### ISSUE TITLE
HELM安装，pod起不来，一直重启

### ISSUE THREAD

**Issue by maodan1985** [TencentBlueKing/bk-cmdb#5592]
问题描述
===========
https://github.com/Tencent/bk-cmdb/blob/master/helm/README.md 用的这个方法 HELM安装

![~Z7FSKS{%SDK@ZZZ2NRXRTP](https://user-images.githubusercontent.com/54883539/129829106-ea672af2-cdee-4ec6-9567-6f1e175af716.png)
pod起不来，一直重启

**Comment by ZQHcode** [comment]
这个已经没有在维护了哈，关于容器化部署cmdb或者整套蓝鲸，可以看下这个链接地址的内容 https://bk.tencent.com/s-mart/community/question/6449?type=answer 查看里面的《部署指引》进行部署
