### ISSUE TITLE
错误，zk按照部署说明的版本搭建的。程序启动报错

### ISSUE THREAD

**Issue by zhang1061260710** [TencentBlueKing/bk-cmdb#5645]
fail to watch children for path(/cc/services/endpoints/cacheservice), err:zk: node does not exist
children node(/cc/services/endpoints/cacheservice) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/topo), err:zk: node does not exist
children node(/cc/services/endpoints/topo) is not exist, will watch after 5s
children node(/cc/services/endpoints/cacheservice) is not exist, will watch after 5s
children node(/cc/services/endpoints/topo) is not exist, will watch after 5s
children node(/cc/services/endpoints/auth) is not exist, will watch after 5s
children node(/cc/services/endpoints/datacollection) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/eventserver), err:zk: node does not exist
children node(/cc/services/endpoints/eventserver) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/auth), err:zk: node does not exist
children node(/cc/services/endpoints/auth) is not exist, will watch after 5s

**Comment by donallin823** [comment]
遇到一样的问题，同问

**Comment by King-Connor** [comment]
遇到同样的问题，绝了，，，

fail to watch children for path(/cc/services/endpoints/datacollection), err:zk: node does not exist
children node(/cc/services/endpoints/datacollection) is not exist, will watch after 5s
children node(/cc/services/endpoints/cloud) is not exist, will watch after 5s
children node(/cc/services/endpoints/auth) is not exist, will watch after 5s
children node(/cc/services/endpoints/datacollection) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/cloud), err:zk: node does not exist
children node(/cc/services/endpoints/cloud) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/auth), err:zk: node does not exist
children node(/cc/services/endpoints/auth) is not exist, will watch after 5s
E0610 11:28:38.428706   60413 collections/hash.go:94] Hash| update services hash values, oops, there is no datacollection can be used

**Comment by ZQHcode** [comment]
这个是在zk进行服务注册发现的问题，可以看下具体是哪个服务没有启动成功，提供下对应的错误日志以及common.yaml文件中的配置，我们协助看下
