### ISSUE TITLE
容器版本 调用新增主机API 报反序列化JSON数据失败

### ISSUE THREAD

**Issue by FrancisDrakeK** [TencentBlueKing/bk-cmdb#5920]
问题描述
===========

![image](https://user-images.githubusercontent.com/42175430/149853834-47348894-8182-46e7-bd42-c159efdaff33.png)
![image](https://user-images.githubusercontent.com/42175430/149853898-e40cf2ef-51d4-48e0-b5e2-be3d8dbb3d76.png)
![image](https://user-images.githubusercontent.com/42175430/149853941-30ddd5d9-4538-497c-aa3b-ce8ebf0d7824.png)

使用版本为容器版本
请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [x] Redis     版本: 
 - [x] MongoDB   版本: 
 - [x] ZooKeeper 版本: 
 - [x] 操作系统      : 
 - [x] bk-cmdb 异常日志

**Comment by wjyfelen** [comment]
看提示是json反序列化失败。 请提供一下具体的版本信息，接口的调用方式根据不同版本可能略有不同，例如V3.10.x 接口文档路径如下:https://github.com/TencentBlueKing/bk-cmdb/tree/v3.10.x/docs/apidoc/cc/zh_hans

**Comment by zhucaipeng** [comment]
我也遇到这个“json反序列化失败”的问题， 请问用curl如何 正确操作api 添加主机，能不能会给一个举例?

**Comment by FrancisDrakeK** [comment]
> 我也遇到这个“json反序列化失败”的问题， 请问用curl如何 正确操作api 添加主机，能不能会给一个举例?

![image](https://user-images.githubusercontent.com/42175430/226284381-5249c3da-020d-4614-977e-0ffb75199e2a.png)
尝试使用以上方法

**Comment by zhucaipeng** [comment]
> 

还是报“序列化JSON数据失败”

![image](https://user-images.githubusercontent.com/18751306/226321479-30e9ddf1-9cf1-4310-8427-c762652eb198.png)
