### ISSUE TITLE
镜像部署异常

### ISSUE THREAD

**Issue by zmengle** [TencentBlueKing/bk-cmdb#5966]
问题描述
===========
按照官方的镜像部署方式部署完成后部分功能无法正常使用
ps：部署过程出现文件权限问题已经参考其他问题解决
1、登录8081端口访问正常，跳转8090无法访问
![企业微信截图_16449114908198](https://user-images.githubusercontent.com/21135502/154453328-fd98ac89-6340-41d4-a4c1-6e22cbeb24f3.png)
2、系统异常，使用8081登录后使用url访问，提示系统异常
![企业微信截图_16449126921871](https://user-images.githubusercontent.com/21135502/154453461-abf8fa7d-b133-46d6-9adc-afd19e8e5162.png)

重现方法
================
镜像部署必现，部署版本v3.9.28
![企业微信截图_1645001912784](https://user-images.githubusercontent.com/21135502/154455128-1141e19c-e8b4-4b0e-b097-db0963444d32.png)

关键信息
=========
1、镜像部署完成，日志提示ok
![企业微信截图_16449115651862](https://user-images.githubusercontent.com/21135502/154454576-6a9c2308-c9aa-4ab8-bf7a-1b343b7ab87d.png)
2、admin/logs 提示信息致命错误mongo连接超时，mongo服务正常
![企业微信截图_1644912942870](https://user-images.githubusercontent.com/21135502/154454888-456b8d95-0b25-4951-a860-306c474088ad.png)
![企业微信截图_16450007914245](https://user-images.githubusercontent.com/21135502/154454947-3c644088-cbae-4725-b175-e869fd474944.png)

请提供以下信息:

 - [x] bk-cmdb   版本: v3.9.28

麻烦看下

**Comment by breezelxp** [comment]
8090端口是什么服务？
