### ISSUE TITLE
API使用说明文档里面和源码对应不上，请问这些文档还在维护吗？

### ISSUE THREAD

**Issue by KingSuo** [TencentBlueKing/bk-cmdb#6111]
问题描述
===========

API使用说明文档里面的接口和源码对应不上，比如API使用说明文档v3.1中【[添加对象模型](https://github.com/Tencent/bk-cmdb/blob/master/docs/apidoc/v3.1/object_model.md#%E6%B7%BB%E5%8A%A0%E5%AF%B9%E8%B1%A1%E6%A8%A1%E5%9E%8B)】接口是`/api/{version}/object`，在v3.10.x分支源码中找到的对应接口是`/api/v3/create/object`，类似这样的还有很多，请问这些文档还在维护吗？

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本:  v3.10.x分支
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by ToughLama** [comment]
文档问题很多，虽然开源，但是不积极

**Comment by yyf365** [comment]
同问，感觉这个项目很随意啊？

**Comment by wjyfelen** [comment]
你好，文档同样是分版本进行维护的，如果是v3.10.x版本的接口请在对应的分支api文档中查阅调用方式:，具体链接如下: https://github.com/TencentBlueKing/bk-cmdb/tree/v3.10.x/docs/apidoc/cc/zh_hans
