### ISSUE TITLE
CMDB 编译指南找个靠谱的人写下

### ISSUE THREAD

**Issue by ToughLama** [TencentBlueKing/bk-cmdb#6120]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by ZQHcode** [comment]
是按照文档编译的时候遇到什么问题了么？可以发出来看下哈

**Comment by ToughLama** [comment]
编译的时候，GO111MODULE="off"才行，文档也很旧，写的也不清不楚的，社区版的文档也是一个样

**Comment by yuuagoo** [comment]
> 编译的时候，GO111MODULE="off"才行，文档也很旧，写的也不清不楚的，社区版的文档也是一个样

这是golang的环境配置，主要看你代码放在哪个路径，放在gopath下，设置成auto也是ok的
