### ISSUE TITLE
windows下monstache不支持编译为动态库

### ISSUE THREAD

**Issue by hunterlau2020** [TencentBlueKing/bk-cmdb#6125]
问题描述
===========
windows下monstache不支持编译为动态库

重现方法
================
提示-buildmode=c-shared not supported on windows/amd64

关键信息
=========
建议Makefile增加windows判断

BINDIR = ${OUTPUT_DIR}/monstache
ifeq ($(LANG),)
TARGET_NAME=windows
else
TARGET_NAME=linux
endif

default:${TARGET_NAME}

linux:
	go build -buildmode=plugin -o $(BINDIR)/etc/$(TARGET).so *.go
	@cp -rf etc/config.toml $(BINDIR)/etc
	@cp -rf etc/extra.toml $(BINDIR)/etc
	@cp -rf monstache.sh $(BINDIR)
	@cp -rf CHANGELOG.md $(BINDIR)
	@cp -rf README.md $(BINDIR)

windows:
	go build -buildmode=c-archive -o $(BINDIR)/etc/$(TARGET).a *.go
	@cp -rf etc/config.toml $(BINDIR)/etc
	@cp -rf etc/extra.toml $(BINDIR)/etc
	@cp -rf monstache.sh $(BINDIR)
	@cp -rf CHANGELOG.md $(BINDIR)
	@cp -rf README.md $(BINDIR)

**Comment by ZQHcode** [comment]
感谢您的建议，后续这块我们会自己实现，不依赖于monstache，目前已经在规划之中，敬请期待哈
