### ISSUE TITLE
【3.10.11】全文检索查询失败

### ISSUE THREAD

**Issue by hongyuxuan** [TencentBlueKing/bk-cmdb#6172]
问题描述
===========
在模型新建分组，新分组下新建模型，并插入数条数据，进入首页-全文检索，输入关键词，页面弹框报错：查询检索内容失败。正常应该出现检索内容

![image](https://user-images.githubusercontent.com/5389643/171979930-f1564aaf-db2d-4ba9-a75e-31a789b54713.png)

重现方法
================
模型新建分组、新建模型、插入数据，在首页进行全文检索。

关键信息
=========
已安装Elasticsearch、Monstache插件，并且在页面插入数据后，通过访问ES的9200端口，进入ES能查到刚刚插入的数据
查看ES索引：
![image](https://user-images.githubusercontent.com/5389643/171980550-8dafa7b8-17e6-4bf1-8e9b-672cae10b713.png)

请提供以下信息:

 - [x] bk-cmdb   版本: 3.10.11
 - [x] Redis     版本: 4.0.12
 - [x] MongoDB   版本: 4.2.8
 - [x] ZooKeeper 版本: 3.4.11
 - [x] 操作系统      : rhel7.9
 - [x] Elasticsearch 版本: 7.10.0
 - [x] Monstache 版本: 6.7.7
 - [x] bk-cmdb 异常日志
Monstache报错日志：
```shell
ERROR 2022/06/04 13:57:28 Bulk response item: {"_index":"cmdb.cc_objattdes","_type":"_doc","_id":"629ac29b9327ffa78e5c96b9","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [create_time] of type [date] in document with id '629ac29b9327ffa78e5c96b9'. Preview of field's value: '{}'","caused_by":{"reason":"Can't get text on a START_OBJECT at 1:275","type":"illegal_state_exception"}}}
ERROR 2022/06/04 11:51:05 Bulk response item: {"_index":"cmdb.cc_objattdes","_type":"_doc","_id":"629ad6a7727c7815055c8924","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse field [option] of type [text] in document with id '629ad6a7727c7815055c8924'. Preview of field's value: '{min=, max=}'","caused_by":{"reason":"Can't get text on a START_OBJECT at 1:471","type":"illegal_state_exception"}}}
```

**Comment by wjyfelen** [comment]
看样子是没有对应的索引，可以按照提示排查下，  目前cmdb是只能搜索指定的索引的内容，看回显没有模型的索引，就是cmdb.mode 开头的索引。可以清掉es内容 重建下索引试试

**Comment by wbpyer** [comment]
我也遇到了这个问题，这个看起来像是索引的问题。
