### ISSUE TITLE
cmdb编译cmdb_cloudserver失败，居然没有代码包，发布前是否真的编译过？

### ISSUE THREAD

**Issue by King-Connor** [TencentBlueKing/bk-cmdb#6182]
问题描述
===========
 参考“https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/installation.md”指导，下载了最新[v3.10.11](https://github.com/Tencent/bk-cmdb/releases/tag/release-v3.10.11) 版本，编译直接报错。

重现方法
================

**进入src目录下，输入 make，报错如下**

**building the target: cmdb_cloudserver...** 

go build -i -ldflags "-X configcenter/src/common/version.CCVersion=master -X configcenter/src/common/version.CCBuildTime=2022-06-08T10:55:17+0800 -X configcenter/src/common/version.CCGitHash=6ffaae6a7a625c8086f2669360c12606d04a66bd -X configcenter/src/common/version.CCTag=master -X configcenter/src/common/version.CCDistro=community" -o /home/gopath/src/configcenter/src/bin/build/master/cmdb_cloudserver/cmdb_cloudserver
._./../../vendor/github.com/aws/aws-sdk-go/aws/awsutil/path_value.go:9:2: cannot find package "configcenter/vendor/github.com/jmespath/go-jmespath" in:
	/home/gopath/src/configcenter/vendor/github.com/jmespath/go-jmespath_
make[1]: *** [cmdb_cloudserver] Error 1
make[1]: Leaving directory `/home/gopath/src/configcenter/src/scene_server/cloud_server'
make: *** [default] Error 2

检测发布包vendor目录，发现vendor/github.com/根本就没有“jmespath/go-jmespath”

很怀疑社区发布有人维护没？

**Comment by liucy1983** [comment]
jmespath在configcenter/vendor/github.com/aws/aws-sdk-go/vendor/github.com/下面，你看有没有
