### ISSUE TITLE
关于使用-如何为模块间构建数据流关系

### ISSUE THREAD

**Issue by set-daemon** [TencentBlueKing/bk-cmdb#6257]
问题描述
===========

 模块间的数据流关系怎么做标识，且能够以拓扑的方式可视化显示？

**Comment by ZQHcode** [comment]
> # 问题描述
> 模块间的数据流关系怎么做标识，且能够以拓扑的方式可视化显示？

你好，有没有具体的想实现的例子呢，简单描述下哈
