### ISSUE TITLE
toposerver 一有请求就会挂掉。

### ISSUE THREAD

**Issue by yangshii** [TencentBlueKing/bk-cmdb#6275]
问题描述
===========
启动toposerver后，一访问页面 ，toposerver就会挂掉。

重现方法
================

启动toposerver  访问web页面

关键信息
=========

E0728 18:06:43.899379     773 rdapi/rdfunc.go:50] server panic, err:"invalid memory address or nil pointer dereference", rid:cc0000cbh5zcx0jxeg000mdkqg, debug strace:goroutine 27 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
configcenter/src/common/rdapi.AllGlobalFilter.func1.1()

 - [x] bk-cmdb   版本: 
./cmdb_toposerver --version
Version     : master
Tag         : master
BuildTime   : 2022-07-27T17:39:02+0800
GitHash     : eeb180e74809aca64203b3b2ebcd3a0b57bce4ca
RunMode     : product
Distribution: community
ServiceName : topo

**Comment by ZQHcode** [comment]
麻烦提供下toposerver的启动参数，还有配置文件的内容

**Comment by yangshii** [comment]
> 麻烦提供下toposerver的启动参数，还有配置文件的内容

`#!/bin/bash

set -e

# get local IP.
localIp=`python ip.py`

# make log-dir if not exists.
if [[ ! -d "./logs" ]];then
    mkdir ./logs
fi

# set execute
chmod +x cmdb_toposerver
./cmdb_toposerver --addrport=${localIp}:60002 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181  --enable-auth=false  > ./logs/std.log 2>&1 &
`

**Comment by ZQHcode** [comment]
在最新的代码中没有成功复现出这个问题，可以用最新的代码试试，如果还是不行，麻烦给下cmdb_adminserver/configures/common.yaml文件里的内容
