### ISSUE TITLE
cmdb部署完提示系统出现异常

### ISSUE THREAD

**Issue by openstack-test** [TencentBlueKing/bk-cmdb#6305]
# 问题描述
编译部署了开源版cmdb （v3.10.11 tag）。编译和部署一切正常，访问系统报如下错误，无法找到问题原因，能帮看看么，谢谢

![_L7M`SDV6`95)TD8D IA)I](https://user-images.githubusercontent.com/12166405/184580428-e9148d48-ace2-414e-9ee0-76bfc98a8d25.jpg)

![image](https://user-images.githubusercontent.com/12166405/184580485-b3afecf4-6eff-433e-8e84-b96452129a3c.png)

# 请提供以下信息:
cmdb各服务均处于运行状态（未部署Elasticsearch 和Monstach）。

 
- ZooKeeper ：3.4.12
- Redis : 3.2.12
- MongoDB：  4.2.8
- 操作系统      : centos 7

亟需帮助，谢谢！

**Comment by ZQHcode** [comment]
可以用请求头里的Cc_Request_Id，在日志文件中grep看下报错原因，日志文件在每个服务的logs文件中

**Comment by openstack-test** [comment]
@ZQHcode  你好，我找了好几个cc_request_id，日志中都没有找到，麻烦帮忙指导下呢，谢谢
![image](https://user-images.githubusercontent.com/12166405/184627350-17cbc47e-6ae6-44b5-ae85-002e8a8c5df7.png)

**Comment by openstack-test** [comment]
社区没人看看这个问题吗？

**Comment by ZQHcode** [comment]
> @ZQHcode 你好，我找了好几个cc_request_id，日志中都没有找到，麻烦帮忙指导下呢，谢谢 ![image](https://user-images.githubusercontent.com/12166405/184627350-17cbc47e-6ae6-44b5-ae85-002e8a8c5df7.png)
> 
> 备注：我是通过外部nginx转发到cmdb-webserver 地址和8083端口访问的。

nginx转发配置不对吧，页面的请求是到websever的，302了

**Comment by openstack-test** [comment]
@ZQHcode 那我应该转发到哪个服务和端口？怎么配置，默认提供的不符合我们环境

**Comment by openstack-test** [comment]
提供一个范例嘛

**Comment by wcs124255** [comment]
你好，请问你这个问题解决掉了嘛

**Comment by ZQHcode** [comment]
> 提供一个范例嘛

这个可以看下webserver的具体的ip和端口，然后配置下
