### ISSUE TITLE
快速启动异常

### ISSUE THREAD

**Issue by crazychengmm** [TencentBlueKing/bk-cmdb#6326]
问题描述
===========
使用镜像快速启动，发现日志有报错信息
![image](https://user-images.githubusercontent.com/23517542/187378197-772cce3f-0f64-4667-a268-2eed1c6f680f.png)

重现方法
================
docker run -d -p 8081:8090 ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest
![image](https://user-images.githubusercontent.com/23517542/187378392-965e7741-2b71-46f5-99cb-7670a93709ed.png)

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by crazychengmm** [comment]
操作页面很多功能都不能使用了

**Comment by ZQHcode** [comment]
关于容器化部署cmdb或者整套蓝鲸，可以看下这个链接地址的内容 https://bk.tencent.com/s-mart/community/question/6449?type=answer 查看里面的《部署指引》进行部署

**Comment by terry8210** [comment]
能否修改IP呢，不要127.0.0.1

**Comment by ZQHcode** [comment]
> 能否修改IP呢，不要127.0.0.1

请问这个指的是什么呢
