### ISSUE TITLE
开源版部署完后进入平台后出现异常

### ISSUE THREAD

**Issue by wcs124255** [TencentBlueKing/bk-cmdb#6333]
问题描述
===========
部署后，在进入页面平台后出现异常，出现server selection timeout问题，但是试了好久没解决掉

![6f77541a351258e9ad1e6f0706bf22a](https://user-images.githubusercontent.com/82073342/188421773-5dea7fb3-31e5-4e79-aac0-47b6d184c043.jpg)
![ee9fa4753a6b44e179f6b0260dfadc5](https://user-images.githubusercontent.com/82073342/188421812-2a2ce70f-81dd-4621-887a-ec1558b25749.jpg)
![b7ddfdf7c56f62ef0a46d9249b3168c](https://user-images.githubusercontent.com/82073342/188421845-2d8cf4ad-327c-4749-bd75-274f603fae06.jpg)

 - [ ] Redis      3.2.11
 - [ ] MongoDB   4.4.15
 - [ ] ZooKeeper 3.4.12
 - [ ] 操作系统       Centos 7
 - [ ] bk-cmdb 异常日志       
E0905 17:56:29.295585   99492 logics/index.go:79] Check whether the db initialization is complete error. err: getVersion failed, err: server selection error: server selection timeout
current topology: Type: Single
Servers:
Addr: 192.168.52.132:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(192.168.52.132:27017[-13293]) connection is closed
 rid: cc0000ccartpf170ho995ks0j0

**Comment by wcy00000000000000** [comment]
mongodb需要使用集群模式部署，可以参考这个文档： https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/installation.md#2-%E5%AE%89%E8%A3%85mongodb%E5%90%8E%E9%85%8D%E7%BD%AE%E9%9B%86%E7%BE%A4%E5%88%9B%E5%BB%BA%E6%95%B0%E6%8D%AE%E5%BA%93-cmdb

**Comment by wcs124255** [comment]
> mongodb需要使用集群模式部署，可以参考这个文档： https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/installation.md#2-%E5%AE%89%E8%A3%85mongodb%E5%90%8E%E9%85%8D%E7%BD%AE%E9%9B%86%E7%BE%A4%E5%88%9B%E5%BB%BA%E6%95%B0%E6%8D%AE%E5%BA%93-cmdb

是按照这个部署的呢   出现的问题都是在mongo这里

**Comment by ZQHcode** [comment]
> > mongodb需要使用集群模式部署，可以参考这个文档： https://github.com/Tencent/bk-cmdb/blob/master/docs/overview/installation.md#2-%E5%AE%89%E8%A3%85mongodb%E5%90%8E%E9%85%8D%E7%BD%AE%E9%9B%86%E7%BE%A4%E5%88%9B%E5%BB%BA%E6%95%B0%E6%8D%AE%E5%BA%93-cmdb
> 
> 是按照这个部署的呢 出现的问题都是在mongo这里

mongo需要是Replica Sets模式，检查下是否已经配置成功了，如果没有的话，按照上述文档配置下，看看是哪一步出错了

**Comment by herico516** [comment]
**### init_db执行成功**
登录页面：
![image](https://user-images.githubusercontent.com/2703682/192683009-7b20e5ea-b9d9-41b3-99d4-4cf394a3bfc6.png)

**### cmdb_adminserver报错：**
0928 11:24:18.480959   27830 configcenter/viper.go:397] config watch.maxIdleConns less than minimum value, use minimum value 50
E0928 11:32:38.004611   27830 v3.0.8/addPresetObjects.go:126] add data for  cc_PropertyGroup table 
E0928 11:32:38.036072   27830 v3.0.8/addPresetObjects.go:100] add data for  cc_ObjDes table 
E0928 11:32:38.252975   27830 v3.0.8/addPresetObjects.go:56] add data for  cc_ObjAsst table 
E0928 11:32:38.256541   27830 v3.0.8/addPresetObjects.go:67] add data for  cc_ObjAsst table  
E0928 11:32:40.624614   27830 logics/index.go:597] "obj(set). The unique index does not support the field type. Field name: ", rid: "cc0000ccps0lp10rcauei72b7g"
E0928 11:32:40.624629   27830 logics/index.go:393] object(set) logic unique to db index error. err: obj(set). The unique index does not support the field type. Field name: , rid: cc0000ccps0lp10rcauei72b7g
E0928 11:32:40.624633   27830 logics/index.go:105] model table sync error. err: obj(set). The unique index does not support the field type. Field name: , rid: cc0000ccps0lp10rcauei72b7g

**### cmdb_webserver报错信息：**
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0928 11:24:41.760254   28223 opensource/userinfo.go:63] login user not found, rid: cc0000ccprsu910rcarculeo9g
E0928 11:24:41.763256   28223 middleware/login.go:110] session key bk_token not found, rid: cc0000ccprsu910rcarculeoa0

**Comment by ZQHcode** [comment]
可以检查下cmdb各个服务是否都已经启动成功，提供下错误日志以及配置文件，我看下
