### ISSUE TITLE
auth模块如何使用

### ISSUE THREAD

**Issue by mini-tiger** [TencentBlueKing/bk-cmdb#6354]
问题描述
===========
我使用的是 3.9.39版本，auth 模块如何使用， 有没有说明文档

**Comment by ZQHcode** [comment]
authserver启用需要连接权限中心 https://github.com/TencentBlueKing/bk-iam，在common.yaml文件里的authServer处配置地址等信息，以及在服务启动脚本里--enable-auth=false改为true。当然，不启动authserver，除了没有进行鉴权，不影响功能的正常使用哈

**Comment by mini-tiger** [comment]
3.9.39代码里src auth_servce是否就是iam的功能，另外程序是不是要访问公网，是访问哪个域名，我这边的环境需要开通才能访问

**Comment by ZQHcode** [comment]
iam是另一个项目，需要单独部署，然后在cmdb这边配置相关的地址接入

> 3.9.39代码里src/…/auth_servce是否就是iam的功能，另外程序是不是要访问公网，是访问哪个域名，我这边的环境需要开通才能访问

**Comment by mini-tiger** [comment]
代码中 src/scene_server/auth_server 是做什么的

**Comment by ZQHcode** [comment]
> 代码中 src/scene_server/auth_server 是做什么的

鉴权相关的接口，主要是封装了cmdb自己的逻辑和调用iam的接口

**Comment by WangBoHan1** [comment]
能否出一个配置bk-iam鉴权系统的指引？我按照上述流程配置好了bk-iam，在cmdb中成功启动了auth-server，无法在浏览器打开cmdb的管理界面了。
bk-iam访问信息：
time="2022-11-22T01:28:57-08:00" level=debug msg="Middleware: RequestID"
[GIN] 2022/11/22 - 01:28:57 | 404 |      31.787µs |   192.168.214.1 | GET      "/favicon.ico"

web界面访问信息：
浏览器访问ip:8090端口时，提示访问被拒绝

**Comment by ZQHcode** [comment]
> 能否出一个配置bk-iam鉴权系统的指引？我按照上述流程配置好了bk-iam，在cmdb中成功启动了auth-server，无法在浏览器打开cmdb的管理界面了。 bk-iam访问信息： time="2022-11-22T01:28:57-08:00" level=debug msg="Middleware: RequestID" [GIN] 2022/11/22 - 01:28:57 | 404 | 31.787µs | 192.168.214.128 | GET "/favicon.ico"
> 
> web界面访问信息： 浏览器访问ip:8090端口时，提示访问被拒绝 未配置auth-server时，是可以通过8090端口访问到cmdb服务的

是已经成功搭建了 https://github.com/TencentBlueKing/bk-iam这里的iam系统了吗，它是否能正常使用？如果是正常的，麻烦提供下authserver和webserver的ERROR日志，我这边看下原因

**Comment by WangBoHan1** [comment]
> > 能否出一个配置bk-iam鉴权系统的指引？我按照上述流程配置好了bk-iam，在cmdb中成功启动了auth-server，无法在浏览器打开cmdb的管理界面了。 bk-iam访问信息： time="2022-11-22T01:28:57-08:00" level=debug msg="Middleware: RequestID" [GIN] 2022/11/22 - 01:28:57 | 404 | 31.787µs | 192.168.214.128 | GET "/favicon.ico"
> > web界面访问信息： 浏览器访问ip:8090端口时，提示访问被拒绝 未配置auth-server时，是可以通过8090端口访问到cmdb服务的
> 
> 是已经成功搭建了 https://github.com/TencentBlueKing/bk-iam 这里的iam系统了吗，它是否能正常使用？如果是正常的，麻烦提供下authserver和webserver的ERROR日志，我这边看下原因

> 
bk-iam已部署，运行正常；
auth-server 日志没有报错，运行正常；
webserver的ERROR log：

`Log file created at: 2022/11/23 01:31:05
Running on machine: bc971a5bbb8a
Binary: Built with gc go1.15.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1123 01:31:05.596817    2589 middleware/login.go:107] session key bk_token not found, rid: cc0000cdunfm8tadagk7bgdkkg`

以上。
怀疑是我在配置authserver上有一些问题，所以想确认一下authserver的一些配置项的具体信息是否正确：
--auth_scheme iam --auth_enabled true ----auth_address ip:9000 --auth_app_code bk_cmdb --auth_app_secret <identipass>
其中identipass是自定义的秘钥串，这样的配置是否正确。不正确应该如何修复
