### ISSUE TITLE
cmdb_webserver 启动不了

### ISSUE THREAD

**Issue by wang00** [TencentBlueKing/bk-cmdb#6375]
问题描述
===========

cmdb_webserver 启动不了

重现方法
================
 process count should be: 12 , now: 12
Not Running: cmdb_apiserver
Not Running: cmdb_authserver
Not Running: cmdb_webserver

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 Version     : master
Tag         : master
BuildTime   : 2022-09-19T13:59:29+0800
GitHash     : ff7a0896a3b253c74d76f43eca603e6ff84b5829
RunMode     : product
Distribution: community
ServiceName : apiserver
 -->
 - [ ] Redis     版本:3.2.12
 - [ ] MongoDB   版本: 4.4.16
 - [ ] ZooKeeper 版本: 3.5.7
 - [ ] 操作系统      : centos7.6 
 - [ ] bk-cmdb 异常日志begin to discover by watch children of path(/cc/services/endpoints/auth)
children node(/cc/services/endpoints/apiserver) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/apiserver), err:zk: node does not exist
children node(/cc/services/endpoints/apiserver) is not exist, will watch after 5s
children node(/cc/services/endpoints/auth) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/webserver), err:zk: node does not exist
children node(/cc/services/endpoints/webserver) is not exist, will watch after 5s
children node(/cc/services/endpoints/webserver) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/auth), err:zk: node does not exist
children node(/cc/services/endpoints/auth) is not exist, will watch after 5s
panic: open ../web/index.html: no such file or directory

goroutine 1 [running]:
html/template.Must(...)
	/data/cmdb/go/src/html/template/template.go:374
github.com/gin-gonic/gin.(*Engine).LoadHTMLFiles(0xc0005ac340, {0xc0000481e0, 0x2, 0x2})
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:244 +0x2ec
configcenter/src/web_server/service.(*Service).WebService(0xc000082f80)
	/data/cmdb/configcenter/src/web_server/service/service.go:82 +0x369
configcenter/src/web_server/app.Run({0x13e46a0, 0xc000082f00}, 0x46769b, 0xc00073ff48)
	/data/cmdb/configcenter/src/web_server/app/server.go:108 +0x7f9
main.main()
	/data/cmdb/configcenter/src/web_server/ui.go:44 +0x1cf

**Comment by wang00** [comment]
可以帮忙回答？

**Comment by wjyfelen** [comment]
panic: open ../web/index.html: no such file or directory
  看下配置文件配置的web包路径是不是放错位置  在common.yaml 中的 
# 前端基础页面位置
htmlRoot:

**Comment by wang00** [comment]
#    htmlRoot: /data/cmdb/web
在common是注释

**Comment by wang00** [comment]
#  cryptor:
#    checkUrl: http://127.0.0.1/login/accounts/get_user/?bk_token=
#    bkAccountUrl: http://127.0.0.1/login/accounts/get_all_user/?bk_token=%s
#    resourcesPath: /tmp/
#    htmlRoot: /data/cmdb/web

**Comment by wang00** [comment]
这个目录是编译目录：/data/cmdb/configcenter/src/web_server/service/。 这个目录是压缩后目录：/data/cmdb/cmdb/cmdb/

**Comment by wang00** [comment]
报错怎么是这个目录
main.main()
/data/cmdb/configcenter/src/web_server/ui.go:44 +0x1cf

**Comment by wang00** [comment]
这个问题是代码版本导致的？

**Comment by wcy00000000000000** [comment]
> 这个目录是编译目录：/data/cmdb/configcenter/src/web_server/service/。 这个目录是压缩后目录：/data/cmdb/cmdb/cmdb/

看这段描述cmdb的工作目录是：/data/cmdb/cmdb/cmdb/，正常情况下web目录是在工作目录里的，但是设置的web目录路径是/data/cmdb/web，两者不匹配
请确认一下环境上web目录的位置，可以把htmlRoot设置为实际的web目录的路径，或者把web包挪到/data/cmdb/web处
