### ISSUE TITLE
云账号不支持aws中国可用区

### ISSUE THREAD

**Issue by spublinux** [TencentBlueKing/bk-cmdb#6376]
问题描述
===========

云账号不支持aws中国可用区

重现方法
================

aws.go 无中国区cn-north-1(北京) cn-northwest-1(宁夏)

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
Version     : v3.10.15
Tag         : release-v3.10.15
BuildTime   : 2022-04-25T16:56:36+0800
GitHash     : b8505da96bde941ccddd5d84e83893f7d97dd725
RunMode     : product
Distribution: community
ServiceName : apiserver

 - [ ] Redis     版本: 5.0.9
 - [ ] MongoDB   版本: db version v4.2.3
 - [ ] ZooKeeper 版本: Zookeeper version: 3.4.14-
 - [ ] 操作系统      : CentOS7.9

 - [ ] bk-cmdb 异常日志
E0922 10:36:36.294904    4852 logics/cloud.go:40] AccountVerify GetRegions failed, AccountID:0, err:AuthFailure: AWS was not able to validate the provided access credentials
        status code: 401, request id: 524e7ddb-c9c1-47d0-a7c9-d07072d678fc, rid:cc0000ccnwmd1y72s0000k4jk0
E0922 10:36:36.294951    4852 service/account.go:42] cloud account verify failed, cloudvendor:"1", err :AuthFailure: AWS was not able to validate the provided access credentials
        status code: 401, request id: 524e7ddb-c9c1-47d0-a7c9-d07072d678fc, rid: "cc0000ccnwmd1y72s0000k4jk0"

**Comment by ZQHcode** [comment]
目前暂不支持
