### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by wcs124255** [TencentBlueKing/bk-cmdb#6414]
enter directory:  /home/weichuansi/GoProject/src/configcenter/src/node_modules/fibers/build
make[1]: 进入目录“/home/weichuansi/GoProject/src/configcenter/src/node_modules/fibers/build”
make[1]: *** 没有规则可以创建“Makefile”需要的目标“../../../Library/Caches/node-gyp/18.1.0/include/node/common.gypi”。 停止。
make[1]: 离开目录“/home/weichuansi/GoProject/src/configcenter/src/node_modules/fibers/build”
make: *** [default] 错误 2

**Comment by ZQHcode** [comment]
> enter directory: /home/weichuansi/GoProject/src/configcenter/src/node_modules/fibers/build make[1]: 进入目录“/home/weichuansi/GoProject/src/configcenter/src/node_modules/fibers/build” make[1]: *** 没有规则可以创建“Makefile”需要的目标“../../../Library/Caches/node-gyp/18.1.0/include/node/common.gypi”。 停止。 make[1]: 离开目录“/home/weichuansi/GoProject/src/configcenter/src/node_modules/fibers/build” make: *** [default] 错误 2

麻烦提供下对应的版本信息(可以按照issue模版来)，方便我们快速协助解决问题哈
