### ISSUE TITLE
cannot execute binary file

### ISSUE THREAD

**Issue by stevenchen0018** [TencentBlueKing/bk-cmdb#6443]
问题描述
===========

重新编译上传后，执行./start.sh 后报错cannot execute binary file: Exec format error
是不是编译出问题还是？

重现方法
================

<img width="490" alt="image" src="https://user-images.githubusercontent.com/7030371/198946809-9b04ba21-1e03-4554-8cba-033569b49b21.png">

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [x] Redis     版本: 
 - [x] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [x] bk-cmdb 异常日志

**Comment by stevenchen0018** [comment]
-bash: ./cmdb_adminserver: cannot execute binary file: Exec format error

**Comment by wjyfelen** [comment]
确认下是否编译的平台和运行的平台不匹配，go是支持跨平台交叉编译的

**Comment by stevenchen0018** [comment]
make Linux 的话则会出现以下问题，
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/7030371/198963539-a9e712ef-9677-45be-98b3-044aaa0f720c.png">

**Comment by stevenchen0018** [comment]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/7030371/198973112-54cfbdc3-206e-4cd7-ae0e-bd854567dd0c.png">
<img width="698" alt="image" src="https://user-images.githubusercontent.com/7030371/198973150-24f22103-a9ea-40fb-81ed-04e09cb85672.png">
2个make file 中第2个改成 
试试这个
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
还是一样，问题未解决

**Comment by wjyfelen** [comment]
第二个看下报错信息，这个需要在特定的go版本上编译，应该是go1.13

**Comment by stevenchen0018** [comment]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/7030371/199915713-72256079-656b-4b55-8be5-773341114bb4.png">
也是这样的报错，用go 1.13没办法编译

**Comment by stevenchen0018** [comment]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/7030371/199915892-8581508b-3e9a-4973-8d89-4f5021710520.png">
第二个报错还是差不多，而且通过go1.13无法正常编译
