### ISSUE TITLE
k8s中使用helm安装，执行/data/cmdb/start.sh脚本，启动报错

### ISSUE THREAD

**Issue by boHam-wang** [TencentBlueKing/bk-cmdb#6488]
问题描述
===========

initial configurations success, configs could be found at cmdb_adminserver/configures
--
Tue, Nov 15 2022 11:03:39 am | starting: cmdb_adminserver
Tue, Nov 15 2022 11:03:39 am | starting: cmdb_apiserver
Tue, Nov 15 2022 11:03:39 am | starting: cmdb_authserver
Tue, Nov 15 2022 11:03:39 am | starting: cmdb_cacheservice
Tue, Nov 15 2022 11:03:39 am | starting: cmdb_cloudserver
Tue, Nov 15 2022 11:03:39 am | starting: cmdb_coreservice
Tue, Nov 15 2022 11:03:40 am | starting: cmdb_datacollection
Tue, Nov 15 2022 11:03:40 am | starting: cmdb_eventserver
Tue, Nov 15 2022 11:03:40 am | starting: cmdb_hostserver
Tue, Nov 15 2022 11:03:40 am | starting: cmdb_operationserver
Tue, Nov 15 2022 11:03:40 am | starting: cmdb_procserver
Tue, Nov 15 2022 11:03:40 am | starting: cmdb_taskserver
Tue, Nov 15 2022 11:03:40 am | starting: cmdb_toposerver
Tue, Nov 15 2022 11:03:40 am | starting: cmdb_webserver
Tue, Nov 15 2022 11:03:40 am | root 264 1 4 03:03 ? 00:00:00 ./cmdb_apiserver --addrport=172.190.135.20:8082 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
Tue, Nov 15 2022 11:03:40 am | root 296 1 3 03:03 ? 00:00:00 ./cmdb_authserver --addrport=172.190.135.20:60014 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
Tue, Nov 15 2022 11:03:40 am | root 404 1 1 03:03 ? 00:00:00 ./cmdb_cacheservice --addrport=172.190.135.20:50010 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
Tue, Nov 15 2022 11:03:40 am | root 445 1 3 03:03 ? 00:00:00 ./cmdb_cloudserver --addrport=172.190.135.20:60013 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false --enable_cryptor=false
Tue, Nov 15 2022 11:03:40 am | root 467 1 2 03:03 ? 00:00:00 ./cmdb_coreservice --addrport=172.190.135.20:50009 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
Tue, Nov 15 2022 11:03:40 am | root 489 1 3 03:03 ? 00:00:00 ./cmdb_datacollection --addrport=172.190.135.20:60005 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
Tue, Nov 15 2022 11:03:40 am | root 513 1 2 03:03 ? 00:00:00 ./cmdb_eventserver --addrport=172.190.135.20:60009 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
Tue, Nov 15 2022 11:03:40 am | root 535 1 2 03:03 ? 00:00:00 ./cmdb_hostserver --addrport=172.190.135.20:60001 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
Tue, Nov 15 2022 11:03:40 am | root 560 1 0 03:03 ? 00:00:00 ./cmdb_operationserver --addrport=172.190.135.20:60011 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
Tue, Nov 15 2022 11:03:40 am | root 584 1 0 03:03 ? 00:00:00 ./cmdb_procserver --addrport=172.190.135.20:60003 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
Tue, Nov 15 2022 11:03:40 am | root 610 1 0 03:03 ? 00:00:00 ./cmdb_taskserver --addrport=172.190.135.20:60012 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
Tue, Nov 15 2022 11:03:40 am | root 633 1 0 03:03 ? 00:00:00 ./cmdb_toposerver --addrport=172.190.135.20:60002 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
Tue, Nov 15 2022 11:03:40 am | root 657 1 0 03:03 ? 00:00:00 ./cmdb_webserver --addrport=172.190.135.20:8090 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
Tue, Nov 15 2022 11:03:40 am | process count should be: 12 , now: 13
Tue, Nov 15 2022 11:03:40 am | Not Running: cmdb_adminserver
Tue, Nov 15 2022 11:03:43 am | localIp:172.190.135.20
Tue, Nov 15 2022 11:03:43 am | % Total % Received % Xferd Average Speed Time Time Time Current
Tue, Nov 15 2022 11:03:43 am | Dload Upload Total Spent Left Speed
Tue, Nov 15 2022 11:03:43 am | 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0curl: (7) Failed connect to 192.168.214.218:60004; Connection refused

</body>
</html> -->

这将会导致pod内8090端口并未被监听，配置service后，无法访问502

**Comment by ZQHcode** [comment]
关于容器化部署cmdb或者整套蓝鲸，可以看下这个链接地址的内容 https://bk.tencent.com/s-mart/community/question/6449?type=answer 查看里面的《部署指引》进行部署
