### ISSUE TITLE
cmdb启用authserver，已部署bk-iam服务。authserver配置相关参数后服务无法正常使用

### ISSUE THREAD

**Issue by boHam-wang** [TencentBlueKing/bk-cmdb#6512]
> > 能否出一个配置bk-iam鉴权系统的指引？我按照上述流程配置好了bk-iam，在cmdb中成功启动了auth-server，无法在浏览器打开cmdb的管理界面了。 bk-iam访问信息： time="2022-11-22T01:28:57-08:00" level=debug msg="Middleware: RequestID" [GIN] 2022/11/22 - 01:28:57 | 404 | 31.787µs | 192.168.214.128 | GET "/favicon.ico"
> > web界面访问信息： 浏览器访问ip:8090端口时，提示访问被拒绝 未配置auth-server时，是可以通过8090端口访问到cmdb服务的
> 
> 是已经成功搭建了 https://github.com/TencentBlueKing/bk-iam 这里的iam系统了吗，它是否能正常使用？如果是正常的，麻烦提供下authserver和webserver的ERROR日志，我这边看下原因

> 
bk-iam已部署，运行正常；
auth-server 日志没有报错，运行正常；
webserver的ERROR log：

`Log file created at: 2022/11/23 01:31:05
Running on machine: bc971a5bbb8a
Binary: Built with gc go1.15.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E1123 01:31:05.596817    2589 middleware/login.go:107] session key bk_token not found, rid: cc0000cdunfm8tadagk7bgdkkg`

以上。
怀疑是我在配置authserver上有一些问题，所以想确认一下authserver的一些配置项的参数如何配置
--auth_scheme iam --auth_enabled true ----auth_address ip:9000 --auth_app_code bk_iam --auth_app_secret xxxxxx
通过查看官方文档，似乎需要用到蓝鲸智云的开发者中心，来创建一个app，以此获得app_code和app_secret
但我的需求是，只需要安装cmdb服务，并使用bk-iam做鉴权，这样应该如何配置app_code和app_secret

_Originally posted by @WangBoHan1 in https://github.com/Tencent/bk-cmdb/issues/6354#issuecomment-1324456057_

**Comment by ZQHcode** [comment]
> 

是需要用到开发者中心的哈，这块功能需要统一部署才可以使用的
