### ISSUE TITLE
文档问题

### ISSUE THREAD

**Issue by xcxinng** [TencentBlueKing/bk-cmdb#6522]
代码库中没看到有数据库设计文档，是否考虑加一下？ 想学习下，提前感谢大佬～📚

**Comment by ZQHcode** [comment]
> 代码库中没看到有数据库设计文档，是否考虑加一下？ 想学习下，提前感谢大佬～📚

你好，文档这块我们后续会慢慢完善，也欢迎大家一起参与到其中来，可以给我们提交PR，如果OK的话会采纳，进行合入的哈

**Comment by xcxinng** [comment]
好的，期待后续更新
