### ISSUE TITLE
使用非默认域的用户无法正确显示

### ISSUE THREAD

**Issue by shenxg13** [TencentBlueKing/bk-cmdb#6524]
问题描述
===========
如果选择了非默认域的用户，用户无法正常显示。
请问这个问题该如何解决比较好？

重现方法
================
使用非默认域用户

关键信息
=========

@blueking/user-selector的库中去掉了@符以后的内容，导致查询接口报错：
```
// 接口最大支持100条记录，超过100条需要将请求拆分为多个
async function handleBatchSearch (api, usernames, options) {
	const map = getMap(api)
	const unique = [...new Set(usernames)].filter(username => !map.has(username))
	if (!unique.length) {
		return Promise.resolve(getUsers(api, usernames))
	}
	const slices = []
	unique.reduce((slice, username, index) => {
		if (slice.length < 100) {
			**slice.push(username.replace(/@.*/, ''))**
```

请提供以下信息:

 - [x] bk-cmdb   版本: 
[root@bk01 cmdb_apiserver]# ./cmdb_apiserver --version
Version     : v3.10.21
Tag         : 
BuildTime   : 2022-11-30T18:33:04+0800
GitHash     : 
RunMode     : product
Distribution: community
ServiceName : apiserver

**Comment by breezelxp** [comment]
@yangyy 帮忙看下

**Comment by yangyy** [comment]
@shenxg13 感谢反馈，此问题在 `@blueking/user-selector@1.0.9` 1.0.9 版本中已经修复，请在项目中更新依赖后验证。
