### ISSUE TITLE
【3.10.x-feature-agent-id-alpha9】已分配下的主机添加业务拓扑后前端提示no node founded

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6545]
一、前提条件

二 、重现步骤：
进入资源-主机-已分配-点击列表属性配置-添加字段业务拓扑
![image](https://user-images.githubusercontent.com/66291315/208013600-73d9903f-6d8d-48ed-81c8-ca532384a709.png)

三 、预期结果
添加字段后正常显示该字段的信息

四 、实际结果
添加字段后无法正常显示该字段的信息，前端提示no node founded
![image](https://user-images.githubusercontent.com/66291315/208015357-db498587-48fe-4840-83ae-21b52051094b.png)

**Comment by wjyfelen** [comment]
最新版本已经修复
