### ISSUE TITLE
新版本事件订阅功能取消了么

### ISSUE THREAD

**Issue by zbhtz** [TencentBlueKing/bk-cmdb#6565]
问题描述
===========
”事件订阅“功能菜单怎么没了，企业版的cmdb”事件订阅“功能在后续版本还迭代升级么？监听系统资源变化产生的事件接口api是有的，页面上的菜单在哪里？

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
Version  : 3.10.21
Tag      : 
Branch   : v3.3.x
BuildTime: 2019-01-30T11:29:27+0800
GitHash  : a99aabedf7a369387423ad0ab013730c88f4a7b6
RunMode  : product
 -->

**Comment by ZQHcode** [comment]
3.10版本下线了事件订阅功能，改由更加灵活的resource watch功能替代，可以关注issue看下：https://github.com/Tencent/bk-cmdb/issues/5308

**Comment by zbhtz** [comment]
监听系统资源变化产生的事件菜单在哪里？怎么使用？难道是直接调api，盲盒使用？

**Comment by ZQHcode** [comment]
> 监听系统资源变化产生的事件菜单在哪里？怎么使用？难道是直接调api，盲盒使用？
通过接口调用，接口文档在这: https://bk.tencent.com/docs/document/6.1/179/14399

**Comment by zbhtz** [comment]
社区版，没有这个gse_syncdata服务呀？

**Comment by ZQHcode** [comment]
> resource_watch接口不支持获取事件相关记录的前映像吧？如果想获取前映像有什么方法吗？或者能够指定监控某个特定字段的修改的事件吗？现有接口只知道记录有变化，不知道是哪个字段。

事件订阅这块功能是希望用户能利用它感知到数据的变化，能够更快地根据最新的数据进行逻辑处理的哈；如果想要知道实例的历史版本信息，可以查询对应实例的审计信息

**Comment by shenxg13** [comment]
> > resource_watch接口不支持获取事件相关记录的前映像吧？如果想获取前映像有什么方法吗？或者能够指定监控某个特定字段的修改的事件吗？现有接口只知道记录有变化，不知道是哪个字段。
> 
> 事件订阅这块功能是希望用户能利用它感知到数据的变化，能够更快地根据最新的数据进行逻辑处理的哈；如果想要知道实例的历史版本信息，可以查询对应实例的审计信息

您好，我在文档中没找到审计相关的api，能提示一下吗？

**Comment by ZQHcode** [comment]
> > > resource_watch接口不支持获取事件相关记录的前映像吧？如果想获取前映像有什么方法吗？或者能够指定监控某个特定字段的修改的事件吗？现有接口只知道记录有变化，不知道是哪个字段。
> > 
> > 
> > 事件订阅这块功能是希望用户能利用它感知到数据的变化，能够更快地根据最新的数据进行逻辑处理的哈；如果想要知道实例的历史版本信息，可以查询对应实例的审计信息
>  
> 您好，我在文档中没找到审计相关的api，能提示一下吗？

https://github.com/TencentBlueKing/bk-cmdb/blob/v3.10.x/docs/apidoc/cc/zh_hans/list_operation_audit.md 这里哈

**Comment by shenxg13** [comment]
> > > > resource_watch接口不支持获取事件相关记录的前映像吧？如果想获取前映像有什么方法吗？或者能够指定监控某个特定字段的修改的事件吗？现有接口只知道记录有变化，不知道是哪个字段。
> > > 
> > > 
> > > 事件订阅这块功能是希望用户能利用它感知到数据的变化，能够更快地根据最新的数据进行逻辑处理的哈；如果想要知道实例的历史版本信息，可以查询对应实例的审计信息
> > 
> > 
> > 您好，我在文档中没找到审计相关的api，能提示一下吗？
> 
> https://github.com/TencentBlueKing/bk-cmdb/blob/v3.10.x/docs/apidoc/cc/zh_hans/list_operation_audit.md 这里哈

您好，谢谢，不过我咋没在bkce 6.1.2的api网关里看到这个接口？

**Comment by ZQHcode** [comment]
> > > > > resource_watch接口不支持获取事件相关记录的前映像吧？如果想获取前映像有什么方法吗？或者能够指定监控某个特定字段的修改的事件吗？现有接口只知道记录有变化，不知道是哪个字段。
> > > > 
> > > > 
> > > > 事件订阅这块功能是希望用户能利用它感知到数据的变化，能够更快地根据最新的数据进行逻辑处理的哈；如果想要知道实例的历史版本信息，可以查询对应实例的审计信息
> > > 
> > > 
> > > 您好，我在文档中没找到审计相关的api，能提示一下吗？
> > 
> > 
> > https://github.com/TencentBlueKing/bk-cmdb/blob/v3.10.x/docs/apidoc/cc/zh_hans/list_operation_audit.md 这里哈
> 
> 您好，谢谢，不过我咋没在bkce 6.1.2的api网关里看到这个接口？

这个是隐藏的接口，不建议给第三方平台调用，所以没有显示在esb api文档中

**Comment by chenrb** [comment]
> 
这个接口返回operation_detail总是null，怎么获取operation_detail？

**Comment by chenrb** [comment]
> > > > > > resource_watch接口不支持获取事件相关记录的前映像吧？如果想获取前映像有什么方法吗？或者能够指定监控某个特定字段的修改的事件吗？现有接口只知道记录有变化，不知道是哪个字段。
> > > > > 
> > > > > 
> > > > > 事件订阅这块功能是希望用户能利用它感知到数据的变化，能够更快地根据最新的数据进行逻辑处理的哈；如果想要知道实例的历史版本信息，可以查询对应实例的审计信息
> > > > 
> > > > 
> > > > 您好，我在文档中没找到审计相关的api，能提示一下吗？
> > > 
> > > 
> > > https://github.com/TencentBlueKing/bk-cmdb/blob/v3.10.x/docs/apidoc/cc/zh_hans/list_operation_audit.md 这里哈
> > 
> > 
> > 您好，谢谢，不过我咋没在bkce 6.1.2的api网关里看到这个接口？
> 
> 这个是隐藏的接口，不建议给第三方平台调用，所以没有显示在esb api文档中

这个接口返回operation_detail总是null，怎么获取operation_detail？

**Comment by wcy00000000000000** [comment]
> > > > > > > resource_watch接口不支持获取事件相关记录的前映像吧？如果想获取前映像有什么方法吗？或者能够指定监控某个特定字段的修改的事件吗？现有接口只知道记录有变化，不知道是哪个字段。
> > > > > > 
> > > > > > 
> > > > > > 事件订阅这块功能是希望用户能利用它感知到数据的变化，能够更快地根据最新的数据进行逻辑处理的哈；如果想要知道实例的历史版本信息，可以查询对应实例的审计信息
> > > > > 
> > > > > 
> > > > > 您好，我在文档中没找到审计相关的api，能提示一下吗？
> > > > 
> > > > 
> > > > https://github.com/TencentBlueKing/bk-cmdb/blob/v3.10.x/docs/apidoc/cc/zh_hans/list_operation_audit.md 这里哈
> > > 
> > > 
> > > 您好，谢谢，不过我咋没在bkce 6.1.2的api网关里看到这个接口？
> > 
> > 
> > 这个是隐藏的接口，不建议给第三方平台调用，所以没有显示在esb api文档中
> 
> 这个接口返回operation_detail总是null，怎么获取operation_detail？

https://github.com/TencentBlueKing/bk-cmdb/blob/v3.10.x/docs/apidoc/cc/zh_hans/find_audit_by_id.md
