### ISSUE TITLE
cmdb_adminserver启动报错  ip显示异常【Addr: 127.0.01:27017】

### ISSUE THREAD

**Issue by xiao-yueyang** [TencentBlueKing/bk-cmdb#6567]
**cmdb_adminserver启动报错**  

Running on machine: demo1
Binary: Built with gc go1.18.9 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0104 04:35:50.436030    4988 configcenter/viper.go:397] config watch.maxIdleConns less than minimum value, use minimum value 50
E0104 04:35:50.465259    4988 backbone/notice.go:57] log watch failed, will watch after 10s, path: /cc/services/notice/log/192.168.174.128:60004/v, err: zk: node does not exist
E0104 04:36:20.548927    4988 upgrader/register.go:353] get system version error,err:server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [{ Addr: 127.0.01:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup 127.0.01: no such host }, ] }
E0104 04:36:20.548954    4988 logics/index.go:79] Check whether the db initialization is complete error. err: getVersion failed, err: server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [{ Addr: 127.0.01:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup 127.0.01: no such host }, ] } rid: cc0000ceqkgthdcuit1s31t6f0
E0104 04:36:20.548957    4988 logics/index.go:82] db not initialization is complete, rid: cc0000ceqkgthdcuit1s31t6f0
E0104 04:37:10.550986    4988 upgrader/register.go:353] get system version error,err:server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [{ Addr: 127.0.01:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup 127.0.01: no such host }, ] }
E0104 04:37:10.551055    4988 logics/index.go:79] Check whether the db initialization is complete error. err: getVersion failed, err: server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [{ Addr: 127.0.01:27017, Type: Unknown, Last error: connection() error occurred during connection handshake: dial tcp: lookup 127.0.01: no such host }, ] } rid: cc0000ceqkgthdcuit1s31t6f0
E0104 04:37:10.551107    4988 logics/index.go:82] db not initialization is complete, rid: cc0000ceqkgthdcuit1s31t6f0

上面的报错出现了该地址  127.0.01:27017
但是检查不到哪里的配置写错，配置也是通过脚本生成的。

**Comment by ZQHcode** [comment]
ip错了，是「127.0.0.1」吧，少了一个「.」

**Comment by xiao-yueyang** [comment]
> ip错了，是「127.0.0.1」吧，少了一个「.」

这里的报错就是少了一个点，我不太知道这个程序读的哪里的配置，我并没有找到对应的配置是少了一个点的

**Comment by ZQHcode** [comment]
> > ip错了，是「127.0.0.1」吧，少了一个「.」
> 
> 这里的报错就是少了一个点，我不太知道这个程序读的哪里的配置，我并没有找到对应的配置是少了一个点的

cmdb_adminserver/configures/mongodb.yaml 这个配置文件中的mongo配置

**Comment by xiao-yueyang** [comment]
> > > ip错了，是「127.0.0.1」吧，少了一个「.」
> > 
> > 
> > 这里的报错就是少了一个点，我不太知道这个程序读的哪里的配置，我并没有找到对应的配置是少了一个点的
> 
> cmdb_adminserver/configures/mongodb.yaml 这个配置文件中的mongo配置

mongodb:
  host: 192.168.174.128
  port: 27017
  usr: cc
  pwd: "cc"
  database: cmdb
  maxOpenConns: 3000
  maxIdleConns: 100
  mechanism: SCRAM-SHA-1
  rsName: rs0
  #mongo的socket连接的超时时间，以秒为单位，默认10s，最小5s，最大30s。
  socketTimeoutSeconds: 10
  # mongodb事件监听存储事件链的mongodb配置
watch:
  host: 192.168.174.128
  port: 27017
  usr: cc
  pwd: "cc"
  database: cmdb
  maxOpenConns: 10
  maxIdleConns: 5
  mechanism: SCRAM-SHA-1
  rsName: rs0
  socketTimeoutSeconds: 10

**Comment by ZQHcode** [comment]
> > > > ip错了，是「127.0.0.1」吧，少了一个「.」
> > > 
> > > 
> > > 这里的报错就是少了一个点，我不太知道这个程序读的哪里的配置，我并没有找到对应的配置是少了一个点的
> > 
> > 
> > cmdb_adminserver/configures/mongodb.yaml 这个配置文件中的mongo配置
> 
> mongodb: host: 192.168.174.128 port: 27017 usr: cc pwd: "cc" database: cmdb maxOpenConns: 3000 maxIdleConns: 100 mechanism: SCRAM-SHA-1 rsName: rs0 #mongo的socket连接的超时时间，以秒为单位，默认10s，最小5s，最大30s。 socketTimeoutSeconds: 10
> 
> # mongodb事件监听存储事件链的mongodb配置
> watch: host: 192.168.174.128 port: 27017 usr: cc pwd: "cc" database: cmdb maxOpenConns: 10 maxIdleConns: 5 mechanism: SCRAM-SHA-1 rsName: rs0 socketTimeoutSeconds: 10

这是现在的配置么，是否还有上面的错误呢

**Comment by xiao-yueyang** [comment]
> 

还是一样的错误

**Comment by xiao-yueyang** [comment]
> > > > > ip错了，是「127.0.0.1」吧，少了一个「.」
> > > > 
> > > > 
> > > > 这里的报错就是少了一个点，我不太知道这个程序读的哪里的配置，我并没有找到对应的配置是少了一个点的
> > > 
> > > 
> > > cmdb_adminserver/configures/mongodb.yaml 这个配置文件中的mongo配置
> > 
> > 
> > mongodb: host: 192.168.174.128 port: 27017 usr: cc pwd: "cc" database: cmdb maxOpenConns: 3000 maxIdleConns: 100 mechanism: SCRAM-SHA-1 rsName: rs0 #mongo的socket连接的超时时间，以秒为单位，默认10s，最小5s，最大30s。 socketTimeoutSeconds: 10
> > # mongodb事件监听存储事件链的mongodb配置
> > watch: host: 192.168.174.128 port: 27017 usr: cc pwd: "cc" database: cmdb maxOpenConns: 10 maxIdleConns: 5 mechanism: SCRAM-SHA-1 rsName: rs0 socketTimeoutSeconds: 10
> 
> 这是现在的配置么，是否还有上面的错误呢

是的  还是一样的错误

**Comment by ZQHcode** [comment]
> > > > > > ip错了，是「127.0.0.1」吧，少了一个「.」
> > > > > 
> > > > > 
> > > > > 这里的报错就是少了一个点，我不太知道这个程序读的哪里的配置，我并没有找到对应的配置是少了一个点的
> > > > 
> > > > 
> > > > cmdb_adminserver/configures/mongodb.yaml 这个配置文件中的mongo配置
> > > 
> > > 
> > > mongodb: host: 192.168.174.128 port: 27017 usr: cc pwd: "cc" database: cmdb maxOpenConns: 3000 maxIdleConns: 100 mechanism: SCRAM-SHA-1 rsName: rs0 #mongo的socket连接的超时时间，以秒为单位，默认10s，最小5s，最大30s。 socketTimeoutSeconds: 10
> > > # mongodb事件监听存储事件链的mongodb配置
> > > watch: host: 192.168.174.128 port: 27017 usr: cc pwd: "cc" database: cmdb maxOpenConns: 10 maxIdleConns: 5 mechanism: SCRAM-SHA-1 rsName: rs0 socketTimeoutSeconds: 10
> > 
> > 
> > 这是现在的配置么，是否还有上面的错误呢
> 
> 是的 还是一样的错误

麻烦再提供下现在的adminserver日志
