### ISSUE TITLE
release-v3.6.3前端代码存在两个bug

### ISSUE THREAD

**Issue by XB2020520** [TencentBlueKing/bk-cmdb#6568]
问题描述
===========
1.稳定性考虑，暂时无法升级；
2.前端源码拉下来，npm start 启动后，会跳入错误页面，再点一次才会进入首页搜索框；
3.业务菜单点击后，会一直在加载，无法看到菜单内容；
4.连过后端，确认问题与后端代码无关
5.原先无bug的3.6.3版本的代码没有保存
6.2023年1月12日重新拉取release-v3.6.3代码，前端获取包版本冲突，启动报错。

重现方法
================

之前拉取的代码中
1.启动前端，进入localhost:9090，直接进入error页面
2.点击业务菜单进不去

新问题：
1.git clone -b release-v3.6.3 git@github.com:Tencent/bk-cmdb.git
2.进入/src/ui
3.cmd打开命令行
4.npm i显示package.json中包版本冲突
5.npm i --legacy-peer-deps安装包
6.npm start启动失败，报错显示缺失模块

关键信息
=========

请提供以下信息:

 - bk-cmdb   版本: release-v3.6.3
 - node  版本：v14.17.6.
 - vue版本：vue/cli 4.5.13
 
 - [ ] 首页问题
 - [ ] 业务菜单
 - [ ] release-v3.6.3包版本冲突问题

**Comment by wjyfelen** [comment]
@yangyy

**Comment by yangyy** [comment]
请尝试切换 node 版本为 v8.17.0 后重试

**Comment by XB2020520** [comment]
> 

未解决。这个前端源码是不是不能单独启动？？？

**Comment by XB2020520** [comment]
> 请尝试切换 node 版本为 v8.17.0 后重试

未解决。这个前端源码是不是不能单独启动？？？@yangyy

**Comment by yangyy** [comment]
不是，请贴出具体的启动时错误信息

**Comment by XB2020520** [comment]
启动后的内容。跳到错误页面。业务菜单打不开。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月15日(星期天) 下午2:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/bk-cmdb] release-v3.6.3前端代码存在两个bug (Issue #6568)





 
不是，请贴出具体的启动时错误信息

**Comment by XB2020520** [comment]
> 不是，请贴出具体的启动时错误信息

邮件图片发给你了。

**Comment by yangyy** [comment]
@XB2020520 未收到邮件，可否再发送一次
