### ISSUE TITLE
没有编译好的可执行包

### ISSUE THREAD

**Issue by Johnnes-Xnn** [TencentBlueKing/bk-cmdb#6572]
问题描述
===========

众所周知，如果让一个想部署的人，要配置很多环境去编译，是一件很难的事情

重现方法
================

下载各种包，环境依赖，然后去编译
CentOS 7.6的系统

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by ZQHcode** [comment]
有的哈，下面分别是二进制和容器化的地址：

二进制：
https://bk.tencent.com/download_version_list/

容器化：
https://bk.tencent.com/s-mart/community/question/6449?type=answer

**Comment by Johnnes-Xnn** [comment]
我只想部署cmdb，一套太多了

**Comment by ZQHcode** [comment]
> 我只想部署cmdb，一套太多了

可以按照我们的安装部署文档一步步部署下哈，如果中途有遇到什么问题，会为您解答的哈
