### ISSUE TITLE
初始化数据库失败

### ISSUE THREAD

**Issue by Johnnes-Xnn** [TencentBlueKing/bk-cmdb#6573]
问题描述
===========

![image](https://user-images.githubusercontent.com/49221563/215317170-3cc45232-6697-4142-b58f-ec0e91c0d031.png)
详见图片，提示迁移数据失败
查看init_db的脚本，其中请求了60004的端口，实际服务是起来了的
![image](https://user-images.githubusercontent.com/49221563/215317201-4d3c2aa8-3943-426e-a11a-6cc526aad7eb.png)

重现方法
================

关键信息
=========

请提供以下信息:
cmdb的版本是最新版
 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [x] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by Johnnes-Xnn** [comment]
zookeeper一直没连上，
![image](https://user-images.githubusercontent.com/49221563/215322114-8a82d7f7-a94c-4876-a396-2e7e3f242663.png)

**Comment by breezelxp** [comment]
看第一个报错，应该是你的db部署的问题，或者是你在admin server的配置文件里没有配置db的信息
