### ISSUE TITLE
主机相关属性进行高级筛选时不支持忽略大小写

### ISSUE THREAD

**Issue by shenxg13** [TencentBlueKing/bk-cmdb#6579]
问题描述
===========
主机相关属性进行高级筛选时不支持忽略大小写

重现方法
================
对主机相关属性进行高级筛选

关键信息
=========

请提供以下信息:
 - [x] bk-cmdb   版本: 
3.10.21

**Comment by wcy00000000000000** [comment]
![image](https://user-images.githubusercontent.com/40779709/216504929-20221a75-a0cc-4f25-8237-94496c74ba94.png)
这个模糊查询的操作符支持忽略大小写

**Comment by shenxg13** [comment]
3.10.21版本的host属性我这里测试用这个模糊查询也会区分大小写，请问这部分代码是在哪里，我确认一下。

**Comment by wcy00000000000000** [comment]
集群、模块等模型等模糊查询是这个PR（#4063）里支持的，主机没有支持
