### ISSUE TITLE
登录没有反应

### ISSUE THREAD

**Issue by EdmundDXu** [TencentBlueKing/bk-cmdb#6592]
问题描述
===========

登录后无任何request发起，且没有跳转，仍然停留在登录页面，没有任何提醒，日志中没有相应报错。

重现方法
================

关键信息
=========
![image](https://user-images.githubusercontent.com/31400710/217245950-e028f89c-6272-4b42-9c63-d533ca8d7c49.png)

请提供以下信息:

 - [x] bk-cmdb   版本: 
Version     : v3.10.x
Tag         : v3.10.x
BuildTime   : 2023-02-07T18:58:13+0800
GitHash     : 703c8b49bb948c3df66d3e8cb37659b8b4d1ef00
RunMode     : product
Distribution: community
ServiceName : apiserver
GoVersion   : go1.19.2
 - [x] Redis     版本: 3.2.12
 - [x] MongoDB   版本: v4.2.23
 - [x] ZooKeeper 版本: 3.4.10
 - [x] 操作系统      : CentOS 7
 - [x] bk-cmdb 异常日志
Log file created at: 2023/02/07 20:02:08
Running on machine: cw4
Binary: Built with gc go1.19.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0207 20:02:08.236687   57329 configcenter/viper.go:397] config watch.maxIdleConns less than minimum value, use minimum value 50
E0207 20:02:08.265914   57329 backbone/notice.go:57] log watch failed, will watch after 10s, path: /cc/services/notice/log/10.100.2.246:60004/v, err: zk: node does not exist

**Comment by ZQHcode** [comment]
麻烦提供下common.yaml配置文件里的内容，以及看下webserver日志中是否有报错信息

**Comment by EdmundDXu** [comment]
> 麻烦提供下common.yaml配置文件里的内容，以及看下webserver日志中是否有报错信息

排查webserver日志后确定是连接到redis slave的原因，修改到redis master后正常。
请问--redis-ip 是否支持 redis replication或者sentinel

**Comment by breezelxp** [comment]
> 

支持sentinel
