### ISSUE TITLE
单独部署开源CMDB（v3.10.22）的API如何调用，调用一直失败

### ISSUE THREAD

**Issue by dujiaoyang** [TencentBlueKing/bk-cmdb#6597]
问题描述
===========
新增主机
API: POST /api/{version}/hosts/add
API名称： add_host_to_resource
功能说明：
中文：新增主机到资源池
English ：add host to resource
input body：
{
　　"host_info":{
　　　　"0":{
　　　　　　"bk_host_innerip":"127.0.0.1",
　　　　　　"import_from":"3",
　　　　　　"bk_cloud_id":1
　　　　}
　　},
　　"bk_supplier_id":0,
　　"bk_biz_id":3
}
https://bk.tencent.com/s-mart/community/question/10300?type=answer

重现方法
================

关键信息
=========

请提供以下信息:

 - [ ] bk-cmdb   版本: v3.10.22
 
 - [x] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by dujiaoyang** [comment]
文档已经脱节了很多了，更新下吧

**Comment by wjyfelen** [comment]
v3.10.x版本请按照 对应版本分支的 文档进行调试 ，具体路径如下: https://github.com/TencentBlueKing/bk-cmdb/tree/v3.10.x/docs/apidoc/cc/zh_hans
