### ISSUE TITLE
【3.10.23-alpha1】点击项目启用/停用 前端提示与实际不符（无法申请权限）

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6617]
一、前提条件
账号test0217未拥有任何权限
![image](https://user-images.githubusercontent.com/66291315/219542912-45b7785c-0b37-4b27-a909-1a5dc932f938.png)

二 、重现步骤：
资源-项目-启用
资源-项目-停用
![image](https://user-images.githubusercontent.com/66291315/219543321-a2c00516-c7ed-493f-a94b-306417a3154c.png)

三 、预期结果
可正常跳转到权限中心申请项目启用/停用权限

四 、实际结果
跳转到申请业务归档的权限申请界面
![image](https://user-images.githubusercontent.com/66291315/219543701-1994647e-490d-46e2-ad91-bb2a0aa14885.png)
![image](https://user-images.githubusercontent.com/66291315/219543739-559a3a81-23c5-438a-b64a-e0ce33050e9e.png)

tips:在权限中心中项目删除的权限其实无法申请使用
![image](https://user-images.githubusercontent.com/66291315/219543819-b3fbc015-240b-4177-89b4-1ed48a6544ee.png)

**Comment by ZQHcode** [comment]
这个跳转需要前端看下 @Lin-zhihan，所需要的权限是项目编辑权限
