### ISSUE TITLE
咨询请教：CMDB未来考虑用图存储作为底层存储吗？对于拓扑方向能力的底层支撑和未来拓扑探索能力方向有什么建议吗？

### ISSUE THREAD

**Issue by MichaelYgZhang** [TencentBlueKing/bk-cmdb#6625]
问题描述
===========

rt

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by xcxinng** [comment]
同问，我看国内像优维还有华为都有用图数据库做拓扑，蓝鲸如果不往这方面考虑的话感觉有点跟不上主流啊，而且像这种拓扑相关的需求例如像路径查找等，用mongo这类数据库应该很难实现吧

**Comment by bd-xiaowang** [comment]
已收到反馈

**Comment by wcy00000000000000** [comment]
我们调研过业界主流的几个图数据库，但是CMDB的拓扑场景和图数据库的应用场景并不完全匹配。CMDB中拓扑树宽度和深度均较多，且查询时多为跨多个层级的按属性筛选的查询场景。在实际测试时发现主机搜索等场景基本需要扫描全部数据，且分页时每页均需要扫描一遍全量数据，并不能起到特别好的效果，因此暂时无法使用图数据库作为CMDB的底层存储。
