### ISSUE TITLE
monstache加载插件失败

### ISSUE THREAD

**Issue by 545119811** [TencentBlueKing/bk-cmdb#6630]
问题描述
===========
编译安装monstache-plugin.so插件，运行启动失败，提示版本不对。
ERROR 2023/02/24 10:45:25 Unable to load mapper plugin etc/monstache-plugin.so: plugin.Open("etc/monstache-plugin"): plugin was built with a different version of package golang.org/x/sys/internal/unsafeheader

重现方法
================
单独编译monstache插件
![image](https://user-images.githubusercontent.com/16227653/221081205-6f738bed-c19d-4ff1-b2b3-b111cf540aa7.png)
再将编译好的 monstache-plugin.so拷贝至之前编译好的cmdb项目中，
启动就报错
![image](https://user-images.githubusercontent.com/16227653/221081885-5da0dbe2-22c1-4820-998c-6185bd05ff97.png)

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
Version     : bk-cmdb-release-v3.10.22.zip
Tag         :
BuildTime   : 2023-02-15T20:11:46+0800
GitHash     :
RunMode     : product
Distribution: community
ServiceName : monstache
 - [x] MongoDB   版本: 4.2.3
 - [x] elasticsearch   版本: 7.6.2
 - [x] monstache   版本: 6.7.11
 - [x] go   版本: 1.17
 - [x] 操作系统      : ubuntu18.0.4

**Comment by bd-xiaowang** [comment]
已反馈

**Comment by happyfanminjie** [comment]
这个问题怎么解决的，我在3.10.41版本碰到同样的问题

**Comment by 545119811** [comment]
网上有人把编译好的monstache二级制包给出来了，就直接用了。

**Comment by wbpyer** [comment]
我也遇到了这样的问题，自己编译的monstache 和plugin对不上，试了好多版本都不行

**Comment by ZQHcode** [comment]
monstache部署对用户确实很不友好，已经规划在新版本里会使用其他方式同步全文检索数据，不依赖于monstache
