### ISSUE TITLE
cmdb_coreservice 崩溃

### ISSUE THREAD

**Issue by HalfLife1** [TencentBlueKing/bk-cmdb#6640]
问题描述
===========

![image](https://user-images.githubusercontent.com/11275095/222342689-5a6de5ff-1554-4271-9a8f-30caebba50b7.png)

重现方法
================

登录webserver 后随便点击几下，coreservice就退出。

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: release-v3.9.43
 
 - [x] Redis     版本: 6.0.16
 - [x] MongoDB   版本: 6.0.4
 - [x] ZooKeeper 版本: 3.4.14
 - [x] 操作系统      : ubuntu22.04
 - [x] go: go1.18.1 
 - [x] 初始化数据

{
 "result": true,
 "bk_error_code": 0,
 "bk_error_msg": "",
 "permission": null,
 "data": "migrate success",
 "pre_version": "y3.9.202112071431",
 "current_version": "y3.9.202112071431",
 "finished_migrations": []
}

 - [x] **bk-cmdb coreservice**
 E0302 06:03:29.893490  811041 rdapi/rdfunc.go:50] server panic, err:"invalid memory address or nil pointer dereference", rid:cc0000cg03ocd65uqm63e9jqs0, debug strace:goroutine 721 [running]:
runtime/debug.Stack()
        /usr/lib/go-1.18/src/runtime/debug/stack.go:24 +0x65
configcenter/src/common/rdapi.AllGlobalFilter.func1.1()
        /home/webdep/configcenter/tmp1/src/configcenter/src/common/rdapi/rdfunc.go:50 +0x94
panic({0xf09ec0, 0x18b8040})
        /usr/lib/go-1.18/src/runtime/panic.go:838 +0x207
reflect.mapiternext(0x40?)
        /usr/lib/go-1.18/src/runtime/map.go:1378 +0x19
configcenter/vendor/github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0xc00031d488?)
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/modern-go/reflect2/unsafe_map.go:136 +0x32
configcenter/vendor/github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc0006fccf0, 0xc000010da0, 0xc000c40000)
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/json-iterator/go/reflect_map.go:293 +0x335
configcenter/vendor/github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc000ade580, 0xc0006fc720, 0xc000acc700?)
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/json-iterator/go/reflect.go:214 +0x82
configcenter/vendor/github.com/json-iterator/go.(*Stream).WriteVal(0xc000c40000, {0xef9ca0, 0xc0006fc720})
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/json-iterator/go/reflect.go:93 +0x158
configcenter/vendor/github.com/json-iterator/go.(*dynamicEncoder).Encode(0xc000740ec0?, 0x9c7787?, 0xc000c40018?)
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/json-iterator/go/reflect_dynamic.go:15 +0x39
configcenter/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000319bf0, 0xe6c7cf?, 0xc000c40000)
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
configcenter/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc000319c50, 0xc000740fe8?, 0xc000c40000)
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x652
configcenter/vendor/github.com/json-iterator/go.(*OptionalEncoder).Encode(0xeb10e0?, 0xc000010d40?, 0xc000741038?)
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/json-iterator/go/reflect_optional.go:74 +0xa4
configcenter/vendor/github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc000e96a20, 0xc000acc6c0, 0xc000741070?)
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/json-iterator/go/reflect.go:214 +0x82
configcenter/vendor/github.com/json-iterator/go.(*Stream).WriteVal(0xc000c40000, {0xf2d4c0, 0xc000acc6c0})
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/json-iterator/go/reflect.go:93 +0x158
configcenter/vendor/github.com/json-iterator/go.(*frozenConfig).Marshal(0xc0001c1040, {0xf2d4c0, 0xc000acc6c0})
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/json-iterator/go/config.go:299 +0xc9
configcenter/src/common/json.Marshal(...)
        /home/webdep/configcenter/tmp1/src/configcenter/src/common/json/json.go:33
configcenter/src/common/http/rest.(*Contexts).Response(0xc0006fc510, 0xc0006fc300?)
        /home/webdep/configcenter/tmp1/src/configcenter/src/common/http/rest/contexts.go:409 +0x3f
configcenter/src/common/http/rest.(*Contexts).RespEntity(0xc0006fc510, {0xef9ca0?, 0xc0006fc720})
        /home/webdep/configcenter/tmp1/src/configcenter/src/common/http/rest/contexts.go:75 +0x15f
configcenter/src/source_controller/coreservice/service.(*coreService).GetDefaultUserCustom(0xfc5380?, 0xc0006fc510)
        /home/webdep/configcenter/tmp1/src/configcenter/src/source_controller/coreservice/service/hostuser.go:118 +0x225
configcenter/src/common/http/rest.(*RestUtility).wrapperAction.func1(0xc0006fc420, 0xc000316620)
        /home/webdep/configcenter/tmp1/src/configcenter/src/common/http/rest/rest.go:135 +0x57c
configcenter/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc0006fc420?, 0x1254378?, 0xc0006fc4e0?)
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/emicklei/go-restful/filter.go:21 +0x58
configcenter/src/common/rdapi.AllGlobalFilter.func1(0xc0006fc420, 0xc000316620, 0xeb0de0?)
        /home/webdep/configcenter/tmp1/src/configcenter/src/common/rdapi/rdfunc.go:79 +0x20f
configcenter/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc0006fc330?, 0xeb0de0?, 0x1249d00?)
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/emicklei/go-restful/filter.go:19 +0x47
configcenter/src/common/metrics.(*Service).RestfulMiddleWare(0x18d0920?, 0xc0006fc420, 0x0?, 0xc000316620?)
        /home/webdep/configcenter/tmp1/src/configcenter/src/common/metrics/metrics.go:185 +0xd9
configcenter/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc00032e160?, 0xc000ade2d0?, 0xc0003165b0?)
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/emicklei/go-restful/filter.go:19 +0x47
configcenter/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc0007e4090, {0x1252788, 0xc0003165b0}, 0xc0000b6600)
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/emicklei/go-restful/container.go:282 +0x834
net/http.HandlerFunc.ServeHTTP(0x40c0ed?, {0x1252788?, 0xc0003165b0?}, 0x7f80081925b8?)
        /usr/lib/go-1.18/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x1252788, 0xc0003165b0}, 0xc0000b6600)
        /usr/lib/go-1.18/src/net/http/server.go:2462 +0x149
configcenter/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0x1253f48?, {0x1252788?, 0xc0003165b0?}, 0x1249d00?)
        /home/webdep/configcenter/tmp1/src/configcenter/vendor/github.com/emicklei/go-restful/container.go:300 +0x27
configcenter/src/common/metrics.(*Service).HTTPMiddleware.func1({0x1253178?, 0xc000a162a0}, 0xc0000b6300)
        /home/webdep/configcenter/tmp1/src/configcenter/src/common/metrics/metrics.go:152 +0x462
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1253178?, 0xc000a162a0?}, 0x4fa169?)
        /usr/lib/go-1.18/src/net/http/server.go:2084 +0x2f
net/http.HandlerFunc.ServeHTTP(0x7f7fdf369a48?, {0x1253178?, 0xc000a162a0?}, 0x40f245?)
        /usr/lib/go-1.18/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0x1253178, 0xc000a162a0}, 0xc0000b6300)
        /usr/lib/go-1.18/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc0006fc150?}, {0x1253178, 0xc000a162a0}, 0xc0000b6300)
        /usr/lib/go-1.18/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000ac1c20, {0x1253ff0, 0xc000d599b0})
        /usr/lib/go-1.18/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        /usr/lib/go-1.18/src/net/http/server.go:3071 +0x4db
runtime: bad pointer in frame configcenter/vendor/github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext at 0xc000ddcc00: 0x8
fatal error: invalid pointer found on stack

 - [x] mongodb集群状态
members: [
    {
      _id: 0,
      name: '172.18.25.41:27017',
      health: 1,
      state: 1,
      stateStr: 'PRIMARY',
      uptime: 48390,
      optime: { ts: Timestamp({ t: 1677737163, i: 1 }), t: Long("11") },
      optimeDate: ISODate("2023-03-02T06:06:03.000Z"),
      lastAppliedWallTime: ISODate("2023-03-02T06:06:03.189Z"),
      lastDurableWallTime: ISODate("2023-03-02T06:06:03.189Z"),
      syncSourceHost: '',
      syncSourceId: -1,
      infoMessage: '',
      electionTime: Timestamp({ t: 1677688791, i: 1 }),
      electionDate: ISODate("2023-03-01T16:39:51.000Z"),
      configVersion: 155509,
      configTerm: 11,
      self: true,
      lastHeartbeatMessage: ''
    },
    {
      _id: 1,
      name: '172.18.25.51:27017',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
      uptime: 48388,
      optime: { ts: Timestamp({ t: 1677737163, i: 1 }), t: Long("11") },
      optimeDurable: { ts: Timestamp({ t: 1677737163, i: 1 }), t: Long("11") },
      optimeDate: ISODate("2023-03-02T06:06:03.000Z"),
      optimeDurableDate: ISODate("2023-03-02T06:06:03.000Z"),
      lastAppliedWallTime: ISODate("2023-03-02T06:06:03.189Z"),
      lastDurableWallTime: ISODate("2023-03-02T06:06:03.189Z"),
      lastHeartbeat: ISODate("2023-03-02T06:06:08.625Z"),
      lastHeartbeatRecv: ISODate("2023-03-02T06:06:09.096Z"),
      pingMs: Long("0"),
      lastHeartbeatMessage: '',
      syncSourceHost: '172.18.25.41:27017',
      syncSourceId: 0,
      infoMessage: '',
      configVersion: 155509,
      configTerm: 11
    },
    {
      _id: 2,
      name: '172.18.25.40:27017',
      health: 1,
      state: 7,
      stateStr: 'ARBITER',
      uptime: 48388,
      lastHeartbeat: ISODate("2023-03-02T06:06:08.624Z"),
      lastHeartbeatRecv: ISODate("2023-03-02T06:06:08.418Z"),
      pingMs: Long("0"),
      lastHeartbeatMessage: '',
      syncSourceHost: '',
      syncSourceId: -1,
      infoMessage: '',
      configVersion: 155509,
      configTerm: 11
    }
  ],
  ok: 1,

**Comment by ZQHcode** [comment]
你好，可以看下coreservice的start.sh启动脚本里的地址配置是否是正常；是否还有其他服务是异常的，是的话提供下common.yaml配置文件中的内容，我看下

**Comment by lalala2047** [comment]
> 你好，可以看下coreservice的start.sh启动脚本里的地址配置是否是正常；是否还有其他服务是异常的，是的话提供下common.yaml配置文件中的内容，我看下

**1. 只有以下进程运行：**
 ./cmdb_adminserver--addrport=172.18.25.41:60004
./cmdb_apiserver--addrport=172.18.25.41:8080
./cmdb_cloudserver--addrport=172.18.25.41:60013
./cmdb_datacollection--addrport=172.18.25.41:60005
./cmdb_eventserver--addrport=172.18.25.41:60009
./cmdb_hostserver--addrport=172.18.25.41:60001
./cmdb_operationserver--addrport=172.18.25.41:60011
./cmdb_procserver--addrport=172.18.25.41:60003
./cmdb_webserver--addrport=172.18.25.41:9090
**2. comm.yaml ， user-passwd已脱敏处理**
#topoServer:
#  es:
#    fullTextSearch: "off"
#    url: http://127.0.0.1:9200
#    usr: cc
#    pwd: cc
#webServer:
#  api:
#    version: v3
#  session:
#    name: cc3
#    defaultlanguage: zh-cn
#    multipleOwner: 0
#    userInfo: cc:cc
#  site:
#    domainUrl: http://127.0.0.1:80/
#    bkLoginUrl: http://127.0.0.1/login/?app_id=%s&amp;c_url=%s
#    appCode: cc
#    checkUrl: http://127.0.0.1/login/accounts/get_user/?bk_token=
#    bkAccountUrl: http://127.0.0.1/login/accounts/get_all_user/?bk_token=%s
#    resourcesPath: /tmp/
#    htmlRoot: /data/cmdb/web
#    fullTextSearch: off
#  app:
#    agentAppUrl: http://127.0.0.1/console/?app=bk_agent_setup
#    authscheme: internal
#  login:
#    version: opensource
#operationServer:
#  timer:
#    spec: 00:30
#authServer:
#  address: 127.0.0.1
#  appCode: bk_cmdb
#  appSecret: 123456
#cloudServer:
#  cryptor:
#    enableCryptor: false
#    secretKeyUrl:
#    secretsAddrs:
#    secretsToken:
#    secretsProject:
#    secretsEnv:

#elasticsearch配置
es:
  #全文检索功能开关(取值：off/on)，默认是off，开启是on
  fullTextSearch: "on"
  #elasticsearch服务监听url，默认是[http://127.0.0.1:9200](http://127.0.0.1:9200/)
  url: http://172.18.25.41:9200
  #用户
  usr: es_user
  #密码
  pwd: *************
# web_server专属配置
webServer:
  api:
    #显示版本，比如v3为3.x
    version: v3
  #会话相关
  session:
    #会话名
    name: cc3
    #语言
    defaultlanguage: zh-cn
    #是否支持同时登录同一用户，0为不支持，1为支持
    multipleOwner: "0"
    #账号密码，以 : 分割
    userInfo: admin:********,root:*******
  site:
    #该值表示部署完成后,输入到浏览器中访问的cmdb 网址
    domainUrl: http://172.18.25.41:9090
    #登录地址
    bkLoginUrl: http://127.0.0.1/login/?app_id=%s&c_url=%s
    appCode: cc
    checkUrl: http://127.0.0.1/login/accounts/get_user/?bk_token=
    bkAccountUrl: http://127.0.0.1/login/accounts/get_all_user/?bk_token=%s
    resourcesPath: /tmp/
    #前端基础页面位置
    htmlRoot: ../web
    #帮助文档地址
    helpDocUrl: https://bk.tencent.com/docs/markdown/配置平台/产品白皮书/产品简介/Overview.md
  app:
    agentAppUrl: http://127.0.0.1/console/?app=bk_agent_setup
    #权限模式，web页面使用，可选值: internal, iam
    authscheme: internal
  login:
    #登录模式
    version: opensource
# operation_server专属配置
operationServer:
  timer:
    # 00:00-23:59,运营统计定时收集数据时间点,默认是为00:30
    spec: 00:30  # 00:00 - 23:59
  # 禁用运营统计数据统计功能，默认false
  disableOperationStatistic: false
#auth_server专属配置
authServer:
  #蓝鲸权限中心地址,可配置多个,用,(逗号)分割
  address:
  #cmdb项目在蓝鲸权限中心的应用编码
  appCode: bk_cmdb
  #cmdb项目在蓝鲸权限中心的应用密钥
  appSecret:
#cloudServer专属配置
cloudServer:
  # 加密服务使用
  cryptor:
    enableCryptor: false
    secretKeyUrl:
    secretsAddrs:
    secretsToken:
    secretsProject:
    secretsEnv:
  # 云同步任务
  syncTask:
    # 同步周期,最小为5分钟
    syncPeriodMinutes: 5
#datacollection专属配置
datacollection:
  hostsnap:
    # 当主机快照数据属性,如cpu,bk_cpu_mhz,bk_disk,bk_mem这些数值型数据变动的范围大于该配置的值时，进行db数据的更新，默认值为10%，最小值为5%，以百分比为单位
    changeRangePercent: 10
    # 用于设置主机快照key在redis中的过期时间，该时间会有上下50%的波动，当key存在时，同一id的主机数据不会更新，默认值为10分钟，最小值为5分钟，以分钟为单位
    changeCountExpireMinute: 10
    # 用于设置单个服务主机快照处理请求能力，起到限流的作用，令牌桶配置，最多请求数通过burst设置。qps的默认值为40，burst的默认值为100
    rateLimiter:
      qps: 40
      burst: 100
# 监控配置， monitor配置项必须存在
monitor:
    # 监控插件名称，有noop，blueking， 不填时默认为noop
    pluginName: noop
    # 是否开启监控
    enableMonitor: false
    # 当使用blueking监控插件时，上报数据所需要的数据通道标识,如1500000
    dataID: 0
    # 采集数据后能够缓存的队列长度，设置范围为1～1000, 默认为100
    queueSize: 100
    # 采集数据用的gsecmdline命令绝对路径，默认版本需要大于等于2.0.2 ，默认路径：/usr/local/gse/plugins/bin/gsecmdline
    gsecmdlinePath:
    # 对应的domainsocket绝对路径，默认路径：/usr/local/gse/agent/data/ipc.state.report
    domainSocketPath:
    # 用于对数据上报进行频率控制和限流
    # qps的设置范围为1～50，默认值为10
    # burst的设置范围为1～100，默认值为20
    rateLimiter:
      qps: 10
      burst: 20

**Comment by HalfLife1** [comment]
使用go 1.17.13 重新编译后，解决该问题。
