### ISSUE TITLE
【3.10.23-alpha4 】动态分组引用数据较多时无法查看到完整的引用结果

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6659]
一、前提条件

当枚举引用字段引用较多数据时，前端显示+4 hover时可查看到完整的数据，如下图

![image](https://user-images.githubusercontent.com/66291315/223385177-203243e9-c91f-48d6-a6e0-4bf5a7df3a8b.png)

二 、重现步骤
动态分组-新建-使用枚举引用字段引用数据

三 、预期结果
在动态分组中当枚举引用字段引用较多数据时，前端显示正常 hover时可查看到完整的数据

四 、实际结果
在动态分组中当枚举引用字段引用较多数据时，前端显示异常，长方框未显示完整 hover时可查看到完整的数据
![image](https://user-images.githubusercontent.com/66291315/223386821-afefcafc-f888-45a9-a528-6abca1603c69.png)

再次选择引用数据时，引用数据框显示异常，如下图
![image](https://user-images.githubusercontent.com/66291315/223387065-8b0aede3-cd3e-4d2c-aa46-50b73cdeb40f.png)

**Comment by reggieisrunning** [comment]
@Lin-zhihan
