### ISSUE TITLE
使用mongodb 分片集群6.0版本 是否支持分布式事务

### ISSUE THREAD

**Issue by mini-tiger** [TencentBlueKing/bk-cmdb#6661]
问题描述
===========
是否支持 分片集群，现在的mongodb  transaction是否可以支持 分片集群中的分布式事务

问题详情
================

- 修改过storage/dal/mongo/local/mongo.go 中的NewMgo方法 以便能支持分片集群
- 在做 修改模型数据时的事务操作会报错与 mongodb [官方链接](https://www.mongodb.com/docs/manual/core/transactions-sharded-clusters/) 中提到的情况一致

- 是否可以更新 mongodb 的驱动包 以适配

**Comment by bd-xiaowang** [comment]
已反馈

**Comment by ZQHcode** [comment]
暂不支持哈
