### ISSUE TITLE
调用任何接口都是"bk_error_code":1199037 

### ISSUE THREAD

**Issue by HalfLife1** [TencentBlueKing/bk-cmdb#6663]
问题描述
===========

![image](https://user-images.githubusercontent.com/11275095/223628573-5a1ec58e-76bc-4114-a195-20a149c9047a.png)

重现方法
================

POST /api/{version}/objects

![image](https://user-images.githubusercontent.com/11275095/223628585-01445fae-50fa-40df-b525-7eb2dcc58e96.png)

关键信息
=========

 **api日志：**
I0308 05:37:56.181618 2409668 rdapi/rdfunc.go:88] code: , user: admin, rip: , uri: /api/v3/objects, body: {
    "bk_obj_id": "domain_url",
    "bk_supplier_account":"0"

}, rid: cc0000cg41ud565uqs9h6mgrog
E0308 05:37:56.181637 2409668 service/filter.go:57] rewrite request url[/api/v3/objects] failed, err: unknown requested with backend process, rid: cc0000cg41ud565uqs9h6mgrog

请提供以下信息:

 bk-cmdb 版本: release-v3.9.43

 Redis 版本: 6.0.16

 MongoDB 版本: 6.0.4

 ZooKeeper 版本: 3.4.14

 操作系统 : ubuntu22.04

 go: go1.17.3

**Comment by ZQHcode** [comment]
你好，代码里是没有这个接口的哈，这边是想调用接口查询什么数据呢
