### ISSUE TITLE
cmdb_apiserver启动失败,如何排查

### ISSUE THREAD

**Issue by yama0509** [TencentBlueKing/bk-cmdb#6675]
问题描述
===========
执行/opt/cmdb/start.sh脚本，显示Not Running: cmdb_apiserver

重现方法
================
[root@localhost cmdb]# /opt/cmdb/start.sh
starting: cmdb_adminserver
starting: cmdb_apiserver
starting: cmdb_auditcontroller
starting: cmdb_datacollection
starting: cmdb_eventserver
starting: cmdb_hostcontroller
starting: cmdb_hostserver
starting: cmdb_objectcontroller
starting: cmdb_proccontroller
starting: cmdb_procserver
starting: cmdb_toposerver
starting: cmdb_webserver
root      13405      1  0 20:08 ?        00:00:07 ./cmdb_adminserver --addrport=192.168.255.132:60004 --logtostderr=false --log-dir=./logs --v=3 --config=configures/migrate.conf
root      13446      1  0 20:08 ?        00:00:20 ./cmdb_auditcontroller --addrport=192.168.255.132:50005 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root      13466      1  0 20:08 ?        00:00:22 ./cmdb_datacollection --addrport=192.168.255.132:60005 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root      13487      1  0 20:08 ?        00:00:21 ./cmdb_eventserver --addrport=192.168.255.132:60009 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root      13506      1  0 20:08 ?        00:00:20 ./cmdb_hostcontroller --addrport=192.168.255.132:50002 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root      13526      1  0 20:08 ?        00:00:19 ./cmdb_hostserver --addrport=192.168.255.132:60001 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root      13548      1  0 20:08 ?        00:00:21 ./cmdb_objectcontroller --addrport=192.168.255.132:50001 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root      13568      1  0 20:08 ?        00:00:20 ./cmdb_proccontroller --addrport=192.168.255.132:50003 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root      13589      1  0 20:08 ?        00:00:19 ./cmdb_procserver --addrport=192.168.255.132:60003 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root      13610      1  0 20:08 ?        00:00:19 ./cmdb_toposerver --addrport=192.168.255.132:60002 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root      13630      1  0 20:08 ?        00:00:03 ./cmdb_webserver --addrport=192.168.255.132:8083 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
process count should be: 12 , now: 11
Not Running: cmdb_apiserver

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本:  网上下载的包，不清楚版本
 -->
 - [ ] Redis     版本:  3.2.11
 - [ ] MongoDB   版本:  2.8.0
 - [ ] ZooKeeper 版本: 3.8.1
 - [ ] 操作系统      : centos7 X64
 - [ ] bk-cmdb 异常日志
 -

**Comment by yama0509** [comment]
MongoDB 版本已更换成4.2.8，任然没有解决问题

**Comment by ZQHcode** [comment]
可以根据apiserver的log文件夹下面的错误日志，根据日志内容判断没有正常启动的原因哈
