### ISSUE TITLE
release-v3.10.18 编译问题

### ISSUE THREAD

**Issue by yama0509** [TencentBlueKing/bk-cmdb#6677]
问题描述
===========
在/configcenter/src下执行make后，出现报错

重现方法
================
[root@localhost ~]# cd configcenter/src/
[root@localhost src]# make

building server...
: 无效选项: 第 2 行:set: -
set: 用法:set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
: 没有那个文件或目录cd: ../src
./build.sh:行6: 未预期的符号 `$'do\r'' 附近有语法错误
'/build.sh:行6: `    for tmp in $DIRS;do
make: *** [default] 错误 2

关键信息
=========

 - [x] bk-cmdb   版本:  release-v3.10.18 
 -->
 - [ ] Redis     版本: 3.2.11
 - [ ] MongoDB   版本: 4.2.8
 - [ ] ZooKeeper 版本: 3.8.1
 - [ ] 操作系统      :  Centos 7
 - [ ] bk-cmdb

**Comment by chestarss** [comment]
编译 cmdb_datacollection报错
```
building the target: cmdb_datacollection... 

go build -ldflags "-X configcenter/src/common/version.CCVersion=v3.10.18 -X configcenter/src/common/version.CCBuildTime=2023-03-22T09:10:27+0000 -X configcenter/src/common/version.CCGitHash=857950d6d65dc0e67f17c37215dcd21d660de0ef -X configcenter/src/common/version.CCTag=release-v3.10.18 -X configcenter/src/common/version.CCDistro=community" -o /data/src/configcenter/src/bin/build/v3.10.18/cmdb_datacollection/cmdb_datacollection
# configcenter/vendor/github.com/Shopify/sarama
../../../vendor/github.com/Shopify/sarama/config.go:672:37: undefined: io.Discard
../../../vendor/github.com/Shopify/sarama/decompress.go:43:10: undefined: io.ReadAll
../../../vendor/github.com/Shopify/sarama/decompress.go:55:10: undefined: io.ReadAll
../../../vendor/github.com/Shopify/sarama/sarama.go:89:29: undefined: io.Discard
make[1]: Leaving directory '/data/src/configcenter/src/scene_server/datacollection'
make[1]: *** [/data//src/configcenter/scripts/Makefile:57: cmdb_datacollection] Error 2
make: *** [Makefile:32: server] Error 2
The command '/bin/sh -c cd /data/src/ && ls -al ./ && mv bk-cmdb configcenter && cd /data/src/configcenter/src/ && export GOPATH=/data/ && make server' returned a non-zero code: 2
```

**Comment by bd-xiaowang** [comment]
> 编译 cmdb_datacollection报错
> 
> ```
> building the target: cmdb_datacollection... 
> 
> go build -ldflags "-X configcenter/src/common/version.CCVersion=v3.10.18 -X configcenter/src/common/version.CCBuildTime=2023-03-22T09:10:27+0000 -X configcenter/src/common/version.CCGitHash=857950d6d65dc0e67f17c37215dcd21d660de0ef -X configcenter/src/common/version.CCTag=release-v3.10.18 -X configcenter/src/common/version.CCDistro=community" -o /data/src/configcenter/src/bin/build/v3.10.18/cmdb_datacollection/cmdb_datacollection
> # configcenter/vendor/github.com/Shopify/sarama
> ../../../vendor/github.com/Shopify/sarama/config.go:672:37: undefined: io.Discard
> ../../../vendor/github.com/Shopify/sarama/decompress.go:43:10: undefined: io.ReadAll
> ../../../vendor/github.com/Shopify/sarama/decompress.go:55:10: undefined: io.ReadAll
> ../../../vendor/github.com/Shopify/sarama/sarama.go:89:29: undefined: io.Discard
> make[1]: Leaving directory '/data/src/configcenter/src/scene_server/datacollection'
> make[1]: *** [/data//src/configcenter/scripts/Makefile:57: cmdb_datacollection] Error 2
> make: *** [Makefile:32: server] Error 2
> The command '/bin/sh -c cd /data/src/ && ls -al ./ && mv bk-cmdb configcenter && cd /data/src/configcenter/src/ && export GOPATH=/data/ && make server' returned a non-zero code: 2
> ```

看着像是go版本或者依赖包版本的问题，请确认你选择的go版本>=1.17，然后再拉取最新的代码进行编译，目前最新版本在3.11.x分支，参照最新的编译部署文档重新进行编译：https://github.com/TencentBlueKing/bk-cmdb/tree/v3.11.x/docs/overview
