### ISSUE TITLE
v3.10.x编译成功，启动cmdb_authserver失败。报错 err: no iam address

### ISSUE THREAD

**Issue by qiqiaobin** [TencentBlueKing/bk-cmdb#6681]
问题描述
===========
v3.10.x编译成功，启动cmdb_authserver失败。报错 err: no iam address
begin to discover by watch children of path(/cc/services/endpoints/cloud)
begin to discover by watch children of path(/cc/services/endpoints/topo)
begin to discover by watch children of path(/cc/services/endpoints/task)
begin to discover by watch children of path(/cc/services/endpoints/proc)
begin to discover by watch children of path(/cc/services/endpoints/eventserver)
begin to discover by watch children of path(/cc/services/endpoints/host)
begin to discover by watch children of path(/cc/services/endpoints/operation)
begin to discover by watch children of path(/cc/services/endpoints/migrate)
begin to discover by watch children of path(/cc/services/endpoints/coreservice)
begin to discover by watch children of path(/cc/services/endpoints/apiserver)
begin to discover by watch children of path(/cc/services/endpoints/datacollection)
begin to discover by watch children of path(/cc/services/endpoints/cacheservice)
begin to discover by watch children of path(/cc/services/endpoints/auth)
children node(/cc/services/endpoints/topo) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/topo), err:zk: node does not exist
children node(/cc/services/endpoints/topo) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/auth), err:zk: node does not exist
children node(/cc/services/endpoints/auth) is not exist, will watch after 5s
children node(/cc/services/endpoints/auth) is not exist, will watch after 5s
E0316 10:28:36.148043   46517 app/server.go:77] new iam client, err: no iam address
no iam address
E0316 10:28:36.148252   46517 auth_server/auth.go:50] process stopped by no iam address

重现方法
================
./restart.sh

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本:  v3.10.18
 - [x] Redis     版本: 5.0.9
 - [x] MongoDB   版本: 4.2.24
 - [x] ZooKeeper 版本: 3.7.1
 - [x] 操作系统      : Centos 7.9
初始化权限模式的时候没有配置使用IAM，希望能更新一下，开源版本CMDB的独立部署文档。
相关配置如下：
    #权限模式，web页面使用，可选值: internal, iam
    authscheme: internal
  login:
    #登录模式
    version: opensource

**Comment by ZQHcode** [comment]
authserver这个服务可以不启动，不影响功能的使用，它需要依赖于权限中心（另一个平台），报错里的为权限中心的配置地址；如果想实现鉴权的逻辑，需要部署权限中心、用户管理等
