### ISSUE TITLE
【3.10.x-feature-agent-id-alpha12 】高级筛选悬浮检索项无对应的tooltips

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6688]
一、前提条件

以前版本鼠标悬浮时正常显示tooltips
![image](https://user-images.githubusercontent.com/66291315/225800686-d67be4e5-a7f6-4bd2-860b-c888d57181ab.png)

二 、重现步骤
高级筛选框中输入多个IP进行搜索，搜索后鼠标悬浮检索项

三 、预期结果
鼠标悬浮检索项tooltips正确显示对应的IP

四 、实际结果
鼠标悬浮检索项无反应，未有对应的tooltips，即显示搜索的IP
![image](https://user-images.githubusercontent.com/66291315/225800854-b470c742-97c9-41b3-8536-a26377921996.png)

**Comment by wjyfelen** [comment]
@yangyy 需要确认下 这个问题是否已经在最新版本修复
