### ISSUE TITLE
【3.10.x-feature-agent-id-alpha12 】业务内高级筛选框存在搜索结果与实际不符的情况

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6689]
一、前提条件

二 、重现步骤

业务-业务拓扑-高级筛选-IP搜索框中输入部分的IPv6地址进行查询（即使用模糊查询，勾选内网IP和外网IP）
![image](https://user-images.githubusercontent.com/66291315/225803073-92e465eb-3d2a-4b61-9b3e-06ab0c6a59e5.png)

三 、预期结果

前端正确展示对应命中的主机

四 、实际结果
前端展示的主机与实际结果不符，默认展示全部主机（tips:如果使用内网IPv4地址进行模糊查询也有此情况，即影响了原先高级筛选框中IP搜索功能）

![image](https://user-images.githubusercontent.com/66291315/225803370-20726524-651f-4473-9f19-056bb71d45ed.png)

**Comment by wjyfelen** [comment]
@reggieisrunning 由于ipv6不支持模糊搜索这里需要看下是否需要给出提示

**Comment by sobbingchild** [comment]
已增加提示文案“ipv6暂不支持模糊搜索”
但是使用IPv4地址模糊查询，默认展示所有主机

**Comment by reggieisrunning** [comment]
此问题在TAPD#1010080961110853019继续跟进
