### ISSUE TITLE
【3.10.x-feature-agent-id-alpha12 】自动发现信息中无法识别外网MAC

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6690]
一、前提条件
该主机已安装且启动了bkmonitorbeat插件
![image](https://user-images.githubusercontent.com/66291315/225805452-0aa4cc7a-9849-4a9e-942d-fd5b35982123.png)

二 、重现步骤

进入对应的业务下查看该主机

三 、预期结果

该主机中的自动发现信息中内网MAC地址及外网MAC正常显示

四 、实际结果

该主机中的自动发现信息中内网MAC地址正常显示，外网MAC显示为空

![image](https://user-images.githubusercontent.com/66291315/225805638-868a8771-17e1-4e50-96cf-075dbdceeb72.png)

**Comment by ZQHcode** [comment]
ipv6单栈场景，外网mac是根据外网ipv6地址的找的，这个机器没有外网ipv6地址，所以外网mac为空

**Comment by reggieisrunning** [comment]
> ipv6单栈场景，外网mac是根据外网ipv6地址的找的，这个机器没有外网ipv6地址，所以外网mac为空

认同开发看法，@sobbingchild确认一下
