### ISSUE TITLE
api添加主机报错："bk_error_msg":"反序列化JSON数据失败"

### ISSUE THREAD

**Issue by zhucaipeng** [TencentBlueKing/bk-cmdb#6698]
报错现象：
![image](https://user-images.githubusercontent.com/18751306/226532105-e37149f2-18be-41fa-b733-c179ac782759.png)

**通过ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest镜像起的容器。**

**Comment by bd-xiaowang** [comment]
请提供相应的报错日志

**Comment by bd-xiaowang** [comment]
请提供CMDB版本、问复现流程、错误日志等相关信息

**Comment by bd-xiaowang** [comment]
![主机添加序列化失败](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/61a3d0f1-f5eb-4ae8-84b9-26936edba585)
CMDB版本v3.11.x，本地测试 api/v3/hosts/add 接口未出现您的问题。
1、检查json格式、数据格式是否正确
2、请尝试使用最新版 v3.11.x 版本的CMDB，如问题依旧存在，请提供CMDB版本以及相应的报错日志
