### ISSUE TITLE
【3.10.23-feature-auth-alpha1 】普通用户拥有实例新建的权限后新建实例异常

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6762]
一、前提条件

普通用户拥有实例新建的权限
![image](https://user-images.githubusercontent.com/66291315/229679770-ebf3c0fa-e022-4af9-9196-4c3c22394533.png)

二 、重现步骤

选择模型测试0213-新建-新建实例-填写实例信息

三 、预期结果
可正常新建实例且填写实例信息

四 、实际结果
点击新建后，前端提示需要申请模型查看及实例查看权限，如下图
![image](https://user-images.githubusercontent.com/66291315/229680685-c6cca431-1308-421e-b036-6adc2e76a1fc.png)

无法正常保存该实例信息，前端提示未知或未能识别的异常
![image](https://user-images.githubusercontent.com/66291315/229680752-fd908f74-a500-438b-8549-15d537d8062e.png)

**Comment by bd-xiaowang** [comment]
新版本已无该问题，版本3.13.9
