### ISSUE TITLE
【3.10.23-feature-auth-alpha1 】无法编辑枚举多选字段（模块）

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6766]
一、前提条件

二 、重现步骤
选择节点模块编辑业务下模块的字段枚举多选
![image](https://user-images.githubusercontent.com/66291315/230331503-aa6242d6-74ea-4895-b1d3-38181f4510fc.png)

三 、预期结果
编辑枚举多选字段成功，保存成功

四 、实际结果
保存失败，前端提示禁止修改字段: pretend_table_field
![image](https://user-images.githubusercontent.com/66291315/230331276-b488beb6-9041-450d-9ec8-97509770ab3b.png)

**Comment by bd-xiaowang** [comment]
新版本已无该问题，版本3.13.9
