### ISSUE TITLE
【3.10.24-alpha1 】导入模型字段，前端提示'option' 参数无效或不存在

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6771]
一、前提条件

二 、重现步骤
选择模型-导出该模型字段-如下图
![image](https://user-images.githubusercontent.com/66291315/230585994-d364054a-f51b-410c-947a-1a151ff3ef9e.png)
导出后编辑该xlsx文件，修改字段名前面添加11
![image](https://user-images.githubusercontent.com/66291315/230586149-b08e3fd1-1791-49ee-bed7-94e244770454.png)

三 、预期结果

可成功导入该xlsx文件

四 、实际结果

无法导入该xlsx文件，前端提示未全部成功
'option' 参数无效或不存在
![image](https://user-images.githubusercontent.com/66291315/230586605-bc8ea09c-9cae-4cf7-b049-fc8768bcad21.png)

**Comment by sobbingchild** [comment]
修改内置模型字段，如下图修改自定义模型测试0411的自定义字段（先导出xlsx文件再进行修改）
![image](https://user-images.githubusercontent.com/66291315/231201260-5cd82cc1-d6ee-4c4c-9cd0-1263975c1395.png)

导入后前端提示未全部成功，第14行：字段 bk_biz_status，当前字段类型状态为单选，请设置合理数据（tips：其它内置模型亦是如此，自定义模型可正常修改）
![image](https://user-images.githubusercontent.com/66291315/231201412-8b7e19ce-ede6-4506-b34c-a052136ef070.png)

**Comment by reggieisrunning** [comment]
@wcy00000000000000 导入的excel中，某字段因为「默认值为空的历史遗留原因未设置默认值」时，允许通过校验。无论内置模型还是自定义模型，不进行刷默认值的操作

**Comment by reggieisrunning** [comment]
> 修改内置模型字段，如下图修改自定义模型测试0411的自定义字段（先导出xlsx文件再进行修改） ![image](https://user-images.githubusercontent.com/66291315/231201260-5cd82cc1-d6ee-4c4c-9cd0-1263975c1395.png)
> 
> 导入后前端提示未全部成功，第14行：字段 bk_biz_status，当前字段类型状态为单选，请设置合理数据（tips：其它内置模型亦是如此，自定义模型可正常修改） ![image](https://user-images.githubusercontent.com/66291315/231201412-8b7e19ce-ede6-4506-b34c-a052136ef070.png)

新版本中，枚举必须要有默认值，所以此处的阻断是合理的，但是提示确实可以再优化一下，告诉用户需要补充默认值的设置
