### ISSUE TITLE
【3.10.24-alpha1 】导出模型的excel中，属性字段的默认值并未被导出

### ISSUE THREAD

**Issue by reggieisrunning** [TencentBlueKing/bk-cmdb#6775]
选择任意模型进行导出到excel，其中的属性字段设置的默认值没有被导出。用户可能在修改完导出的excel后，未注意到默认值，此时再进行导入，导致属性字段的默认值被覆盖置空。

**Comment by sobbingchild** [comment]
当默认值可以被导出时存在两种异常情况：
case1:
当导入的xlsx文件中数字或者浮点超过取值范围，如下图
![image](https://user-images.githubusercontent.com/66291315/231195393-c4204cae-9058-4824-8c8a-b33958bd4662.png)
前端提示未全部成功第8行：字段 test4，未知或未能识别的异常，未具体提示信息，如果直接编辑浮点或数字时前端提示最大值不可超过xxx
![image](https://user-images.githubusercontent.com/66291315/231195561-31b94407-604f-4626-90c4-4e5587ccc281.png)
![image](https://user-images.githubusercontent.com/66291315/231196200-436966cc-3ce2-4d63-a5ef-d59758dd5e2f.png)

case2:
当导入的xlsx文件中编辑了时间或者日期时，如下图
![image](https://user-images.githubusercontent.com/66291315/231197459-f340b8de-5b6d-41d9-9c13-47302e37ab69.png)
前端提示未全部成功，提示第13行：字段 test9，未知或未能识别的异常
![image](https://user-images.githubusercontent.com/66291315/231197885-0aacca1e-2c39-47d0-91e3-9cfb7e67cf7c.png)

**Comment by reggieisrunning** [comment]
> 当默认值可以被导出时存在两种异常情况： case1: 当导入的xlsx文件中编辑了数字或者浮点的默认值并且超过取值范围，如下图 ![image](https://user-images.githubusercontent.com/66291315/231195393-c4204cae-9058-4824-8c8a-b33958bd4662.png) 前端提示未全部成功第8行：字段 test4，未知或未能识别的异常，未具体提示信息，如果直接编辑浮点或数字时前端提示最大值不可超过xxx ![image](https://user-images.githubusercontent.com/66291315/231195561-31b94407-604f-4626-90c4-4e5587ccc281.png) ![image](https://user-images.githubusercontent.com/66291315/231196200-436966cc-3ce2-4d63-a5ef-d59758dd5e2f.png)
> 
> case2: 当导入的xlsx文件中编辑了时间或者日期的默认值时，如下图 ![image](https://user-images.githubusercontent.com/66291315/231197459-f340b8de-5b6d-41d9-9c13-47302e37ab69.png) 前端提示未全部成功，提示第13行：字段 test9，未知或未能识别的异常 ![image](https://user-images.githubusercontent.com/66291315/231197885-0aacca1e-2c39-47d0-91e3-9cfb7e67cf7c.png)

这两个case非阻断性问题，后续进行优化

**Comment by testqwerts** [comment]
1.现在枚举，枚举多选。表格字段的默认值没有导出
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/5f287aa6-4bda-4725-be0a-86a228fb1d09)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/74fd1d42-0a84-4055-acf1-ec5a572fcc14)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/8364e218-68f1-4880-b1bd-0277817ef490)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/5e539d61-d8d5-4dde-b950-f011d714deee)
2.修改“数字”，“浮点”字段的默认值超出设置的范围，导入更新时报错目前还没有优化
![企业微信截图_16980269932220](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/766d195c-d161-468a-b19b-f10dfd2524a6)
3.日期/时间/用户/时区/列表这四个字段没做任何变动导入时报错
![企业微信截图_16980272414233](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/0e57f995-0c0c-4992-85e3-f99c3984c975)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/216f64e2-9601-4b70-a04d-69ec7658c3ae)
