### ISSUE TITLE
能添加模型继承功能吗？

### ISSUE THREAD

**Issue by skyox** [TencentBlueKing/bk-cmdb#6776]
能添加模型继承功能吗？

**Comment by reggieisrunning** [comment]
> 能添加模型继承功能吗？

hi，@skyox
你希望“模型继承功能”可以解决你的什么问题呢？

**Comment by skyox** [comment]
> > 能添加模型继承功能吗？
> 
> hi，@skyox 你希望“模型继承功能”可以解决你的什么问题呢？

比如物理服务器、网络设备、存储都有相同的属性：机柜位置、U数、状态、机房位置，我想可以设计一个独立的通用设备模型，物理服务器、网络设备、存储继承该模型即可继承通用的字段。

**Comment by reggieisrunning** [comment]
> > > 能添加模型继承功能吗？
> > 
> > 
> > hi，@skyox 你希望“模型继承功能”可以解决你的什么问题呢？
> 
> 比如物理服务器、网络设备、存储都有相同的属性：机柜位置、U数、状态、机房位置，我想可以设计一个独立的通用设备模型，物理服务器、网络设备、存储继承该模型即可继承通用的字段。

新版本中的“字段组合模板”功能可以完成多个模型之间相同字段的管理。可以通过https://bk.tencent.com/docs/markdown/ZH/CMDB/3.11/UserGuide/Feature/FieldGroupingTemplate.md这篇文章了解一下
