### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by gxlxiao** [TencentBlueKing/bk-cmdb#6777]
go build -ldflags "-X configcenter/src/common/version.CCVersion=master -X configcenter/src/common/version.CCBuildTime=2023-04-10T19:56:11-0700 -X configcenter/src/common/version.CCGitHash=bbe2945409dad0284d0f071add9cfc77eb1ae117 -X configcenter/src/common/version.CCTag=master -X configcenter/src/common/version.CCDistro=community" -o /opt/work/src/configcenter/src/bin/build/master/tool_ctl/tool_ctl
make[1]: Leaving directory `/opt/work/src/configcenter/src/tools/cmdb_ctl'
enter directory:  /opt/work/src/configcenter/src/tools/monstache
make[1]: Entering directory `/opt/work/src/configcenter/src/tools/monstache'
go build -buildmode=plugin -o /opt/work/src/configcenter/src/bin/build/master/monstache/etc/monstache-plugin.so *.go
# configcenter/src/tools/monstache/vendor/go.mongodb.org/mongo-driver/vendor/github.com/klauspost/compress/zstd/internal/xxhash
asm: xxhash_amd64.s:120: when dynamic linking, R15 is clobbered by a global variable access and is used here: 00092 (/opt/work/src/configcenter/src/tools/monstache/vendor/go.mongodb.org/mongo-driver/vendor/github.com/klauspost/compress/zstd/internal/xxhash/xxhash_amd64.s:120)	ADDQ	R15, AX
asm: assembly failed
make[1]: *** [default] Error 1
make[1]: Leaving directory `/opt/work/src/configcenter/src/tools/monstache'
make: *** [default] Error 2

**Comment by gxlxiao** [comment]
单独编译这个也是报错的










在 2023-04-11 14:40:08，"扬扬扬扬扬" ***@***.***> 写道：

monstache 编译请参考这个文档：https://github.com/TencentBlueKing/bk-cmdb/blob/master/src/tools/monstache/README.md

**Comment by wjyfelen** [comment]
需要用go1.13.5进行编译
