### ISSUE TITLE
【3.10.24-alpha1 】内置模型未国际化

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6778]
一、前提条件

中英文切换中已切换语言为英文

二 、重现步骤

查看内置模型是否国际化

三 、实际结果

内置模型分组名及其分组下的模型名未国际化，包括主机管理、业务拓扑、组织架构、网络、未分类
![image](https://user-images.githubusercontent.com/66291315/231076468-a1a99a22-e747-4e14-b21c-3d8a0bc7c431.png)
![image](https://user-images.githubusercontent.com/66291315/231076534-999549ce-148a-4317-b844-66aaf408d45c.png)

**Comment by laodiu** [comment]
后端已修复
