### ISSUE TITLE
【3.10.24-alpha1 】内置模型字段及自定义模型字段实例名未国际化

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6779]
一、前提条件

中英文切换中已切换语言为英文

二 、重现步骤

查看内置模型字段是否国际化

三 、实际结果

内置模型字段未国际化，如主机模型字段（tips:其它内置模型如模块、集群、业务等也未实现国际化）
![image](https://user-images.githubusercontent.com/66291315/231086994-1e632da6-0829-4744-9576-952e771ab8cc.png)

自定义模型中字段实例名未国际化
![image](https://user-images.githubusercontent.com/66291315/231085845-712321e4-7a7a-46a4-a7cd-e666469f2d2c.png)

**Comment by penggehero** [comment]
自定义模型中字段实例名未国际化是因为创建时是中文

**Comment by laodiu** [comment]
此处国际化在前端做，最新版本已经做了国际化处理， 需要更新前端的配置文件i18n/lang/en.json
