### ISSUE TITLE
【3.10.24-alpha1 】平台管理-业务空闲机池提示语未国际化

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6782]
一、前提条件

中英文切换中已切换语言为英文

二 、重现步骤

修改空闲机池下各模块的名称，查看提示语是否国际化

三 、实际结果

提示语未国际化，如下图

![image](https://user-images.githubusercontent.com/66291315/231098584-7424268d-f8b6-4657-87d4-88646e2bc3be.png)

**Comment by reggieisrunning** [comment]
此问题已修复，@sobbingchild 复核一下
