### ISSUE TITLE
【3.10.24-alpha1 】服务分类 内置服务分类名称未国际化

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6783]
一、前提条件

中英文切换中已切换语言为英文

二 、重现步骤

查看内置服务分类是否国际化

三 、实际结果
内置服务分类一级服务分类名称未国际化，如下图
![image](https://user-images.githubusercontent.com/66291315/231107305-038d0f0a-6179-412c-8f0d-01b7a339eb5d.png)

**Comment by laodiu** [comment]
国际化已做，更新对应配置文件

**Comment by reggieisrunning** [comment]
此问题已修复，@sobbingchild 复核一下
