### ISSUE TITLE
【3.10.24-alpha1 】列表显示属性配置未国际化（含资源及业务）

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6784]
一、前提条件

中英文切换中已切换语言为英文

二 、重现步骤

分别点击业务内及资源主机下的列表显示属性配置查看是否国际化

三 、实际结果

业务内及资源主机下的列表显示属性配置（内置字段）未国际化，如下图

业务下
![image](https://user-images.githubusercontent.com/66291315/231113351-2437a3c8-f203-4814-841b-4d7f836a5153.png)

资源主机下
![image](https://user-images.githubusercontent.com/66291315/231113748-e4cfdfff-2542-4b38-846a-cd4908b4ee94.png)

因为内置模型其对应字段均未国际化，所以内置模型中其对应的列表属性配置也均未国际化，如交换机、业务、防火墙等
![image](https://user-images.githubusercontent.com/66291315/231932715-4e9ee621-509d-4b8c-8f25-0ddac4a4469e.png)

![image](https://user-images.githubusercontent.com/66291315/231932855-edbbdf51-c6ac-44e1-8214-946c068d7725.png)

**Comment by laodiu** [comment]
国际化已做，更新环境中的配置文件

**Comment by reggieisrunning** [comment]
此问题已修复，@sobbingchild 复核一下
