### ISSUE TITLE
【3.10.24-alpha1 】服务模板未国际化完全

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6792]
一、前提条件

中英文切换中已切换语言为英文

二 、重现步骤

查看服务模板基础信息、监听信息、进程管理信息是否国际化

三 、实际结果

服务模板基础信息、监听信息、进程管理信息未国际化
![image](https://user-images.githubusercontent.com/66291315/231366792-20687414-8df1-4280-8cc5-566f4ca6f768.png)

包括Basic information中的服务分类
![image](https://user-images.githubusercontent.com/66291315/231368132-f1f942f9-5549-46bd-9b4d-3f86f2829cdc.png)
当点击 configure now 时正确显示服务分类名称Service Category
![image](https://user-images.githubusercontent.com/66291315/231368351-8a11700b-0f1d-49a0-bf2f-c8c29e9af991.png)

包括鼠标悬浮时其提示语
![image](https://user-images.githubusercontent.com/66291315/231384458-8dc0ce12-d520-4d95-8c08-6c465989405b.png)

**Comment by reggieisrunning** [comment]
服务分类未修复
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/82890468/b78681a6-216d-4f5e-9609-adc7c5d9fbd7)
