### ISSUE TITLE
【3.10.24-alpha1 】集群模板未国际化完全

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6793]
一、前提条件

中英文切换中已切换语言为英文

二 、重现步骤

查看集群模板是否国际化

三 、实际结果

集群模板未国际化完全如下图
![image](https://user-images.githubusercontent.com/66291315/231370299-fb3b290c-0b54-4a3d-b088-f78ca6db0b0b.png)
Add service template时全选为中文
![image](https://user-images.githubusercontent.com/66291315/231387531-57deea48-6daf-4068-abb3-8b9a72733a2d.png)

**Comment by laodiu** [comment]
@reggieisrunning 这种按钮类型，应该是前端做好国际化，后端不用处理吧？
