### ISSUE TITLE
【3.10.24-alpha1 】主机自动应用未国际化完全

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6796]
一、前提条件

中英文切换中已切换语言为英文

二 、重现步骤

如下图docker client版本 docker server版本未国际化（tips:包括By business topology及By service Template）
![image](https://user-images.githubusercontent.com/66291315/231398139-4deb615e-a180-4de9-8f88-7e757e533362.png)

![image](https://user-images.githubusercontent.com/66291315/231398278-f10aa342-c738-4431-886b-f40e503aef6c.png)

**Comment by laodiu** [comment]
cmdb最新版本已经无该字段了，无需处理

**Comment by sobbingchild** [comment]
确认最新版本已经无该字段了
