### ISSUE TITLE
【3.10.24-alpha1 】动态分组国际化未完全

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6797]
一、前提条件

中英文切换中已切换语言为英文

二 、重现步骤

如下图Keep adding时docker client版本 docker server版本
![image](https://user-images.githubusercontent.com/66291315/231402881-f823e096-0482-4376-8b66-8d00ab7a331b.png)

**Comment by laodiu** [comment]
cmdb最新版本没有图中两个字段了，无需处理

**Comment by sobbingchild** [comment]
已确认最新版本没有图中两个字段了，无需处理
