### ISSUE TITLE
【3.10.24-alpha1 】业务内自定义字段未国际化完全

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6798]
一、前提条件

中英文切换中已切换语言为英文

二 、重现步骤

如下图，New field时(新建用户字段)
![image](https://user-images.githubusercontent.com/66291315/231407009-41059e4f-693d-4372-b79c-ea82836b5ec8.png)

Host字段
![image](https://user-images.githubusercontent.com/66291315/231408539-28e2973b-1979-4214-bcf0-e9971ff56ac7.png)

**Comment by laodiu** [comment]
done, 上面提示需要前端处理下

**Comment by reggieisrunning** [comment]
新字段编辑后不保存，直接cancel，二次确认页未国际化
<img width="1489" alt="image" src="https://github.com/TencentBlueKing/bk-cmdb/assets/82890468/51aa3ee2-6b67-432b-9c6a-005578736602">

**Comment by testqwerts** [comment]
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/f4fd0b96-bd27-44c8-aa45-e77c256f18e4)
内置的字段还没实现国际化

**Comment by wcy00000000000000** [comment]
这两个字段不是系统内置字段，忽略即可
