### ISSUE TITLE
【3.10.24-alpha1 】确定取消框未国际化

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6802]
一、前提条件

中英文切换中切换语言为英文或者中文

二 、重现步骤
所有确定取消框未国际化，以下是几个case

确认删除主机时：
![image](https://user-images.githubusercontent.com/66291315/231672371-c68fa0d3-2429-41f7-bf9a-52a50abdf9fb.png)

退出创建业务时：
![image](https://user-images.githubusercontent.com/66291315/231673203-b03ec1b4-1de3-4fa2-b232-aa5e20b0187f.png)

确认删除模型时：
![image](https://user-images.githubusercontent.com/66291315/231674125-3d34f69e-63cb-464d-a54a-e0a41a61b891.png)

确认应用属性列表配置：
![image](https://user-images.githubusercontent.com/66291315/231930319-b2602086-4f8d-4d9d-8cb1-6092a74a5859.png)

归档业务时：
![image](https://user-images.githubusercontent.com/66291315/232365678-ce0ccec8-e5da-4a0a-9f0c-780a1405aa62.png)

**Comment by reggieisrunning** [comment]
<img width="1100" alt="image" src="https://github.com/TencentBlueKing/bk-cmdb/assets/82890468/b76689a6-dda5-46dd-9ebd-3895a7f89c6e">

**Comment by reggieisrunning** [comment]
确认应用属性列表配置：
<img width="1232" alt="image" src="https://github.com/TencentBlueKing/bk-cmdb/assets/82890468/58dce564-229f-40e1-a3bc-a7798a0da39d">
