### ISSUE TITLE
fail to watch children for path(/cc/services/endpoints/auth), err:zk: node does not exist children node(/cc/services/endpoints/auth) is not exist, will watch after 5s

### ISSUE THREAD

**Issue by GLL550C** [TencentBlueKing/bk-cmdb#6833]
问题描述
===========

服务启动报错：err:zk: node does not exist
cmdb所有服务

![image](https://user-images.githubusercontent.com/64561461/232427567-981419ce-f78a-491e-a922-3a2bbf179a72.png)

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 3.10.23
 
 - [x] Redis     版本: 3.2.12
 - [x] MongoDB   版本: 4.2.1
 - [x] ZooKeeper 版本: 3.7.1
 - [x] 操作系统      :  Centos 7 x64
 - [x] bk-cmdb 异常日志

**Comment by ZQHcode** [comment]
如果不需要使用authserver进行鉴权，那么可以检查下start.sh脚本里，是否有这个参数 --enable-auth=false

**Comment by workman-Lu** [comment]
> 如果不需要使用authserver进行鉴权，那么可以检查下start.sh脚本里，是否有这个参数 --enable-auth=false

3.12版本没有这个参数
