### ISSUE TITLE
cmdb自建模型实例详情点击报错

### ISSUE THREAD

**Issue by chestarss** [TencentBlueKing/bk-cmdb#6846]
问题描述
===========

新建实例后，点击实例主键id无法进入详情

console报错
65385.f3ee8f8eb1336f88bc1c.js:1 Uncaught (in promise) ReferenceError: Cannot access 'v' before initialization
    at Module.default (5385.f3ee8f8eb1336f88bc1c.js:1:132)
    at vendors.6cc115b96b823f2e3aa5.js:2:962926
    at vendors.6cc115b96b823f2e3aa5.js:2:960756

![image](https://user-images.githubusercontent.com/11288347/232786401-1a9fa7f9-facb-4a32-982d-ae7bfe960814.png)

重现方法
================

关键信息
=========
cmdb版本：

请提供以下信息:

cmdb-webserver--version 
Version     : v3.10.21
Tag         : release-v3.10.21
BuildTime   : 2022-09-28T20:04:38+0800
GitHash     : 64c244d1b49a468f42f0416efefee80e85e37e60
RunMode     : product
Distribution: community
ServiceName : webserver

cmdb-apiserver --version
Version     : v3.10.21
Tag         : release-v3.10.21
BuildTime   : 2022-09-28T20:04:38+0800
GitHash     : 64c244d1b49a468f42f0416efefee80e85e37e60
RunMode     : product
Distribution: community
ServiceName : webserver

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by chestarss** [comment]
![image](https://user-images.githubusercontent.com/11288347/232787919-e259e0eb-5af2-4857-8aad-c220b3c13b9f.png)

**Comment by bd-xiaowang** [comment]
![模型实例详情](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/a7e2f25e-bd8f-4541-9e21-689162c7767f)
CMDB版本v3.11.x，测试： 新建实例后，点击实例主键id无法进入详情问题。
接口数据正常返回，应该是在后续的版本中已修复该问题，请尝试使用最新版本的CMDB，如问题依旧存在，请提供CMDB版本以及相应的报错日志
