### ISSUE TITLE
编译部署体验极差！！！

### ISSUE THREAD

**Issue by rayshen3** [TencentBlueKing/bk-cmdb#6876]
1、部署、编译文档，步骤混乱，不看几遍真搞不清怎么部署，很多地方要靠猜，编译各种报错
2、配置参数描述模糊，继续猜
3、这么好的产品，部署交付完全可以上点心，弄个二进制包交付是基本功能吧

**Comment by ZQHcode** [comment]
你好，可以贴一下部署过程中遇到的问题，这边协助看一下

**Comment by GuoFlight** [comment]
+1，各种部署报错，对用户友好是一个产品必备的要素。文档也很乱很杂

**Comment by rayshen3** [comment]
就提一个地方，这种问题太多了
首页不让用master分支代码部署，部署手册中又是直接去master pull 。。。  
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/9734936/0506be0e-51fd-4793-bbd9-53066f608234)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/9734936/9b91b598-fc8b-4021-a315-02692d7055f0)

**Comment by wswn5456** [comment]
`编译
进入源码根目录执行make或make server编译指令时，默认会编译后端服务涉及到的所有组件，包括monstache及其对应的monstache-plugin.so插件。您也可以进入到monstache目录，执行make命令单独进行monstache及其插件的编译。`

**Comment by bd-xiaowang** [comment]
很抱歉给您不好的体验，我们会继续加强产品文档的建设工作，同样邀请您参与协同共建。
关于编译部署的相关您可以参考最新的编译部署帮助文档：https://github.com/TencentBlueKing/bk-cmdb/pull/7352/commitshttps://github.com/TencentBlueKing/bk-cmdb/pull/7352/commits
如还未能解决您的问题，可提供相应的问题描述、日志信息等我们会第一时间协助解决
