### ISSUE TITLE
没有PAAS能不能部署iam,iam-saas,bk-user,bk-cmdb?

### ISSUE THREAD

**Issue by goluckycoding** [TencentBlueKing/bk-cmdb#6881]
问题描述
===========
现在部署的时候发现很多url需要配置成paas，然后iam-saas，bk-user里面又因为前后端分离，python配置各种缺失报错，导致无法分清哪些端口是谁的，或者域名url需要如何配置才能让这几者关联起来，那么就很疑惑是不是必须要有paas才能起起来这些，但实际上目前并没有引入paas的想法，请问能提供iam-saas和bk-user的配置和域名端口吗，因为这里面前后端有两个端口比如5000都重复了，还有8000端口

关键信息
=========

请提供以下信息:
都是master分支

**Comment by ZQHcode** [comment]
cmdb是可以不依赖其他平台进行单独部署的（按照《安装部署》文档操作即可）；如果需要进行鉴权和根据用户管理的用户进行登陆，才需要部署iam和bk-user这些平台；如果对于paas平台部署有疑问，可以在这里(https://github.com/TencentBlueKing/legacy-bk-paas) 提问哈
