### ISSUE TITLE
【3.10.24-alpha1 】业务集未国际化完全

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6899]
一、前提条件

中英文切换中已切换语言为英文

二 、重现步骤

新建业务集时Business Set正常显示英文，Create业务集存在中文
![image](https://user-images.githubusercontent.com/66291315/234169280-edbb1224-10e4-4122-9eef-78806cc55b66.png)

编辑业务集时前端提示编辑成功
![image](https://user-images.githubusercontent.com/66291315/234170062-9652d610-d3d0-49f3-aeb0-f82c86c03546.png)
![image](https://user-images.githubusercontent.com/66291315/234170257-950115ad-cf7a-45ea-8760-ee97606f075f.png)

搜索框可搜索字段
![image](https://user-images.githubusercontent.com/66291315/234195936-2bde40e1-26f9-4e72-84f0-16f823d3bfa4.png)

**Comment by laodiu** [comment]
新建业务集时Business Set正常显示英文，Create业务集存在中文, cmdb最新版本不存在该问题，需要更新对应的配置文件，再看看
![image](https://user-images.githubusercontent.com/39582223/234442137-3556897b-f8b9-4717-bb34-600059fd254a.png)
