### ISSUE TITLE
【3.10.24-alpha1 】项目未国际化完全

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6900]
一、前提条件

中英文切换中已切换语言为英文

二 、重现步骤

搜索框可搜索字段未国际化
![image](https://user-images.githubusercontent.com/66291315/234203199-d6eb2fd3-7e3d-4950-af74-3d4a55c3396f.png)

字段类型是枚举类型，枚举值存在未国际化的情况，包括其它内置模型，如主机、交换机等，建议全面排查内置模型的枚举字段是否做相应的国际化
如下图
项目模型中
![image](https://user-images.githubusercontent.com/66291315/234207525-0aceaccf-205a-4c51-842a-e3e0f8ef8055.png)

交换机中
![image](https://user-images.githubusercontent.com/66291315/234207869-27c8d6da-f892-4451-8753-e45327020445.png)

主机模型中
![image](https://user-images.githubusercontent.com/66291315/234208580-e3c196fe-8033-439a-857e-08aab2db1f14.png)

**Comment by laodiu** [comment]
1、搜索框可搜索字段未国际化，最新版本已经国际化，请更新对应的配置文件再看看
![image](https://user-images.githubusercontent.com/39582223/234442930-065f1489-68e8-4c0c-9aa3-1fdf3ee75a89.png)

@reggieisrunning 内置枚举字段是否做国际化？

**Comment by reggieisrunning** [comment]
@sobbingchild “列表”类型的列表值不适合做国际化，因为用户消费的是“值内容本身”，做了国际化，反而产生二义性，基于此点再消费会出现歧义

**Comment by reggieisrunning** [comment]
@sobbingchild 交换机中的厂商亦是如此，对于短字符，用户要求“值本身”的诉求高于“国际化能看懂”

**Comment by reggieisrunning** [comment]
除上面两条评论涉及之外的内容均已修复完成
