### ISSUE TITLE
【3.10.24-alpha1 】交换机/防火墙/路由器/负载均衡自定义模型 未国际化合集

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6901]
一、前提条件

中英文切换中已切换语言为英文

二 、重现步骤

以下是各模型未国际化问题，以交换机截图举例，其它模型也是如此
交换机/防火墙/路由器/自定义模型可搜索字段未国际化
![image](https://user-images.githubusercontent.com/66291315/234235804-e4715519-16b0-4f60-9d95-d755ab7c7aa6.png)

交换机中的高级筛选（内置字段）
![image](https://user-images.githubusercontent.com/66291315/234236082-1d7b6ab2-22e0-4ba9-8681-21a680926275.png)

Export或者import
![image](https://user-images.githubusercontent.com/66291315/234238007-7d18aef1-498a-4a86-b23b-7237f73af504.png)

![image](https://user-images.githubusercontent.com/66291315/234238371-ea62e697-e5da-4d48-b17e-23d23e6c07cf.png)

对应的属性列表配置（tips:内置模型的属性列表配置或者自定义模型的属性列表配置其内置字段均未国际化）
![image](https://user-images.githubusercontent.com/66291315/234238819-3f727afc-6bd7-4bc7-8dc5-92095160f938.png)

**Comment by laodiu** [comment]
最新版本中均已做了国际化处理，更新测试环境中的配置文件 @reggieisrunning
