### ISSUE TITLE
【3.10.24-alpha1 】云区域未国际化完全

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6903]
一、前提条件

中英文切换中已切换语言为英文

二 、重现步骤

Cloud Area中的cloud vendor
![image](https://user-images.githubusercontent.com/66291315/234456809-0e3b8d9a-c15e-4494-bcc4-cc5a7d0a23a9.png)
删除云区域时前端提示删除成功
![image](https://user-images.githubusercontent.com/66291315/234457459-37cbda7b-e0a6-41a3-a067-a34c2addef32.png)
![image](https://user-images.githubusercontent.com/66291315/234457668-67efc733-752f-4e28-ade3-694650a1cd33.png)

cloud account中的Account type
![image](https://user-images.githubusercontent.com/66291315/234460819-f944b056-8c6b-4992-9f98-5336ad0f6eb1.png)
修改cloud account时，前端提示修改成功
![image](https://user-images.githubusercontent.com/66291315/234461026-19cb1a4d-0dda-4bd1-9317-31e6646402d7.png)
![image](https://user-images.githubusercontent.com/66291315/234461094-1de2dd3a-408f-4c66-90e7-395cd7879c5a.png)

删除云资源发现中的任务时提示删除成功
![image](https://user-images.githubusercontent.com/66291315/234461182-0035f162-6052-4ae9-857e-2100c2a2a7a7.png)
Task details中的账户名称及资源类型无法查看到完整的英文
![image](https://user-images.githubusercontent.com/66291315/234463073-8f8e0e22-1258-4e13-a51a-015d1dd7b0cf.png)

**Comment by laodiu** [comment]
后端已完成国际化，其余需要前端处理@林志瀚

**Comment by reggieisrunning** [comment]
「修改cloud account时，前端提示修改成功」仍未修复
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/82890468/6673869b-76f3-491f-8518-a24267110705)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/82890468/384ec321-bf18-488c-b7fa-62026deff466)
