### ISSUE TITLE
请问cmdb有没有golang sdk

### ISSUE THREAD

**Issue by chestarss** [TencentBlueKing/bk-cmdb#6906]
问题描述
===========

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by bd-xiaowang** [comment]
请参考官方文档中心：https://bk.tencent.com/docs/markdown/ZH/CMDB/ErrorCode/cmdb.md

**Comment by bd-xiaowang** [comment]
非常抱歉暂时还没有完善CMDB相关的golang sdk，请您继续关注CMDB后续的更新
