### ISSUE TITLE
【3.10.x-feature-agent-id-alpha14 】主机搜索通过搜索后显示暂无数据

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6924]
一、前提条件

主机搜索中将搜索条件判断为固资编号后提示搜索结果为空
![image](https://user-images.githubusercontent.com/66291315/235099973-1d614a95-0780-4bce-a968-3583d9f1081e.png)

二 、重现步骤及预期结果

主机搜索中将搜索条件判断为内网IP后提示暂无数据
![image](https://user-images.githubusercontent.com/66291315/235102673-ffbfd200-a81a-413a-9539-8c561db0baa0.png)

主机搜索中将搜索条件判断为内网IP后应提示搜索结果为空，通过搜索按钮触发了搜索功能

**Comment by wjyfelen** [comment]
@yangyy
