### ISSUE TITLE
【3.10.x-feature-agent-id-alpha14 】全文检索搜索为空时前端提示与设计规范不符

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6928]
一、前提条件

二 、重现步骤

全文检索中搜索不存在的关键词，如下图
![image](https://user-images.githubusercontent.com/66291315/236144787-9e6d6d6d-776a-42cc-b9f9-5ca36dbcb586.png)

三 、预期结果

通过搜索，搜索结果为空时，空状态预期
![image](https://user-images.githubusercontent.com/66291315/236143714-473276d0-4533-44af-b111-162745b0f072.png)

四 、实际结果

抱歉，搜不到相关内容，换个词试一试～
![image](https://user-images.githubusercontent.com/66291315/236144893-a2802480-e76d-4b0a-829d-8d111b51f319.png)

**Comment by wjyfelen** [comment]
@yangyy @reggieisrunning 辛苦看下
