### ISSUE TITLE
【3.10.x-feature-agent-id-alpha14 】服务分类搜索结果为空时，搜索结果框未居中

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#6930]
一、前提条件

集群模板搜索结果为空时，搜索结果框居中如下图
![image](https://user-images.githubusercontent.com/66291315/236152803-0f11bfef-984e-47cd-91ff-af1fbcf42dd6.png)

服务模板搜索结果为空时，搜索结果框居中如下图
![image](https://user-images.githubusercontent.com/66291315/236152896-e90a39a7-339a-4038-8777-1d6c86b97ea2.png)

二 、重现步骤

服务分类中搜索不存在的服务分类

三 、预期结果

前端提示搜索结果为空且搜索结果框居中

四 、实际结果

前端提示搜索结果为空但搜索结果框未居中
![image](https://user-images.githubusercontent.com/66291315/236158005-cafcb999-6562-4bde-8554-dc209980dd42.png)

**Comment by wjyfelen** [comment]
@yangyy
