### ISSUE TITLE
【3.10.x-feature-agent-id-alpha14 】自定义字段新建（集群）“枚举多选”业务字段后，编辑功能失效，且动态分组下没有正确查询

### ISSUE THREAD

**Issue by testqwerts** [TencentBlueKing/bk-cmdb#6943]
问题描述
自定义字段新建（集群）“枚举多选”业务字段后，
问题1.编辑功能失效，
问题2.动态分组下没有正确查询

一、前提条件
1.已在自定义字段新建（集群）“枚举多选”字段
![image](https://user-images.githubusercontent.com/132563061/236422510-0c005992-8b32-4756-a546-7f4b9d27c849.png)
2.已新建对应动态分组查询条件为枚举多选（集群）

二 、重现步骤
问题1：
1.点击对应（集群）字段，点击编辑
2.输入编辑信息，点击保存

问题2：浏览对应动态分组
三 、预期结果
问题1：编辑成功，对应信息显示为修改后的信息
问题2：动态分组下命中查询条件正确展示对应集群下的主机

四 、实际结果
问题1：编辑功能失效
![image](https://user-images.githubusercontent.com/132563061/236423565-0e8e9d5a-7cd4-4ff9-933c-562a8fb10667.png)
![image](https://user-images.githubusercontent.com/132563061/236423662-0125ecb6-8c85-4876-900d-7a8e17b9dde0.png)
![image](https://user-images.githubusercontent.com/132563061/236423709-aaa25272-8873-48f1-b509-df3421177260.png)

问题2：浏览动态分组能没有正确展示对应集群下的主机
![image](https://user-images.githubusercontent.com/132563061/236423910-8de00912-d9ed-4b00-87c0-dfed1a61102c.png)
![image](https://user-images.githubusercontent.com/132563061/236423995-6610f859-4302-4bb0-9631-f0e7cab4034d.png)
![image](https://user-images.githubusercontent.com/132563061/236424055-1b75a63a-76b4-405e-9d31-7891c04c5f19.png)

**Comment by wjyfelen** [comment]
@laodiu
