### ISSUE TITLE
【3.10.x-feature-agent-id-alpha14 】自定义字段新建集群/模块/主机分组下的业务字段，不能编辑业务字段名称

### ISSUE THREAD

**Issue by testqwerts** [TencentBlueKing/bk-cmdb#6946]
一、前提条件
已在自定义字段下新建一个分组，并且分组下有对应的业务字段
二 、重现步骤
点击编辑对应业务字段，修改业务名称，点击保存
三 、预期结果
修改业务字段成功，保存后，业务字段名称显示为修改后的名称

四 、实际结果
前端显示修改成功，实际上并没有修改成功
![image](https://user-images.githubusercontent.com/132563061/236592128-1c2eba58-88c0-44a6-925f-4845e901a6e5.png)
![image](https://user-images.githubusercontent.com/132563061/236592161-1f991aee-ceab-484e-99a8-813b59632a5e.png)

**Comment by laodiu** [comment]
和上一个单子一样的问题，已经修复
