### ISSUE TITLE
clientset目录下没有discovery

### ISSUE THREAD

**Issue by han-yh** [TencentBlueKing/bk-cmdb#6947]
问题描述
===========

![image](https://user-images.githubusercontent.com/103162595/236592848-55fe96b9-926e-4aa0-9487-2267e2049a63.png)
clientset目录下没有discovery，
在https://github.com/TencentBlueKing/bk-cmdb/releases地址里所有的版本及最新版本均有此问题

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: master、release
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by bd-xiaowang** [comment]
此模块及对应的方法似乎已弃用
