### ISSUE TITLE
【3.10.x-feature-agent-id-alpha14 】资源目录通用模型导入功能失效

### ISSUE THREAD

**Issue by testqwerts** [TencentBlueKing/bk-cmdb#6954]
一、前提条件
已下载导入模板，并编辑好需要导入的数据
二 、重现步骤
1.点击导入
2.点击上传需要导入的文件
3.点击下一步，开始导入
三 、预期结果
导入成功，列表下显示导入的数据

四 、实际结果
前端页面提示导入成功，但是对应数据并没有正确导入至列表
![image](https://user-images.githubusercontent.com/132563061/236600340-1c6e454b-bc93-4b02-a788-fe539d3c37c6.png)
![image](https://user-images.githubusercontent.com/132563061/236600375-b4efb43b-71c7-4b25-9212-1b10e7cdd1fb.png)
![image](https://user-images.githubusercontent.com/132563061/236600397-d7bb1c3e-4bb7-47b2-9e7c-b767d04095f0.png)

**Comment by laodiu** [comment]
这个属于更新场景， 新增场景无bk_inst_id字段。

**Comment by sobbingchild** [comment]
分两种情况：
case1:下载模板进行导入如图1，导入内容如图2，前端显示导入成功，实际未成功导入该实例
![企业微信截图_16836032325545](https://user-images.githubusercontent.com/66291315/237009639-02f97182-5923-4a50-97c7-3c606d3277fa.png)
![企业微信截图_16836032207499](https://user-images.githubusercontent.com/66291315/237009695-ad8b09af-b19a-4447-ac1e-8ba30ab168aa.png)
![企业微信截图_1683603212893](https://user-images.githubusercontent.com/66291315/237009657-6999caac-72e9-4677-854e-b94a1607419b.png)

case2:另外一种先导出文件，根据导出的文件就行编辑修改，修改实例名后进行导入，前端显示导入成功实际未成功修改（tips:其它字段可成功修改导入，实例名允许修改导入）
