### ISSUE TITLE
【3.10.x-feature-agent-id-alpha14 】CC和节点管理下云服务商 两边显示不一致

### ISSUE THREAD

**Issue by testqwerts** [TencentBlueKing/bk-cmdb#6956]
一、前提条件
存在对应云区域
二 、重现步骤
1.进入CC查看云区域
2.进入节点管理查看云区域
三 、预期结果
CC和节点管理下云服务商 两边显示一致

四 、实际结果
CC和节点管理下云服务商 两边显示不一致
![image](https://user-images.githubusercontent.com/132563061/236601179-b18f4ffa-8891-4587-aa36-0f9481f079f7.png)
![image](https://user-images.githubusercontent.com/132563061/236601221-21bc57cc-7051-4f19-ad47-4970169af816.png)

**Comment by reggieisrunning** [comment]
待处理

**Comment by reggieisrunning** [comment]
需和节点管理一起跟进这个问题，此单已记录TAPD#1010080961110852869后续处理
