### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by qifeng998130** [TencentBlueKing/bk-cmdb#6961]
问题描述
=========== 
![image](https://user-images.githubusercontent.com/12607253/236751612-2584b60e-84c9-4331-85c9-df1cfa07e8cc.png)

 请问一下，我cmdb版本是bk-cmdb-release-v3.10.25.zip ，对应node 和npm版本是多少呢、
 

 - [x] bk-cmdb   版本:  
Version     : v3.10.21
Tag         : release-v3.10.21
BuildTime   : 2022-09-28T20:03:58+0800
GitHash     : 64c244d1b49a468f42f0416efefee80e85e37e60
RunMode     : product
Distribution: community
ServiceName : apiserver

**Comment by yangyy** [comment]
node: v12.13.1
npm: 6.12.1
@qifeng998130

**Comment by fit2cloud-zhangjinli** [comment]
<img width="989" alt="image" src="https://github.com/TencentBlueKing/bk-cmdb/assets/73459704/e8bfed95-24cb-4ec5-acdb-d919076a40b3">

cmdb version : 3.10.26
[root@bk-cmdb src]# node -v 
v12.13.1
[root@bk-cmdb src]# npm -v
6.12.1
编译报错，这个是我node问题吗？

**Comment by elkon028** [comment]
> <img alt="image" width="989" src="https://user-images.githubusercontent.com/73459704/237961026-e8bfed95-24cb-4ec5-acdb-d919076a40b3.png">
> cmdb version : 3.10.26 [root@bk-cmdb src]# node -v v12.13.1 [root@bk-cmdb src]# npm -v 6.12.1 编译报错，这个是我node问题吗？

- `src/ui/package.json` 文件中
删除 fibers，这个开发依赖好象是没有使用的多于东东
