### ISSUE TITLE
源码编译报错

### ISSUE THREAD

**Issue by fit2cloud-zhangjinli** [TencentBlueKing/bk-cmdb#6977]
问题描述
===========

编译源码报错，
<img width="991" alt="image" src="https://github.com/TencentBlueKing/bk-cmdb/assets/73459704/7c67c220-f340-4d77-9f69-91c701f1cec2">

重现方法
================
进入configcenter/src后编译执行make

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
cmdb version : 3.10.26
[root@bk-cmdb src]# node -v
v12.13.1
[root@bk-cmdb src]# npm -v
6.12.1

**Comment by elkon028** [comment]
- `src/ui/package.json` 文件中
删除 fibers，这个开发依赖好象是没有使用的多于东东

**Comment by yangyy** [comment]
@elkon028 @fit2cloud-zhangjinli 相同版本下未复现此问题，请使用最新的v3.10.x重试下

**Comment by bd-xiaowang** [comment]
可从以下方面排查
1、检查 Node.js 和 npm 版本，清除 npm 缓存并重新安装依赖，再次重新编译；
2、检查主机内存是否充足，编译时内存不足可能会导致编译失败，如果编译进入读条但编译时长久且最终编译失败，大概率就是内存不足问题
其它问题可参考最新CMDB编译部署指南：https://github.com/TencentBlueKing/bk-cmdb/pull/7352/files#diff-137a3289d2d9c3b98174af9cb3068567c079bacfd4fd59d3e5a516f358556b51
