### ISSUE TITLE
实例名bk_inst_name 唯一校验不生效

### ISSUE THREAD

**Issue by chestarss** [TencentBlueKing/bk-cmdb#6990]
问题描述
===========

创建了一个模型，bk_inst_name默认是有个唯一约束，但是添加相同的值却能加进去

![image](https://github.com/TencentBlueKing/bk-cmdb/assets/11288347/54db9c10-5b3b-4df1-b9ab-d57135a150be)

![image](https://github.com/TencentBlueKing/bk-cmdb/assets/11288347/f2d02aa6-9b89-4970-9918-8c7abb8b94b2)

重现方法
================

关键信息
=========

请提供以下信息:
[root@bk-cmdb-apiserver-5c74f8d54b-jl5tr cmdb_apiserver]# ./cmdb_apiserver --version
Version     : v3.10.21
Tag         : release-v3.10.21
BuildTime   : 2022-09-28T20:03:58+0800
GitHash     : 64c244d1b49a468f42f0416efefee80e85e37e60
RunMode     : product
Distribution: community
ServiceName : apiserver

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by ZQHcode** [comment]
你好，正常来说，创建唯一校验后，如果数据不满足唯一校验，那么创建实例会失败；反过来，如果有实例的数据不满足唯一性，那么创建唯一校验会失败；目前没有复现成功，麻烦提供下复现的方法，我们看下

**Comment by chestarss** [comment]
> 你好，正常来说，创建唯一校验后，如果数据不满足唯一校验，那么创建实例会失败；反过来，如果有实例的数据不满足唯一性，那么创建唯一校验会失败；目前没有复现成功，麻烦提供下复现的方法，我们看下

已经找到问题了，是我的mongodb出问题了，导致唯一索引不生效，重启mongodb后唯一约束生效了。我记得以前版本的唯一约束好像是cmdb业务层做的, 看了下最新的代码改成了数据库索引做的
