### ISSUE TITLE
通过api添加主机时,bool类型设置默认值是true ，但是实际添加后默认值始终是false

### ISSUE THREAD

**Issue by mingyueqingfeng10** [TencentBlueKing/bk-cmdb#7005]
问题描述
配置平台: v3.10.21
通过api添加主机时,bool类型设置默认值是true ，但是实际添加时不设置参数，添加进去后默认值始终是false
 url   http://paas.bktencent.com/api/c/compapi/v2/cc/add_host_to_resource/
param：{
  "bk_app_code": "bk_iam",
  "bk_app_secret": "22775e7b-c807-4eed-8319-7a2b2be95d42",
  "bk_username": "admin",
  "host_info": {
    "0": {
      "bk_host_innerip": "10.0.0.12",
      "bk_cloud_id": 0,
      "import_from": "3"
    }
  }
}

关键信息
![1684898251529](https://github.com/TencentBlueKing/bk-cmdb/assets/84175872/1cf6b78d-fb7d-4483-bded-04e514937659)
![1684898169560](https://github.com/TencentBlueKing/bk-cmdb/assets/84175872/cf9979d2-773e-4f98-8ff3-60e6e748f223)

**Comment by bd-xiaowang** [comment]
已反馈

**Comment by bd-xiaowang** [comment]
在cmdb字段类型中，bool类型较为特殊，按照正常逻辑，所有参数被传至后端后会被解析到对应的结构体中，其它类型字段未设置值解析到结构体中时会被解析为空字符或对应的0值，此时可根据为空字符或对应的0值来判断是否应用默认值；
而bool类型作为基础类型，如果在传参时未传递值被解析到结构体中会被解析为false，此时无法判断是传参中想设置为false还是解析结构体时设置的false，故自动判断为已传参false
