### ISSUE TITLE
monstache 编译后没有可执行文件

### ISSUE THREAD

**Issue by wswn5456** [TencentBlueKing/bk-cmdb#7013]
monstache 编辑问题
===========

git clone https://github.com/Tencent/bk-cmdb configcenter 下载的源码。

依据 https://github.com/TencentBlueKing/bk-cmdb/blob/master/src/tools/monstache/README.md  文档编译后，monstache目录中不会生成目标文件  monstache ,只有 monstache-plugin.so 插件.

重现方法
================

git clone https://github.com/Tencent/bk-cmdb configcenter  下载源码，编译。查看 src/tools/monstache目录

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [x] Redis     版本: 
 - [x] MongoDB   版本: 
 - [x] ZooKeeper 版本: 
 - [x] 操作系统      : 
 - [x] bk-cmdb 异常日志

**Comment by wswn5456** [comment]
git clone https://github.com/Tencent/bk-cmdb

**Comment by rayshen3** [comment]
+1，编译各种问题
[root@ops monstache]# ls
build  CHANGELOG.md  etc  Makefile  monstache.sh  plugin.go  README.md
[root@ops monstache]# make 
go build -buildmode=plugin -o /data/configcenter/src/tools/monstache/build/monstache/etc/monstache-plugin.so *.go

[root@ops monstache]# ls build/monstache/ -R
build/monstache/:
CHANGELOG.md  etc  monstache.sh  README.md

build/monstache/etc:
config.toml  extra.toml  monstache-plugin.so

**Comment by bd-xiaowang** [comment]
已反馈

**Comment by wbpyer** [comment]
这个问题怎么样了，我也遇到了这样的问题， 自己编译的monstache 没有办法和插件版本对应上。

**Comment by bd-xiaowang** [comment]
@wswn5456 @rayshen3 @wbpyer CMDB 开启全文检索功能可参考开源社区文章进行开启：https://bk.tencent.com/s-mart/community/question/8248?type=article
其中所使用到的monstache二进制文件及monstache-plugin.so插件请不要使用自己编译的版本，直接下载文章内提供的配套版本进行使用
