### ISSUE TITLE
【3.10.27-alpha3】Host Statistics及Instance Statistics删除图表时切换英文未完全

### ISSUE THREAD

**Issue by sobbingchild** [TencentBlueKing/bk-cmdb#7041]
一、前提条件

已切换英文

二 、重现步骤

分别如下图删除图表
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/66291315/d4072363-0cc8-4b64-9098-cbb098c35478)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/66291315/a66a3d8e-c213-4f6e-97a4-28ac57a70b23)

三 、预期结果

点击后切换中英文完全

四、实际国际

点击后切换中英文未完全，存在中文确定要删除
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/66291315/83a120e8-1dfe-47c2-8375-76c3031bd08e)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/66291315/9d547d6f-a82a-49fa-9d5c-7e8c21f6bb65)

**Comment by reggieisrunning** [comment]
转内部TAPD关注
