### ISSUE TITLE
启动不起来

### ISSUE THREAD

**Issue by yuyc** [TencentBlueKing/bk-cmdb#7049]
改来改去，总有两个进程起不来：
前后也没有相关信息。就是zk的服务里面没有相关上报。
W0615 17:14:56.816074  360406 discovery/server.go:111] get zk event with 0 instance with path[/cc/services/endpoints/migrate], reset its servers
W0615 17:14:56.843216  360406 discovery/server.go:104] received one zk event from path /cc/services/endpoints/apiserver.
W0615 17:14:56.843225  360406 discovery/server.go:111] get zk event with 0 instance with path[/cc/services/endpoints/apiserver], reset its servers
W0615 17:14:56.885948  360406 discovery/server.go:104] received one zk event from path /cc/services/endpoints/cacheservice.
W0615 17:14:56.885958  360406 discovery/server.go:111] get zk event with 0 instance with path[/cc/services/endpoints/cacheservice], reset its servers
E0615 17:14:55.788488  360406 logics/index.go:91] db not initialization is complete, rid: cc0000ci5d17s92kh77sn2kpb0
I0615 17:14:56.813039  360406 backbone/http.go:51] receive signal terminated, begin to shutdown

**Comment by ZQHcode** [comment]
是哪两个进程呢，麻烦提供下std.log文件，我们看下
