### ISSUE TITLE
cmdb编译报错

### ISSUE THREAD

**Issue by westbullman** [TencentBlueKing/bk-cmdb#7052]
问题描述
===========
configcenter/src下make报错

重现方法
================
安装文档 clone、到src下make报错！
本地环境：mac、node版本：v16.17.0，golang版本：1.19，python版本是：2.7.16
编译报错如下：
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: bk-cmdb-ui@1.0.0
npm ERR! Found: vue@2.7.14
npm ERR! node_modules/vue
npm ERR!   vue@"^2.7.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR! node_modules/@vue/composition-api
npm ERR!   @vue/composition-api@"^1.6.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/zg/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zg/.npm/_logs/2023-06-16T03_45_43_174Z-debug-0.log
make: *** [default] Error 1

**Comment by westbullman** [comment]
我看编译的时候没要求安装vue啊，为啥编译报vue相关的错，不懂

**Comment by yangyy** [comment]
@westbullman 最新的版本中已经解决此问题，如仍要使用老版本请先删除 package.json 文件中的  "@vue/composition-api" 依赖后重试。

**Comment by westbullman** [comment]
谢谢。这个问题解决了
