### ISSUE TITLE
启动失败，报错内容：Not Running: cmdb_authserver

### ISSUE THREAD

**Issue by westbullman** [TencentBlueKing/bk-cmdb#7066]
问题描述
===========
./start.sh 

控制台输出的内容是：
starting: cmdb_adminserver
starting: cmdb_apiserver
starting: cmdb_authserver
starting: cmdb_cacheservice
starting: cmdb_cloudserver
starting: cmdb_coreservice
starting: cmdb_datacollection
starting: cmdb_eventserver
starting: cmdb_hostserver
starting: cmdb_operationserver
starting: cmdb_procserver
starting: cmdb_taskserver
starting: cmdb_toposerver
starting: cmdb_webserver
root     25706 25492  0 6月15 ?       00:28:14 ./cmdb_adminserver --addrport=172.17.0.2:60004 --logtostderr=false --log-dir=./logs --v=3 --config=configures/migrate.yaml
root     25730 25492  0 6月15 ?       00:35:41 ./cmdb_apiserver --addrport=172.17.0.2:8080 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
root     25990 25492  5 6月15 ?       05:19:28 ./cmdb_cacheservice --addrport=172.17.0.2:50010 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root     26245 25492  0 6月15 ?       00:38:27 ./cmdb_cloudserver --addrport=172.17.0.2:60013 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false --enable_cryptor=false
root     26498 25492  0 6月15 ?       00:44:44 ./cmdb_coreservice --addrport=172.17.0.2:50009 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root     26746 25492  0 6月15 ?       00:42:01 ./cmdb_datacollection --addrport=172.17.0.2:60005 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
root     26837 25492  1 6月15 ?       01:22:34 ./cmdb_eventserver --addrport=172.17.0.2:60009 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
root     26956 25492  0 6月15 ?       00:33:19 ./cmdb_hostserver --addrport=172.17.0.2:60001 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
root     27114 25492  0 6月15 ?       00:34:40 ./cmdb_operationserver --addrport=172.17.0.2:60011 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
root     27139 25492  0 6月15 ?       00:32:54 ./cmdb_procserver --addrport=172.17.0.2:60003 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
root     27260 25492  0 6月15 ?       00:44:57 ./cmdb_taskserver --addrport=172.17.0.2:60012 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
root     27468 25492  0 6月15 ?       00:36:46 ./cmdb_toposerver --addrport=172.17.0.2:60002 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
root     27722 25492  0 6月15 ?       00:34:52 ./cmdb_webserver --addrport=172.17.0.2:8090 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
process count should be: 12 , now: 13
Not Running: cmdb_authserver

请大佬协助看下

**Comment by westbullman** [comment]
std.log内容是：start.sh:行15: ./cmdb_authserver: 无法执行二进制文件

**Comment by ZQHcode** [comment]
authserver启动需要依赖于第三方系统<权限中心>，除了没有鉴权逻辑外，是不影响cmdb的单独部署使用的哈

**Comment by westbullman** [comment]
现在stg.log的内容是：
begin to discover by watch children of path(/cc/services/endpoints/coreservice)
begin to discover by watch children of path(/cc/services/endpoints/auth)
begin to discover by watch children of path(/cc/services/endpoints/cacheservice)
begin to discover by watch children of path(/cc/services/endpoints/apiserver)
begin to discover by watch children of path(/cc/services/endpoints/proc)
begin to discover by watch children of path(/cc/services/endpoints/topo)
begin to discover by watch children of path(/cc/services/endpoints/host)
begin to discover by watch children of path(/cc/services/endpoints/migrate)
begin to discover by watch children of path(/cc/services/endpoints/datacollection)
begin to discover by watch children of path(/cc/services/endpoints/operation)
begin to discover by watch children of path(/cc/services/endpoints/task)
begin to discover by watch children of path(/cc/services/endpoints/cloud)
begin to discover by watch children of path(/cc/services/endpoints/eventserver)
children node(/cc/services/endpoints/auth) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/auth), err:zk: node does not exist
children node(/cc/services/endpoints/auth) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/cacheservice), err:zk: node does not exist
children node(/cc/services/endpoints/cacheservice) is not exist, will watch after 5s
children node(/cc/services/endpoints/cacheservice) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/cloud), err:zk: node does not exist
children node(/cc/services/endpoints/cloud) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/datacollection), err:zk: node does not exist
children node(/cc/services/endpoints/datacollection) is not exist, will watch after 5s
children node(/cc/services/endpoints/datacollection) is not exist, will watch after 5s
children node(/cc/services/endpoints/cloud) is not exist, will watch after 5s
E0625 13:20:56.853414   70865 app/server.go:78] new iam client, err: no iam address
no iam address
E0625 13:20:56.853809   70865 auth_server/auth.go:50] process stopped by no iam address
