### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by westbullman** [TencentBlueKing/bk-cmdb#7098]
问题描述
zg@zgdeMacBook-Pro v3.10.x % ./start.sh 
starting: cmdb_adminserver
starting: cmdb_apiserver
starting: cmdb_authserver
starting: cmdb_cacheservice
starting: cmdb_cloudserver
starting: cmdb_coreservice
starting: cmdb_datacollection
starting: cmdb_eventserver
starting: cmdb_hostserver
starting: cmdb_operationserver
starting: cmdb_procserver
starting: cmdb_taskserver
starting: cmdb_toposerver
starting: cmdb_webserver
  501 60814     1   0 11:28上午 ttys000    1:14.44 ./cmdb_adminserver --addrport=10.16.25.33:60004 --logtostderr=false --log-dir=./logs --v=3 --config=configures/migrate.yaml --enable-auth=false
  501 60826     1   0 11:28上午 ttys000    0:59.72 ./cmdb_apiserver --addrport=10.16.25.33:8080 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
  501 60875     1   0 11:28上午 ttys000    1:01.31 ./cmdb_coreservice --addrport=10.16.25.33:50009 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
  501 60899     1   0 11:28上午 ttys000    0:58.50 ./cmdb_eventserver --addrport=10.16.25.33:60009 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
  501 60912     1   0 11:28上午 ttys000    0:59.10 ./cmdb_hostserver --addrport=10.16.25.33:60001 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
  501 60924     1   0 11:28上午 ttys000    1:00.06 ./cmdb_operationserver --addrport=10.16.25.33:60011 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
  501 60936     1   0 11:28上午 ttys000    1:01.77 ./cmdb_procserver --addrport=10.16.25.33:60003 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
  501 60948     1   0 11:28上午 ttys000    0:59.44 ./cmdb_taskserver --addrport=10.16.25.33:60012 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
  501 60960     1   0 11:28上午 ttys000    0:56.10 ./cmdb_toposerver --addrport=10.16.25.33:60002 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
  501 60973     1   0 11:28上午 ttys000    1:01.52 ./cmdb_webserver --addrport=10.16.25.33:8083 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
  501 74550     1   0  1:54下午 ttys000    0:02.45 ./cmdb_datacollection --addrport=10.16.25.33:60005 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false
  501 75130     1   0  2:01下午 ttys000    0:00.09 ./cmdb_cacheservice --addrport=10.16.25.33:50010 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181
  501 75141     1   0  2:01下午 ttys000    0:00.08 ./cmdb_cloudserver --addrport=10.16.25.33:60013 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=127.0.0.1:2181 --enable-auth=false --enable_cryptor=false
process count should be: 12 , now:       13
Not Running: cmdb_authserver

然后我看日志是：
begin to discover by watch children of path(/cc/services/endpoints/auth)
begin to discover by watch children of path(/cc/services/endpoints/coreservice)
begin to discover by watch children of path(/cc/services/endpoints/task)
begin to discover by watch children of path(/cc/services/endpoints/eventserver)
begin to discover by watch children of path(/cc/services/endpoints/operation)
begin to discover by watch children of path(/cc/services/endpoints/cacheservice)
begin to discover by watch children of path(/cc/services/endpoints/migrate)
begin to discover by watch children of path(/cc/services/endpoints/cloud)
begin to discover by watch children of path(/cc/services/endpoints/topo)
begin to discover by watch children of path(/cc/services/endpoints/apiserver)
begin to discover by watch children of path(/cc/services/endpoints/host)
begin to discover by watch children of path(/cc/services/endpoints/datacollection)
begin to discover by watch children of path(/cc/services/endpoints/proc)
fail to watch children for path(/cc/services/endpoints/auth), err:zk: node does not exist
children node(/cc/services/endpoints/auth) is not exist, will watch after 5s
children node(/cc/services/endpoints/auth) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/cacheservice), err:zk: node does not exist
children node(/cc/services/endpoints/cacheservice) is not exist, will watch after 5s
children node(/cc/services/endpoints/cloud) is not exist, will watch after 5s
children node(/cc/services/endpoints/cacheservice) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/cloud), err:zk: node does not exist
children node(/cc/services/endpoints/cloud) is not exist, will watch after 5s
fail to watch children for path(/cc/services/endpoints/datacollection), err:zk: node does not exist
children node(/cc/services/endpoints/datacollection) is not exist, will watch after 5s
children node(/cc/services/endpoints/datacollection) is not exist, will watch after 5s
E0625 14:01:12.343216   75119 app/server.go:78] new iam client, err: no iam address
no iam address
E0625 14:01:12.345385   75119 auth_server/auth.go:50] process stopped by no iam address

我看我zk部署的没问题啊，端口都起来了，不过是docker部署的，有关系吗？我看文档上是否的参数都没填
起不来，很难受，都搞了好久了 呜呜呜

**Comment by bd-xiaowang** [comment]
好像没有失败呀，是因为”Not Running: cmdb_authserver“这个服务吗，cmdb_authserver服务依赖其它平台所以启动失败是正常的
