### ISSUE TITLE
无法访问

### ISSUE THREAD

**Issue by westbullman** [TencentBlueKing/bk-cmdb#7113]
问题描述
启动正常，init_db也成功了，但是不能访问！

zg@zgdeMacBook-Pro v3.10.x % ./start.sh         
starting: cmdb_adminserver
starting: cmdb_apiserver
starting: cmdb_authserver
starting: cmdb_cacheservice
starting: cmdb_cloudserver
starting: cmdb_coreservice
starting: cmdb_datacollection
starting: cmdb_eventserver
starting: cmdb_hostserver
starting: cmdb_operationserver
starting: cmdb_procserver
starting: cmdb_taskserver
starting: cmdb_toposerver
starting: cmdb_webserver
  501 40326     1   0  7:23下午 ttys000    0:00.14 ./cmdb_adminserver --addrport=10.16.25.33:60004 --logtostderr=false --log-dir=./logs --v=3 --config=configures/migrate.yaml --enable-auth=false --register-ip=127.0.0.1
  501 40337     1   0  7:23下午 ttys000    0:00.09 ./cmdb_apiserver --addrport=10.16.25.33:8080 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=10.0.44.233:2181 --enable-auth=false --register-ip=127.0.0.1
  501 40359     1   0  7:23下午 ttys000    0:00.25 ./cmdb_cacheservice --addrport=10.16.25.33:50010 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=10.0.44.233:2181 --register-ip=127.0.0.1
  501 40371     1   0  7:23下午 ttys000    0:00.11 ./cmdb_cloudserver --addrport=10.16.25.33:60013 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=10.0.44.233:2181 --enable-auth=false --enable_cryptor=false --register-ip=127.0.0.1
  501 40382     1   0  7:23下午 ttys000    0:00.12 ./cmdb_coreservice --addrport=10.16.25.33:50009 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=10.0.44.233:2181 --register-ip=127.0.0.1
  501 40396     1   0  7:23下午 ttys000    0:00.10 ./cmdb_datacollection --addrport=10.16.25.33:60005 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=10.0.44.233:2181 --enable-auth=false --register-ip=127.0.0.1
  501 40407     1   0  7:23下午 ttys000    0:00.11 ./cmdb_eventserver --addrport=10.16.25.33:60009 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=10.0.44.233:2181 --enable-auth=false --register-ip=127.0.0.1
  501 40418     1   0  7:23下午 ttys000    0:00.09 ./cmdb_hostserver --addrport=10.16.25.33:60001 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=10.0.44.233:2181 --enable-auth=false --register-ip=127.0.0.1
  501 40429     1   0  7:23下午 ttys000    0:00.09 ./cmdb_operationserver --addrport=10.16.25.33:60011 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=10.0.44.233:2181 --enable-auth=false --register-ip=127.0.0.1
  501 40440     1   0  7:23下午 ttys000    0:00.09 ./cmdb_procserver --addrport=10.16.25.33:60003 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=10.0.44.233:2181 --enable-auth=false --register-ip=127.0.0.1
  501 40451     1   0  7:23下午 ttys000    0:00.10 ./cmdb_taskserver --addrport=10.16.25.33:60012 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=10.0.44.233:2181 --register-ip=127.0.0.1
  501 40462     1   0  7:23下午 ttys000    0:00.10 ./cmdb_toposerver --addrport=10.16.25.33:60002 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=10.0.44.233:2181 --enable-auth=false --register-ip=127.0.0.1
  501 40473     1   0  7:23下午 ttys000    0:00.00 ./cmdb_webserver --addrport=10.16.25.33:8083 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=10.0.44.233:2181 --register-ip=127.0.0.1
process count should be: 12 , now:       13
Not Running: cmdb_authserver
zg@zgdeMacBook-Pro v3.10.x % ps -ef | grep 8083 
  501 40473     1   0  7:23下午 ttys000    0:00.11 ./cmdb_webserver --addrport=10.16.25.33:8083 --logtostderr=false --log-dir=./logs --v=3 --regdiscv=10.0.44.233:2181 --register-ip=127.0.0.1

**Comment by westbullman** [comment]
坑啊，要在端口后面加/login，输入用户名密码不能重定向到index页面，怎么配置？

**Comment by bd-xiaowang** [comment]
生成配置文件后找到配置文件目录的`cmdb_adminserver/configures/common.yaml`配置文件，修改以下两项为您的主机ip：
![访问ip修改](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/451e4216-a7f8-4687-ba30-330b2d37c520)

**Comment by bd-xiaowang** [comment]
生成配置文件后找到配置文件目录的`cmdb_adminserver/configures/common.yaml`配置文件，修改以下两项为您的主机ip：
![访问ip修改](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/451e4216-a7f8-4687-ba30-330b2d37c520)

**Comment by bd-xiaowang** [comment]
然后再重启服务

**Comment by bd-xiaowang** [comment]
生成配置文件后找到配置文件目录的cmdb_adminserver/configures/common.yaml配置文件，修改以下两项为您的主机ip：
![访问ip修改](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/2f723383-9e45-4806-8fff-d31a3729035d)
然后再重启服务
