### ISSUE TITLE
安装开源cmdb时出现的问题

### ISSUE THREAD

**Issue by alanChenJB** [TencentBlueKing/bk-cmdb#7171]
问题描述
===========
按照以下文章 https://github.com/TencentBlueKing/bk-cmdb/blob/master/docs/overview/upgrade-from-ce.md 尝试安装开源的cmdb来替代社区版cmdb时，出现报错。
社区版的cmdb版本为v3.10.21
我下载的版本为v3.10.22
下载解压后，执行 GITHASH=${release} GITTAG=ocr-${release} VERSION=${release} make
出现npm的报错如下：

building web... 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: bk-cmdb-ui@1.0.0
npm ERR! Found: vue@2.7.14
npm ERR! node_modules/vue
npm ERR!   vue@"^2.7.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR! node_modules/@vue/composition-api
npm ERR!   @vue/composition-api@"^1.6.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /root/.npm/_logs/2023-07-04T07_00_29_048Z-eresolve-report.txt

应该是vue版本不对，我可以如何去调整？

**Comment by yangyy** [comment]
请参考 #7052 解决
