### ISSUE TITLE
3.10.18版本，前端编译npm install 能成功。 npm run build 失败。

### ISSUE THREAD

**Issue by dujiaoyang** [TencentBlueKing/bk-cmdb#7190]
问题描述
===========

前端编译npm install 能成功。
npm run build 失败。

node 版本 v14.17.0

npm 版本  6.14.13

蓝鲸版本：v3.10.18
windows 10系统
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/13164583/18c99fc9-729c-405e-913d-f6f360636f6a)

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
     ╷
1374 │       background-color: $ghostBackgroundColor !important;
     │                         ^^^^^^^^^^^^^^^^^^^^^
     ╵
  src\components\model-manage\field-group\index.vue 1374:25  root stylesheet
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/13164583/16273e41-ed14-45c1-8a4a-ecde947772d9)

重现方法
================

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by yangyy** [comment]
请参考 #7074 解决

**Comment by dujiaoyang** [comment]
可以了，谢谢

**Comment by dujiaoyang** [comment]
> 请参考 #7074 解决

可以了，谢谢
