### ISSUE TITLE
3.10.26版本，前端编译报错

### ISSUE THREAD

**Issue by xiaopan327** [TencentBlueKing/bk-cmdb#7194]
问题描述
===========

编译前端时提示
Duplicated key 'readonly'
ui/src/components/ui/form/organization.vue:95:9
重现方法
================

make NPM=cnpm ui

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by yangyy** [comment]
请升级至v3.10.26以上版本，或者参考 43512fc966b7d23dca3918a7581603614299dd93 解决
