### ISSUE TITLE
开源cmdb v3.10.23编译时出现以下报错

### ISSUE THREAD

**Issue by alanChenJB** [TencentBlueKing/bk-cmdb#7196]
问题描述
===========
执行make后，到fibers时报以下超时错误

npm ERR! code 127
npm ERR! path /tmp1/src/configcenter/src/ui/node_modules/fibers
npm ERR! command failed
npm ERR! command sh -c -- node build.js || nodejs build.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.18.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.6.13 found at "/opt/py36/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.18.1/node-v16.18.1-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v16.18.1/node-v16.18.1-headers.tar.gz failed, reason: connect ETIMEDOUT 104.20.23.46:443
npm ERR! gyp ERR! stack     at ClientRequest.<anonymous> (/usr/local/nodejs/node-v16.18.1-linux-x64/lib/node_modules/npm/node_modules/minipass-fetch/lib/index.js:130:14)
npm ERR! gyp ERR! stack     at ClientRequest.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:494:9)
npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:525:35)
npm ERR! gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR! gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Linux 3.10.0-1160.el7.x86_64
npm ERR! gyp ERR! command "/usr/local/nodejs/node-v16.18.1-linux-x64/bin/node" "/usr/local/nodejs/node-v16.18.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /tmp1/src/configcenter/src/ui/node_modules/fibers
npm ERR! gyp ERR! node -v v16.18.1
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok 
npm ERR! node-gyp exited with code: 1
npm ERR! Please make sure you are using a supported platform and node version. If you
npm ERR! would like to compile fibers on this machine please make sure you have setup your
npm ERR! build environment--
npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
npm ERR! Alpine users please run: `sudo apk add python make g++`
npm ERR! sh: nodejs: 未找到命令

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-11T08_12_20_709Z-debug-0.log

**Comment by dujiaoyang** [comment]
试试容器部署，拉个node14的容器，然后把ui目录复制进容器，再编译。
