### ISSUE TITLE
v3.10.27执行init_db失败

### ISSUE THREAD

**Issue by xiaopan327** [TencentBlueKing/bk-cmdb#7197]
问题描述
===========

部署完成，启动服务后执行init_db.sh 报错如下
{"result":false,"bk_error_code":1105000,"bk_error_msg":"迁移数据失败, server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [] }","permission":null,"data":null}

重现方法
================
./init_db.sh

关键信息
=========
mongodb已使用rs模式
rs.conf()信息如下

{
	"_id" : "single",
	"version" : 1,
	"protocolVersion" : NumberLong(1),
	"writeConcernMajorityJournalDefault" : true,
	"members" : [
		{
			"_id" : 0,
			"host" : "192.168.215.176:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				
			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		}
	],
	"settings" : {
		"chainingAllowed" : true,
		"heartbeatIntervalMillis" : 2000,
		"heartbeatTimeoutSecs" : 10,
		"electionTimeoutMillis" : 10000,
		"catchUpTimeoutMillis" : -1,
		"catchUpTakeoverDelayMillis" : 30000,
		"getLastErrorModes" : {
			
		},
		"getLastErrorDefaults" : {
			"w" : 1,
			"wtimeout" : 0
		},
		"replicaSetId" : ObjectId("64acff5b1f3ee32e431d5eb5")
	}
}

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by xiaopan327** [comment]
已解决，rsName和配置文件里的不一致造成的

**Comment by yuan-0708** [comment]
您好，这个怎么更改呢？

**Comment by bd-xiaowang** [comment]
> 
![mongodb配置](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/bc3ff1f8-c009-420c-ae6d-43002837f12b)
配置文件在`src/bin/build/v3.11.1/cmdb_adminserver/configures/mongodb.yaml`，请按照您的mongodb实际配置进行更改
