### ISSUE TITLE
开源版cmdb3.10.27替换3.10.21时，执行init_db.sh 脚本用来升级数据库报错

### ISSUE THREAD

**Issue by Ai-MaShi** [TencentBlueKing/bk-cmdb#7216]
问题描述
===========
执行 curl -X POST -H 'Content-Type:application/json' -H 'BK_USER:migrate' -H 'HTTP_BLUEKING_SUPPLIER_ID:0' http://${adminserver}:60004/migrate/v3/migrate/community/0  或者 sh init_db.sh的时候报错
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/69375800/ee0b299b-7d20-469f-8abd-515f6608e731)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/69375800/478325ab-8a4f-4417-afbf-5c11665904e4)

重现方法
================
cd /tmp/tmp1/src/configcenter/src/bin/build/v3.10.27
 sh init_db.sh

关键信息
=========
使用3.10.27替换3.10.21代码后，执行数据库 migrate报错。
sh init_db.sh

请提供以下信息:

[root@vcomyw-bk03 bin]# ./cmdb_adminserver  --version
Version     : v3.10.27
Tag         : ocr-v3.10.27
BuildTime   : 2023-07-13T16:15:22+0800
GitHash     : v3.10.27
RunMode     : product
Distribution: community
ServiceName : migrate
GoVersion   : go1.20.5

**Comment by bd-xiaowang** [comment]
![initdb报错](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/34a3d917-1dcc-44fd-920e-0fc08d52eb98)
看您的60004端口运行好像并不是`cmdb_adminserver`服务，是否是这个原因？查看cmdb_adminserver下的日志文件是否有输出，如果没有很大可能就是因为`cmdb_adminserver`启动的端口错误，脚本未能访问到该服务；

**Comment by bd-xiaowang** [comment]
如果不是上述原因，日志文件有输出报错信息，请提供相应报错信息
