### ISSUE TITLE
安装CMDB时，初始化数据库报错“迁移数据失败”

### ISSUE THREAD

**Issue by duk-ops** [TencentBlueKing/bk-cmdb#7270]
问题描述
===========
安装CMDB时，执行init_db.sh 报错“迁移数据失败”
{"result":false,"bk_error_code":1105000,"bk_error_msg":"迁移数据失败, server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [] }","permission":null,"data":null}

关键信息
=========
 - [x] bk-cmdb   版本: v3.10.31

-->
 - [x] Redis     版本: 5.5.0
 - [ ] MongoDB   版本: 4.2.0
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : <!-- `示例： Centos7

**Comment by yuan-0708** [comment]
我也碰到这个问题，你解决了吗？

**Comment by duk-ops** [comment]
> 我也研究了这个问题，你解决了吗？
已经解决，我的报错原因是自己安装的mongodb配置文件使用的默认的分片名称，但是安装包中提供的迁移配置指定了分片名称为rs0，所以在mongo的配置文件中添加一下分片名称配置就解决了

**Comment by zhucaipeng** [comment]
想问下，如何设置啊？ "在mongo的配置文件中添加一下分片名称配置"

**Comment by yuan-0708** [comment]
想问下，怎么设置啊？ "在mongo的配置文件中添加一下分片名称配置"

**Comment by duk-ops** [comment]
mongo配置文件中找到replication
replication:
   replSetName: rs0
就可以了

**Comment by bd-xiaowang** [comment]
1、检查cmdb_adminserver/configures/mongodb.yaml下的配置信息是否准确，检查MongoDB配置是否与配置文件对应
![mongodb配置](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/16ec3fc6-cf9d-4f1e-82c6-8d1e7c746311)
2、如果您使用了MongoDB的分片集群（Replica Set）或分片（Sharding）功能，请确保集群配置正确，主节点正常工作，并且副本集成员也正常运行
3、参考编译部署文档：https://github.com/TencentBlueKing/bk-cmdb/pull/7352，其它mongodb报错请提供日志文件
