### ISSUE TITLE
【CMDB+v3.11.1-alpha1】绑定的模型下输入“\ ?”字符会报查询数据失败的错误

### ISSUE THREAD

**Issue by testqwerts** [TencentBlueKing/bk-cmdb#7317]
问题描述：
绑定的模型下输入“\ ?”字符会报查询数据失败的错误
一，前置条件：
组合模板下存在多个模型，早模板详情页面

二，操作步骤：
1.点击绑定的模型
2.搜索框输入“\ ?”字符
三，预期结果：
按照搜索为空规范设计

四，实际结果：
会报查询数据失败的错误
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/685474e0-ef77-4b26-a056-4732b12a0dff)

**Comment by wcy00000000000000** [comment]
@yangyy 这个是因为前端contains传的不是正则表达式，需要按照高级搜索里contains条件的方式传参
