### ISSUE TITLE
cmdb源码v3.11.1版本单机部署数据库初始化失败

### ISSUE THREAD

**Issue by yuan-0708** [TencentBlueKing/bk-cmdb#7347]
问题描述
cmdb源码v3.11.1版本单机部署数据库初始化失败，自己编译的。
package success and store in /tmp/tmp5/src/configcenter/src/bin/pub/cmdb.tar.gz
[root@oracledb src]# cd bin/pub/
[root@oracledb pub]# ll
total 294828
drwxr-xr-x 3 root root        21 Aug  9 10:35 cmdb
-rw-r--r-- 1 root root 301901344 Aug  9 10:36 cmdb.tar.gz
[root@oracledb pub]# ll cmdb
total 4
drwxr-xr-x 22 root root 4096 Aug  9 10:35 v3.11.1
[root@oracledb pub]# ll cmdb
cmdb/        cmdb.tar.gz  
[root@oracledb pub]# ll cmdb/v3.11.1/
changelog_user/         cmdb_cloudserver/       cmdb_operationserver/   cmdb_webserver/         ip.py                   stop.sh
cmdb_adminserver/       cmdb_coreservice/       cmdb_procserver/        docker/                 monstache/              tool_ctl/
cmdb_apiserver/         cmdb_datacollection/    cmdb_synchronizeserver/ image.sh                refresh_config.sh       upgrade.sh
cmdb_authserver/        cmdb_eventserver/       cmdb_taskserver/        init_db.sh              restart.sh              web/
cmdb_cacheservice/      cmdb_hostserver/        cmdb_toposerver/        init.py                 start.sh                
[root@oracledb pub]# ll cmdb/v3.11.1/
total 76
drwxr-xr-x 4 root root    26 Aug  9 10:35 changelog_user
drwxr-xr-x 3 root root   172 Aug  9 10:35 cmdb_adminserver
drwxr-xr-x 3 root root   170 Aug  9 10:35 cmdb_apiserver
drwxr-xr-x 3 root root   171 Aug  9 10:35 cmdb_authserver
drwxr-xr-x 3 root root   173 Aug  9 10:35 cmdb_cacheservice
drwxr-xr-x 3 root root   172 Aug  9 10:35 cmdb_cloudserver
drwxr-xr-x 3 root root   172 Aug  9 10:35 cmdb_coreservice
drwxr-xr-x 3 root root   175 Aug  9 10:35 cmdb_datacollection
drwxr-xr-x 3 root root   172 Aug  9 10:35 cmdb_eventserver
drwxr-xr-x 3 root root   171 Aug  9 10:35 cmdb_hostserver
drwxr-xr-x 3 root root   176 Aug  9 10:35 cmdb_operationserver
drwxr-xr-x 3 root root   171 Aug  9 10:35 cmdb_procserver
drwxr-xr-x 3 root root   178 Aug  9 10:35 cmdb_synchronizeserver
drwxr-xr-x 3 root root   171 Aug  9 10:35 cmdb_taskserver
drwxr-xr-x 3 root root   171 Aug  9 10:35 cmdb_toposerver
drwxr-xr-x 3 root root   170 Aug  9 10:35 cmdb_webserver
drwxr-xr-x 2 root root  4096 Aug  9 10:35 docker
-rwxr--r-- 1 root root   913 Aug  9 10:35 image.sh
-rwxr-xr-x 1 root root   372 Aug  9 10:35 init_db.sh
-rwxr-xr-x 1 root root 37868 Aug  9 10:35 init.py
-rwxr--r-- 1 root root   211 Aug  9 10:35 ip.py
drwxr-xr-x 3 root root    74 Aug  9 10:35 monstache
-rwxr-xr-x 1 root root   945 Aug  9 10:35 refresh_config.sh
-rwxr-xr-x 1 root root    34 Aug  9 10:35 restart.sh
-rwxr-xr-x 1 root root  1231 Aug  9 10:35 start.sh
-rwxr-xr-x 1 root root   810 Aug  9 10:35 stop.sh
drwxr-xr-x 2 root root    22 Aug  9 10:35 tool_ctl
-rwxr-xr-x 1 root root  2144 Aug  9 10:35 upgrade.sh
drwxr-xr-x 7 root root   175 Aug  9 10:35 web
部署后查看进程：
[root@10-100-12-49 v3.11.1]# ps aux|grep cmdb|wc -l
14
[root@10-100-12-49 v3.11.1]# 
[root@10-100-12-49 v3.11.1]# ./init_db.sh 
localIp:10.100.12.49
{"result":false,"bk_error_code":1105000,"bk_error_msg":"迁移数据失败, server selection error: server selection timeout, current topology: { Type: ReplicaSetNoPrimary, Servers: [] }","permission":null,"data":null}
[root@10-100-12-49 v3.11.1]# 

cmdb-v3.11.1
redis-3.2.11
zookeeper-3.4.12
mongodb-4.0.28

**Comment by bd-xiaowang** [comment]
看样子并不是程序或脚本的问题。
1、检查cmdb_adminserver/configures/mongodb.yaml下的配置信息是否准确，检查MongoDB配置是否与配置文件对应
![mongodb配置](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/31613834-85a5-4650-9d11-4cb72be105e6)
2、如果您使用了MongoDB的分片集群（Replica Set）或分片（Sharding）功能，请确保集群配置正确，主节点正常工作，并且副本集成员也正常运行
3、参考编译部署文档：https://github.com/TencentBlueKing/bk-cmdb/pull/7352，其它mongodb报错请提供日志文件

**Comment by bd-xiaowang** [comment]
CMDB最新编译部署文档：https://github.com/TencentBlueKing/bk-cmdb/tree/v3.11.x/docs/overview
