### ISSUE TITLE
【3.11.1】枚举引用类型在模型中无法使用

### ISSUE THREAD

**Issue by yyf365** [TencentBlueKing/bk-cmdb#7356]
问题描述
===========
枚举引用类型在模型创建字段时无法选择，在备选类型中不存在，无法使用版本中包含的`枚举(引用)`类型

重现方法
================
1、升级到3.11.1代码，重新编译打包后启动服务。
2、无论是在全新的环境和数据库，还是接续使用原有数据库都无法使用枚举（引用类型）

<img width="1439" alt="image" src="https://github.com/TencentBlueKing/bk-cmdb/assets/12697067/ca32c0ad-8dcf-4149-bf05-7a00ff41c68c">

查看提交历史和代码里是有这个PR的合并记录的，也无法使用该类型
Merge pull request #7234 from yangyy/fix-disallow-create-enumquote

<img width="644" alt="image" src="https://github.com/TencentBlueKing/bk-cmdb/assets/12697067/60c3abfe-ef26-4bbb-8dc1-218fe2c41b3b">

关键信息
=========
 - [ ] CMDB     版本: `3.11.1` 
 - [ ] Redis     版本: `6.2.7`
 - [ ] MongoDB   版本: `4.2.22`
 - [ ] ZooKeeper 版本: `3.4.12`
 - [ ] 操作系统      : `macOS 12.6.7`
 - [x] bk-cmdb 异常日志：`无`

**Comment by yyf365** [comment]
另外查看提交历史和代码里是有这个PR的合并记录的

**Comment by bd-xiaowang** [comment]
问题的确存在，已反馈

**Comment by reggieisrunning** [comment]
Hi，@yyf365
感谢您对蓝鲸配置平台项目的关注。关于枚举引用功能其设计存在缺陷，在项目内部验收未通过。在历史版本中我们失误放出了该功能，但为了确保产品质量和用户体验，我们在后续版本中对其进行了屏蔽。
为了避免可能的问题，我们建议您暂时不要使用此功能。我们已经规划在今年下半年推出全新的“关联字段”功能来替代枚举引用，届时您便可以体验到更加完善的功能。
再次感谢您的理解与支持！
