### ISSUE TITLE
在线体验网站证书过期了

### ISSUE THREAD

**Issue by FOWind** [TencentBlueKing/bk-cmdb#7364]
问题描述
===========

在线体验网站证书过期了

<img width="590" alt="image" src="https://github.com/TencentBlueKing/bk-cmdb/assets/13653453/f782b5da-3d57-4699-b989-5e2888dcad5f">

重现方法
================

https://cmdb-exp.bktencent.com/start

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 
 
 - [ ] Redis     版本: 
 - [ ] MongoDB   版本: 
 - [ ] ZooKeeper 版本: 
 - [ ] 操作系统      : 
 - [ ] bk-cmdb 异常日志

**Comment by bd-xiaowang** [comment]
![在线体验页面](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/a862201c-75e9-4369-99e6-db32dea36439)
页面打开正常

**Comment by bd-xiaowang** [comment]
页面打开正常
![在线体验页面](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/e4b86387-acd8-4ef3-9980-b53d40fa55ef)

**Comment by FOWind** [comment]
证书还是过期啊
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/13653453/7425b247-2c47-41df-b9fa-d5ee70960fc7)
