### ISSUE TITLE
【CMDB+3.11.2-alpha1】导出模型字段后Excel表格后方会出现随机字符，用导出的Excel修改字段信息后报"获取文件内容失败 [sheet GG does not exist]"的错误

### ISSUE THREAD

**Issue by testqwerts** [TencentBlueKing/bk-cmdb#7384]
问题描述：
导出模型字段后Excel表格后方会出现随机字符，用导出的Excel修改字段信息后报"获取文件内容失败 [sheet GG does not exist]"的错误
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/0df39159-4ca1-42ec-bb16-9d38e34d0924)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/923e8795-4ca1-40f9-b0fe-6c3e4090ac77)

一，前置条件：
已导出了模型字段的Excel表格
二，操作步骤：
1.修改对应字段内容信息，保存Excel表格
2.点击导入-->点击上传-->上传修改后的文件

三，预期结果：
导入成功

四，实际结果：
导入时报错
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/6037c276-9411-4303-99a8-0ac0514b1412)

**Comment by ZQHcode** [comment]
后缀是模型的objID，「sheet GG does not exist」是因为里面的sheet不是对应的objID名称
