### ISSUE TITLE
coreserver无法进行负载均衡问题

### ISSUE THREAD

**Issue by HappyBinbin** [TencentBlueKing/bk-cmdb#7427]
问题描述
===========

生产环境，将cmdb各个服务拆分容器化后，进行并发测试时，发现coreserver会重启，查看负载均衡，发现某个pod总是会达到cpu或者内存限制后重启。
查看代码，发现是apimachinery 中，发送http请求时，会轮训存在的host，如果第一个可用则一直使用第一个host进行http请求

重现方法
================

进行大量的并发测试即可复现

具体代源码
================
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/54468133/12465fb4-daf7-47e8-9de2-0515e474c346)

疑问：
================
为什么不做负载均衡？

**Comment by wcy00000000000000** [comment]
cmdb是用Round Robin策略做的负载均衡，每次获取server的时候都会往后轮询的。截图中的hosts是通过`r.capability.Discover.GetServers()`方法获取的，实现代码如下：https://github.com/TencentBlueKing/bk-cmdb/blob/v3.12.x/src/apimachinery/discovery/server.go#L55
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/40779709/94073574-1d83-42ab-a5e8-2c597e16b477)

**Comment by HappyBinbin** [comment]
抱歉，我没有说明版本信息；
我们是采用的是比较低版本的bk-cmdb，例如v3.2.x，其轮训算法如下：
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/54468133/08fc4cd9-0db6-413d-9657-d70f5b79be2a)
当只有三个server运行时，就会导致负载不均衡的问题，通过单测可以看出来：
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/54468133/f8dbc049-247e-4215-a666-7831fdb31603)
具体的原因，低版本在获取servers时，没有使用新的infos变量，而是采用原本的servers来进行切片，就会导致其本身顺序被重新排列，从而出现，以下的规律（列举两次RR轮询）：
1,2,3
2,3,1
1,2,3
-------
1,2,3
2,3,1
1,2,3
在三个server进行RR轮询时，第三个sever永远不会有机会被访问到，而第一个服务器被访问的到概率为2/3，出现负载不均衡的情况；高版本因为使用infos作为变量进行切片，所以不会有该问题

**Comment by HappyBinbin** [comment]
> cmdb是用Round Robin策略做的负载均衡，每次获取server的时候都会往后轮询的。截图中的hosts是通过`r.capability.Discover.GetServers()`方法获取的，实现代码如下：https://github.com/TencentBlueKing/bk-cmdb/blob/v3.12.x/src/apimachinery/discovery/server.go#L55 ![image](https://user-images.githubusercontent.com/40779709/271235182-94073574-1d83-42ab-a5e8-2c597e16b477.png)

抱歉，我没说明版本信息，我们采用的是bk-cmdb较低版本，例如：v.3.2.x，其轮询算法如下：

![image](https://github.com/TencentBlueKing/bk-cmdb/assets/54468133/1599efaa-f36a-4789-92f5-6188ad12ff7a)

在只有三个节点时，会出现负载不均衡的情况，通过单测亦可看出：

![image](https://github.com/TencentBlueKing/bk-cmdb/assets/54468133/30fc417a-cb8d-4047-9629-7b9548ae37cd)

究其原因，低版本的轮询算法，在进行servers切片时，是用本身 s.servers 变量进行切片，从而重新排列的，当只有三个节点时，就会出现以下的情况（列举两次轮询结果）：

1,2,3
2,3,1
1,2,3

1,2,3
2,3,1
1,2,3

第三个节点永远不会被访问到，而第一个节点被访问到的概率为 2/3，从而出现负载不均衡的情况；

解决方案：
进行切片时，将index-1改为index即可

![image](https://github.com/TencentBlueKing/bk-cmdb/assets/54468133/21b9b84d-dc5a-48a9-adce-a43f2e29247c)

**Comment by bd-xiaowang** [comment]
> 采用的是bk-cmdb较低版本，例如：v.3.2.x，其轮询算法如下
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/77056ce0-950a-4a7e-b4c6-5a951dd566e0)
你好，使用v3.2.x，测试用例与测试结果如下：
![联想截图_20231019120408](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/779b417d-23bc-4a4f-8080-6d6d5745080b)
在只有三个节点时，未重现负载不均衡的情况
