### ISSUE TITLE
synchronize_server中的同步功能在3.11.1版本中实际可行吗，运行实际代码报错

### ISSUE THREAD

**Issue by fuhaifei1993** [TencentBlueKing/bk-cmdb#7430]
问题描述
===========

运行synchronize_server中的synchronize.go
会报错logics/synchronize.go:36] TriggerSynchronize not config
读取配置的代码是否需要自己添加呢？

关键信息
=========

请提供以下信息:

 - [x] bk-cmdb   版本: 

Branch   : v3.11.1
 -->

 - [ ] bk-cmdb 异常日志
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1009 06:28:13.670170   12227 util/flags.go:54] [auth] enableAuth: true
I1009 06:28:13.686520   12227 log/log.go:184] connected to 127.0.0.1:2181
I1009 06:28:13.710391   12227 log/log.go:184] authenticated: id=72786326910468141, timeout=40000
I1009 06:28:13.710756   12227 log/log.go:184] re-submitting `0` credentials after reconnect
I1009 06:28:13.721018   12227 discovery/server.go:101] start to discover cc component from zk, path:[/cc/services/endpoints/task].
I1009 06:28:13.721046   12227 discovery/server.go:101] start to discover cc component from zk, path:[/cc/services/endpoints/eventserver].
I1009 06:28:13.721060   12227 discovery/server.go:101] start to discover cc component from zk, path:[/cc/services/endpoints/coreservice].
I1009 06:28:13.721074   12227 discovery/server.go:101] start to discover cc component from zk, path:[/cc/services/endpoints/cloud].
I1009 06:28:13.721128   12227 discovery/server.go:101] start to discover cc component from zk, path:[/cc/services/endpoints/apiserver].
I1009 06:28:13.721162   12227 discovery/server.go:101] start to discover cc component from zk, path:[/cc/services/endpoints/migrate].
I1009 06:28:13.721188   12227 discovery/server.go:101] start to discover cc component from zk, path:[/cc/services/endpoints/topo].
I1009 06:28:13.721207   12227 discovery/server.go:101] start to discover cc component from zk, path:[/cc/services/endpoints/host].
I1009 06:28:13.721220   12227 discovery/server.go:101] start to discover cc component from zk, path:[/cc/services/endpoints/sync].
I1009 06:28:13.721234   12227 discovery/server.go:101] start to discover cc component from zk, path:[/cc/services/endpoints/operation].
I1009 06:28:13.721246   12227 discovery/server.go:101] start to discover cc component from zk, path:[/cc/services/endpoints/proc].
I1009 06:28:13.721264   12227 discovery/server.go:101] start to discover cc component from zk, path:[/cc/services/endpoints/auth].
I1009 06:28:13.721277   12227 discovery/server.go:101] start to discover cc component from zk, path:[/cc/services/endpoints/cacheservice].
I1009 06:28:13.721289   12227 discovery/server.go:101] start to discover cc component from zk, path:[/cc/services/endpoints/datacollection].
I1009 06:28:13.721445   12227 configcenter/cc.go:287] start sync config from config center.
W1009 06:28:13.730883   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/cacheservice.
W1009 06:28:13.742366   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/migrate.
W1009 06:28:13.742476   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/topo.
W1009 06:28:13.742899   12227 discovery/server.go:111] get zk event with 0 instance with path[/cc/services/endpoints/topo], reset its servers
W1009 06:28:13.743085   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/host.
W1009 06:28:13.743090   12227 discovery/server.go:111] get zk event with 0 instance with path[/cc/services/endpoints/host], reset its servers
W1009 06:28:13.743104   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/apiserver.
W1009 06:28:13.743569   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/operation.
W1009 06:28:13.743579   12227 discovery/server.go:111] get zk event with 0 instance with path[/cc/services/endpoints/operation], reset its servers
W1009 06:28:13.743599   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/proc.
W1009 06:28:13.743613   12227 discovery/server.go:111] get zk event with 0 instance with path[/cc/services/endpoints/proc], reset its servers
W1009 06:28:13.743634   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/auth.
W1009 06:28:13.743637   12227 discovery/server.go:111] get zk event with 0 instance with path[/cc/services/endpoints/auth], reset its servers
W1009 06:28:13.743648   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/datacollection.
W1009 06:28:13.743651   12227 discovery/server.go:111] get zk event with 0 instance with path[/cc/services/endpoints/datacollection], reset its servers
W1009 06:28:13.743842   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/apiserver.
W1009 06:28:13.743930   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/cloud.
W1009 06:28:13.743964   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/task.
W1009 06:28:13.753897   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/cacheservice.
W1009 06:28:13.754024   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/coreservice.
W1009 06:28:13.754056   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/sync.
W1009 06:28:13.754060   12227 discovery/server.go:111] get zk event with 0 instance with path[/cc/services/endpoints/sync], reset its servers
W1009 06:28:13.754067   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/eventserver.
I1009 06:28:13.760823   12227 backbone/backbone.go:325] load new language config success.
I1009 06:28:13.762035   12227 backbone/backbone.go:337] load new error config success.
W1009 06:28:13.762075   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/coreservice.
W1009 06:28:13.762106   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/cloud.
E1009 06:28:13.876744   12227 logics/synchronize.go:36] TriggerSynchronize not config
I1009 06:28:13.880988   12227 backbone/http.go:70] start insecure server on 172.17.0.2:60010
E1009 06:28:13.883307   12227 backbone/notice.go:57] log watch failed, will watch after 10s, path: /cc/services/notice/log/172.17.0.2:60010/v, err: zk: node does not exist
W1009 06:28:13.920412   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/host.
W1009 06:28:14.423368   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/operation.
W1009 06:28:14.757143   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/operation.
W1009 06:28:14.757211   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/host.
W1009 06:28:14.768149   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/proc.
W1009 06:28:14.776047   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/proc.
I1009 06:28:14.883742   12227 registerdiscover/zkregdiscv.go:53] register server and watch it. path(/cc/services/endpoints/sync/172.17.0.2), data({"ip":"172.17.0.2","port":60010,"registerip":"172.17.0.2","hostname":"9cff6f7cd2ad","scheme":"http","version":"Version     : v3.11.1\nTag         : release-v3.11.1\nBuildTime   : 2023-08-04T22:07:12+0800\nGitHash     : 7581141e8371aba789ee560b143a1e07e86d94ff\nRunMode     : product\nDistribution: enterprise\nServiceName : sync\nGoVersion   : go1.17\n","pid":12227,"uuid":"ckhpqvfl7e1f91ju3g9g"})
I1009 06:28:14.883778   12227 registerdiscover/zkregdiscv.go:116] finish register server node(/cc/services/endpoints/sync/172.17.0.2) and watch it
W1009 06:28:14.958264   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/sync.
W1009 06:28:15.332638   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/task.
W1009 06:28:15.452315   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/datacollection.
W1009 06:28:15.747895   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/task.
W1009 06:28:15.754441   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/datacollection.
W1009 06:28:15.754481   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/sync.
W1009 06:28:15.922959   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/topo.
W1009 06:28:16.782104   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/topo.
W1009 06:37:33.647232   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/sync.
W1009 06:37:34.272885   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/sync.
W1009 06:38:44.865322   12227 discovery/server.go:104] received one zk event from path /cc/services/endpoints/sync.

**Comment by ZQHcode** [comment]
目前这个服务已经没有在维护了哈
