### ISSUE TITLE
这里应该是写错了吧  同步process一直是失败的

### ISSUE THREAD

**Issue by fuhaifei1993** [TencentBlueKing/bk-cmdb#7447]
https://github.com/TencentBlueKing/bk-cmdb/blob/6730f94f1885c5a71777743451724a9e8bc90f27/src/source_controller/coreservice/core/datasynchronize/instance.go#L72

	case common.BKInnerObjIDProc:
		return inst.saveSynchronizeModuleInstance(kit)

**Comment by ZQHcode** [comment]
synchronize_server相关内容已经没有在维护了哈
