### ISSUE TITLE
【CMDB+v3.12.3-alpha1】1.动态分组搜索框条件id应该大写“ID” 2.名称应该为“分组名称” 3.这里的“更新人”与“修改人”的字段没统一 4.建议在搜索框底部也增加对应搜索条件的文案，比如："请选择ID，分组名称，查询对象，更新人进行搜索"

### ISSUE THREAD

**Issue by testqwerts** [TencentBlueKing/bk-cmdb#7492]
问题描述：
1.动态分组搜索框条件id应该大写“ID”
2.名称应该为“分组名称”
3.这里的“更新人”与“修改人”的字段没统一
4.建议在搜索框底部也增加对应搜索条件的文案，比如："请选择ID，分组名称，查询对象，更新人进行搜索"
一，前置条件：
在动态分组页面

二，操作步骤：
1.点击搜索框

四，实际结果：
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/2cb444b1-b15e-4881-90e2-45f8fed397c8)

**Comment by reggieisrunning** [comment]
@zc422 完成建议1、2、3。
4暂时不用
