### ISSUE TITLE
建议log文件有记录上限

### ISSUE THREAD

**Issue by AaronZzzqy** [TencentBlueKing/bk-cmdb#7501]
**用文字描述你遇到的问题**

日志文件经过堆积占用磁盘空间过大

**重现方法**

项目起了30多个小时没停机，日志文件占了我磁盘300g

**预期行为**

仅保存最近一段时间内的日志或日志存到一定大小不再存储

**版本**
开源版v3.10.x

**额外信息**

任何你觉得有助于问题解决的内容

**Comment by wcy00000000000000** [comment]
每个cmdb进程都可以通过命令行参数log_max_size配置单日志文件大小上限（单位MB），和命令行参数log_max_num配置日志文件数上限

**Comment by AaronZzzqy** [comment]
> 每个cmdb进程都可以通过命令行参数log_max_size配置单日志文件大小上限（单位MB），和命令行参数log_max_num配置日志文件数上限

好的，谢谢
