### ISSUE TITLE
v3.12.2 前端版本异常

### ISSUE THREAD

**Issue by workman-Lu** [TencentBlueKing/bk-cmdb#7618]
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/23043492/34beddfe-681a-4526-91d7-f20675a65bc1)

**Comment by workman-Lu** [comment]
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/23043492/527af961-5a16-488b-84e4-4b16ca724c8b)
切回源码还是显示

**Comment by yangyy** [comment]
调用接口 `admin/find/system_config/platform_setting/current` 失败，请确认后台服务是否正常。

**Comment by dujiaoyang** [comment]
cd cmdb_adminserver/configures/
sed -i 's/opensource/skip-login/g' common.yaml
sed -i 's/opensource/skip-login/g' common.conf
