### ISSUE TITLE
【ESB接口】search_module查询模块的接口，必填"bk_biz_id"的参数填写string类型的参数也能查询成功

### ISSUE THREAD

**Issue by testqwerts** [TencentBlueKing/bk-cmdb#7625]
问题描述：
search_module查询模块的接口，必填"bk_biz_id"的参数填写string类型的参数也能查询成功

一，前置条件：
对应业务下存在模块“ada”
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/679eb977-1551-487e-b3f8-9c667c41bfeb)

二，操作步骤：
1."bk_biz_id"的参数填写string类型的参数
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/a81414c1-84a3-46c3-9f22-a2786f968956)

三，预期结果：
查询失败，提示"bk_biz_id"的参数类型错误

四，实际结果：
查询成功
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/21c3a074-2db8-4a91-8c80-7bd75352fe3f)

**Comment by bd-xiaowang** [comment]
此接口对应的url为：/findmany/module/biz/{bk_biz_id}，因为bk_biz_id设置在url上，在Web框架中，路径参数都会默认解析为字符串类型，所以后端代码会将其进行显式的类型转换，转换为数字类型，所以该问题非bug，为设计如此
