### ISSUE TITLE
【ESB接口】create_set创建集群必填"bk_biz_id"的参数和delete_set删除集群的必填"bk_biz_id"/“bk_set_id”填写string类型的参数接口也能请求成功

### ISSUE THREAD

**Issue by testqwerts** [TencentBlueKing/bk-cmdb#7629]
问题描述：
create_set/必填"bk_biz_id"的参数填写string类型的参数接口也能请求成功

截图：
创建集群
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/e34b0319-3306-4acd-85d9-366651e431b3)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/9031f6e2-aa8d-4426-89de-b5b5f31d7223)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/29052a1f-dc89-4271-acc1-05f7eea20d32)
删除集群
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/a3fa3624-e533-41cf-9930-ca2ef75a49fd)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/55d6e0ce-5aeb-4c63-8a19-a022176ddcdf)

**Comment by bd-xiaowang** [comment]
create_set接口对应的url：/set/{app_id};
delete_set接口对应的url：/set/{app_id}/{set_id}，
因为bk_biz_id（即app_id）设置在url上，在Web框架中，路径参数都会默认解析为字符串类型，所以后端代码会将其进行显式的类型转换，转换为数字类型，所以该问题非bug，为设计如此
