### ISSUE TITLE
【ESB接口】创建模块/删除模块的接口必填"bk_biz_id"/bk_set_id/bk_module_id字段的参数填写string类型的参数接口也能请求成功

### ISSUE THREAD

**Issue by testqwerts** [TencentBlueKing/bk-cmdb#7630]
问题描述：
创建模块/删除模块的接口必填"bk_biz_id"/bk_set_id/bk_module_id字段的参数填写string类型的参数接口也能请求成功

创建模块
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/5174c8eb-6c6f-45d3-b00e-30e6bfb7f4d3)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/5493cc95-bf19-4899-90ce-0c7c0fe38a52)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/5f35d720-8b71-42e9-93d1-e7c0c6796064)

删除模块
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/b6f8f11a-2f73-4d0d-8a82-23824d14aa18)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/7ef5b7f9-54ff-4dea-ad0d-b73507f6dc12)

**Comment by bd-xiaowang** [comment]
create_module接口对应的url：/module/{app_id}/{set_id};
delete_module接口对应的url：/module/{app_id}/{set_id}/{module_id}，
因为bk_biz_id（即app_id）设置在url上，在Web框架中，路径参数都会默认解析为字符串类型，所以后端代码会将其进行显式的类型转换，转换为数字类型，所以该问题非bug，为设计如此
