### ISSUE TITLE
【ESB接口】search_set查询集群接口必填"bk_biz_id"的参数填写string类型的参数接口也能请求成功 

### ISSUE THREAD

**Issue by testqwerts** [TencentBlueKing/bk-cmdb#7634]
问题描述：
search_set查询集群接口必填"bk_biz_id"的参数填写string类型的参数接口也能请求成功 
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/0cf9fbb9-6657-44c3-88ca-1df478ebf543)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/208e085f-db5e-4151-8cd0-f1d01971a508)

**Comment by bd-xiaowang** [comment]
search_set接口对应的url：/set/search/{owner_id}/{app_id};
因为bk_biz_id（即app_id）设置在url上，在Web框架中，路径参数都会默认解析为字符串类型，所以后端代码会将其进行显式的类型转换，转换为数字类型，所以该问题非bug，为设计如此
