### ISSUE TITLE
全部主机过滤后排序错误

### ISSUE THREAD

**Issue by ChainsDW** [TencentBlueKing/bk-cmdb#7670]
在主机全部页，过滤完使用磁盘排序，仅排序了当前页面20条数据
<img width="1167" alt="image" src="https://github.com/TencentBlueKing/bk-cmdb/assets/37797813/56d5b847-e25c-4aeb-9dae-8e674e5b0430">

预期的正常行为
需要全量排序
tips: 当我把/src/scene_server/host_server/logics/appendHostTopoConds函数的allHostIDsArr完全返回时
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/37797813/66977c9b-46f8-4134-aee9-24d92530e8b0)
同时取消searchByHostConds中的设置start为0
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/37797813/b89ce5ed-8528-4b29-84fa-55e8e0d32b95)
可以达到预期行为。
所以如果直接这样改除了降低性能外会有什么风险或者错误吗？

**Comment by ZQHcode** [comment]
全量拉取主机，在数据量大的时候，对db和服务会有影响
