### ISSUE TITLE
【ESB接口】create_object创建模型后，页面显示我还没有对应这个模型的查看权限，我是admin账户

### ISSUE THREAD

**Issue by bd-xiaowang** [TencentBlueKing/bk-cmdb#7694]
如图：create_object接口创建模型后，页面显示我还没有对应这个模型的查看权限，我是admin账户
![18-1](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/5ee66ffb-d5f1-4803-93b2-2b2b62ec8b57)
![18-2](https://github.com/TencentBlueKing/bk-cmdb/assets/102893179/bb97909f-9f03-44be-9f55-36cf31558d0f)

**Comment by bd-xiaowang** [comment]
联调环境（全蓝鲸）上未复现该情况，有可能是paas6环境问题，后续排查

**Comment by ZQHcode** [comment]
空间级版本才有模型查看权限
