### ISSUE TITLE
CMDB创建模型唯一性校验、联合唯一校验失败

### ISSUE THREAD

**Issue by jinxin-fu** [TencentBlueKing/bk-cmdb#7699]
现象：
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/52962500/4fd95e56-179e-48ac-a982-84b2529cdfb2)
模型管理页面创建联合唯一校验失败

版本：
bk-cmdb v3.11.2

coreservice 日志
E1227 10:30:43.376529       1 model/unique_crud.go:512] [UpdateObjectUnique] drop unique index name bkcc_unique_72 for union_test err: "connection(10.8.7.214:8635[-437]) incomplete read of message header: read tcp 10.244.3.201:58708->10.8.7.214:8635: i/o timeout", rid: cc0000cm5ooib8gm9cpaf9bqug
E1227 10:30:43.376548       1 model/unique_crud.go:192] [UpdateObjectUnique] updateDBUnique error: 创建唯一索引失败, raw: &metadata.UpdateUniqueRequest{Keys:[]metadata.UniqueKey{metadata.UniqueKey{Kind:"property", ID:0x15d}, metadata.UniqueKey{Kind:"property", ID:0x15f}, metadata.UniqueKey{Kind:"property", ID:0x15e}}, LastTime:time.Date(2023, time.December, 27, 2, 30, 33, 370685401, time.UTC), TemplateID:0}, rid: cc0000cm5ooib8gm9cpaf9bqug
E1227 10:30:43.376574       1 service/model.go:793] rid: cc0000cm5ooib8gm9cpaf9bqug, err: 创建唯一索引失败
E1227 10:30:43.378345       1 local/txn_manager.go:284] get txn error failed, err: redis: nil, session id: g2s37VfRS5OIy1oYayt4EQ==

**Comment by ZQHcode** [comment]
可以先检查下mongodb的版本和部署方式是否正确 https://github.com/TencentBlueKing/bk-cmdb/blob/master/docs/overview/installation.md
