### ISSUE TITLE
是否支持Mongo分片集群模式

### ISSUE THREAD

**Issue by meegle** [TencentBlueKing/bk-cmdb#7701]
**是否支持Mongo的Sharding Cluster模式**
Mongo-Driver在Mongo4.2开始，事务API已经兼容支持了rs模式和sharding cluster，而为什么BK CMDB只支持rs模式呢？
我看BK CMDB的全局事务是通过在多个mongo客户端间传递session事务信息来实现事务操作的，理论上是否也能支持sharding cluster，只是缺乏测试？或者是否有其他问题要解决？

**预期行为**
Mongo建连支持分片集群，事务控制逻辑不需要调整。

**版本**
v3.12.2

**Comment by ZQHcode** [comment]
目前暂不支持哈
