### ISSUE TITLE
cacheservice 启动失败

### ISSUE THREAD

**Issue by jinxin-fu** [TencentBlueKing/bk-cmdb#7706]
版本： cmdb v1.12.x
mongodb： 4.4
error 日志：
E1229 22:03:49.813186       1 configcenter/viper.go:397] config watch.maxIdleConns less than minimum value, use minimum value 50
F1229 22:03:49.851296       1 event/watch.go:96] mongodb watch failed with conf: {Options:{MajorityCommitted:0xc00049371a MaxAwaitTime:1s OperationType:<nil> Filter:map[] CollectionFilter:<nil> EventStruct:0xc000536220 Collection:cc_SetBase StartAfterToken:0xc00019ab70 StartAtTime:2023-11-07/13:55:01 WatchFatalErrorCallback:0xf43160 Fields:[]}}, err: (Location40415) BSON field '$changeStream.startAfter' is an unknown field.
Stack：
goroutine 189 [running]:
configcenter/src/common/blog/glog.stacks(0x0)
	/data/landun/workspace/cc3gopath/src/configcenter/src/common/blog/glog/glog.go:786 +0x8a
configcenter/src/common/blog/glog.(*loggingT).output(0x1d90e60, 0x3, 0xc0002e6070, {0x172a5f2, 0xc0003e2180}, 0x2, 0x0)
	/data/landun/workspace/cc3gopath/src/configcenter/src/common/blog/glog/glog.go:737 +0x3ab
configcenter/src/common/blog/glog.(*loggingT).printf(0xc000f57e80, 0x40c3eb, {0x12b31db, 0x2c}, {0xc0003e2180, 0x2, 0x2})
	/data/landun/workspace/cc3gopath/src/configcenter/src/common/blog/glog/glog.go:675 +0x110
configcenter/src/common/blog/glog.Fatalf({0x12b31db, 0xc000254460}, {0xc0003e2180, 0xc0000a40c0, 0x1dc58e0})
	/data/landun/workspace/cc3gopath/src/configcenter/src/common/blog/glog/glog.go:1188 +0x3e
configcenter/src/storage/stream/event.(*Event).Watch.func1()
	/data/landun/workspace/cc3gopath/src/configcenter/src/storage/stream/event/watch.go:96 +0x854
created by configcenter/src/storage/stream/event.(*Event).Watch
	/data/landun/workspace/cc3gopath/src/configcenter/src/storage/stream/event/watch.go:37 +0xff

**Comment by jinxin-fu** [comment]
MongoDB 采用华为DDS服务 4.4版本 完全兼容Mongodb 4.4

**Comment by ZQHcode** [comment]
可以按照这个mongodb的部署流程走一遍，看下是否还有这个问题 https://github.com/TencentBlueKing/bk-cmdb/blob/master/docs/overview/installation.md

**Comment by jinxin-fu** [comment]
> 可以按照这个mongodb的部署流程走一遍，看下是否还有这个问题 https://github.com/TencentBlueKing/bk-cmdb/blob/master/docs/overview/installation.md

已解决，选用的华为云DDS服务不支持startafter字段，更换原生mongodb4.4服务恢复正常
