### ISSUE TITLE
导入资产的字段单元格内容限制

### ISSUE THREAD

**Issue by v-49** [TencentBlueKing/bk-cmdb#7730]
目前比如一个单元格的IP集合可能几百条或者更多 但是似乎目前会报
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/140229616/1526f1cd-6e7b-46e5-b4b1-2322623d00cf)
一个的上限似乎在100~200之间 这个能放开么？

**Comment by reggieisrunning** [comment]
> 目前比如一个单元格的IP集合可能几百条或者更多 但是似乎目前会报 ![image](https://private-user-images.githubusercontent.com/140229616/296156754-1526f1cd-6e7b-46e5-b4b1-2322623d00cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDM4ODcsIm5iZiI6MTcwNTA0MzU4NywicGF0aCI6Ii8xNDAyMjk2MTYvMjk2MTU2NzU0LTE1MjZmMWNkLTZlN2ItNDZlNS1iNGIxLTIzMjI2MjNkMDBjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNzEzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDZiMDk2NWQ5ZjA0NjUwYTYzYTI5NTczMDY1NjBlMWU2OGUzNGMyNTI4N2NiMWY0MmFiOWMxZDhmMDI2NTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CsH4DGxHhDjKLrxRDlu4uR3DAZg8jB2sS-wrCpHgAoI) 一个的上限似乎在100~200之间 这个能放开么？

hi，先确认一下：
1. 这个字段是什么类型的(短字符、长字符...)？
2. 为什么会有这么多的IP集合需要放在一个字段中承载？

**Comment by v-49** [comment]
相当于一个区域下有很多个云主机的IP  他们除了IP不同 其他数据都是一样的 所以处理人员把他们合在了一起 我看页面上好像是限制长字符2000 有什么别的类型更好吗  几百个IP可能字符4000甚至更多

**Comment by reggieisrunning** [comment]
> 相当于一个区域下有很多个云主机的IP 他们除了IP不同 其他数据都是一样的 所以处理人员把他们合在了一起 我看页面上好像是限制长字符2000 有什么别的类型更好吗 几百个IP可能字符4000甚至更多

基于这些信息，我描绘一下可能的场景：有一个“区域”的模型，它底下有“南京、广州”这种区域实例，其中有个“管控的主机”字段，希望在这个主机字段里面记录这个区域管理的所有主机IP信息。是这样吗？

**Comment by v-49** [comment]
是的 实际使用上就可能是非常多的IP整合在一个单元格内 作为大的资源模型表  小的资源可能以单IP作为最小颗粒

**Comment by reggieisrunning** [comment]
> 是的 实际使用上就可能是非常多的IP整合在一个单元格内 作为大的资源模型表 小的资源可能以单IP作为最小颗粒

我们正在设计一个“关联”的新字段类型。这个类型是在现有“模型关联”功能的基础上进行扩展的，它将使你能以“字段”的方式将两个不同模型的实例连接起来。
以你的场景为例，如果在“区域”模型下创建这个关联字段，只需将相应的主机实例关联起来，就可以在这个字段中查看所管理的所有主机了。
目前这个功能仍在设计阶段，请关注我们的新版本通知。在此之前，你可以使用“模型关联”功能来实现需求，对于这种涉及“两个不同模型实例”之间关系类的场景，更推荐你使用这种方式，而不是通过另一个实例的字段值来表示这个实例。
