### ISSUE TITLE
Redis 内存高 服务异常问题

### ISSUE THREAD

**Issue by jinxin-fu** [TencentBlueKing/bk-cmdb#7757]
V3.11.2版本中，Redis规格配置1G内存，出现服务异常，查看Redis记录数据百万条左右，咨询一下，Redis在CMDB的具体使用场景是什么， Redis与ES的数据 与mongodb是否一样都是全量存储的

**Comment by bd-xiaowang** [comment]
@jinxin-fu redis非全量存储cmdb数据，在CMDB的具体使用场景为：
- 用于缓存主机快照数据；
- 用于采集器上报采集的主机信息；
- 用于缓存主机拓扑数据；
- 用于事件订阅缓存事件信息；
- 用于一些异步任务执行缓存任务信息；
