### ISSUE TITLE
fix：【CMDB+v3.13.2-feature-layered1】新建“集群”/“模块”“主机”自定义字段 选择内置分组时，添加的字段没有成功显示在对应内置分组下，目前默认新增的字段都是在“业务基础信息”分组下

### ISSUE THREAD

**Issue by testqwerts** [TencentBlueKing/bk-cmdb#7804]
问题描述：
新建“集群”/“模块”“主机”自定义字段 选择内置分组时，添加的字段没有成功显示在对应内置分组下，目前默认新增的字段都是在“业务基础信息”分组下
一，前置条件：
在自定义字段页面“集群”/“模块”“主机”页面

二，操作步骤：
1.点击新建字段输入对应字段信息
2.分组选择“基础信息”
3.点击提交

三，预期结果：
新建字段在“基础信息”分组下

四，实际结果：
添加的字段没有成功显示在对应内置分组下，目前默认新增的字段都是在“业务基础信息”分组下
![企业微信截图_17071869691724](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/3b9279c5-9ae7-4fe5-ad77-086bb6a5a232)
![企业微信截图_17071869962180](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/bf655bca-22ca-408d-9e73-751d6cc77493)

**Comment by wcy00000000000000** [comment]
设计如此，自定义字段必须在业务分组下
