### ISSUE TITLE
fix：【CMDB+v3.13.2-feature-layered1】项目 操作没有‘启用/停用’功能

### ISSUE THREAD

**Issue by testqwerts** [TencentBlueKing/bk-cmdb#7817]
问题描述：
项目 操作没有‘启用/停用’功能
一，前置条件：

二，操作步骤：
1.点击资源--点击项目

三，预期结果：
项目操作有‘启用/停用’功能
四，实际结果：
项目 操作没有‘启用/停用’功能
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/132563061/ddb30ae1-824c-4659-a243-5a7908be6a23)

**Comment by yangyy** [comment]
非内置“项目”，此项目为普通模型
