### ISSUE TITLE
两台服务器之间通过多个端口相连，端口又通过网线相连，怎么通过关联关系导入到CMDB中呢？

### ISSUE THREAD

**Issue by v-49** [TencentBlueKing/bk-cmdb#7833]
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/140229616/88efaffa-2984-44a2-b6ab-cb2dd970e9d2)
我应当创建怎样的模型？几个模型？每个模型又有那些字段？是否需要端口作为中间字段？
然后对于关联关系 如何体现A服务器的ABCD端口连接到B服务器的BD端口这种。

似乎目前的关联只能以服务器作为最小颗粒直接1对1关联，如何再往下再细分一层 使得其端口作为最小颗粒 在一个模型中 存储多个端口，然后又以服务器+端口 对应相应的交换机+端口  多枚举字段与联合唯一需要被使用到吗？
我应当如何获取支持来处理现在的复杂情况

**Comment by reggieisrunning** [comment]
因为关系到你实际的管理场景，所以我个人不好给出一个方案。我们建议如果一个资源有被当做单独的实体进行管理时，则可以独立成为一个模型，这点与OOD理念一致。其中关于交换机、路由器类端口对应的关系，可以看一下表格类型是否可以满足。
这个问题可以到问答社区中问问大家看如何实践会更好，此处就不再做深入的讨论。社区地址：https://bk.tencent.com/s-mart/community/question
