### ISSUE TITLE
authserver正常启用,登陆跳转后提示get user from bk-login failed

### ISSUE THREAD

**Issue by danxiaonuo** [TencentBlueKing/bk-cmdb#7848]
版本：开源版本bk-cmdb [v3.13.2]
bk-paas 、bk-iam 均已部署 
cmdb_webserver error 日志：
I0301 15:00:34.775441   62755 blueking/userinfo.go:103] get user info url: http://www.bking.com/login/accounts/get_user/?bk_token=X6pw5fUADwxfM9MbTXOBOZH3nkaHb4e_gKBDhoCxoIU, result: {"message": "\u7528\u6237\u4fe1\u606f\u83b7\u53d6\u6210\u529f", "code": "00", "data": {"username": "admin", "qq": "", "role": "1", "language": "zh-cn", "phone": "", "wx_userid": "", "email": "", "chname": "", "time_zone": "Asia/Shanghai"}, "result": true}, rid: cc0000cngnq4jthm3jdbstojig
E0301 15:00:34.776162   62755 rest/request.go:343] [apimachinery] GET /api/c/compapi/v2/bk_login/get_user/?bk_token=X6pw5fUADwxfM9MbTXOBOZH3nkaHb4e_gKBDhoCxoIU with body , but Get "/api/c/compapi/v2/bk_login/get_user/?bk_token=X6pw5fUADwxfM9MbTXOBOZH3nkaHb4e_gKBDhoCxoIU": unsupported protocol scheme "", rid: cc0000cngnq4jthm3jdbstojig

**Comment by bd-xiaowang** [comment]
@danxiaonuo 除bk-paas 、bk-iam外还需要部署用户管理
