### ISSUE TITLE
make ui缺少一些包，需要手工安装

### ISSUE THREAD

**Issue by law-lee** [TencentBlueKing/bk-cmdb#7873]
**用文字描述你遇到的问题**
使用make ui NPM=cnpm编译前端时有几个包不会默认安装，需要手工安装

- http-proxy-middleware
- terser-webpack-plugin
- @swc/core
- lodash
- lodash.memoize
- lodash.uniq

**预期行为**
可以自动安装

**版本**
- bk-cmdb的具体版本号
编译分支：3.13.x

**额外信息**
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/19585742/61071e8e-1075-4c98-9677-29ea6417f1a4)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/19585742/ac9b42fd-da77-470e-a2b0-a38d47a340cf)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/19585742/47945a2c-48df-4c04-ac9e-29992a48fb9c)
![image](https://github.com/TencentBlueKing/bk-cmdb/assets/19585742/93c62e7e-99d7-4983-83c2-492e4f280268)

**Comment by yangyy** [comment]
@law-lee 请检查(c)npm是否存在 --depth 0 配置，可去除后重试，同时部分依赖会考虑添加至到顶层

**Comment by yangyy** [comment]
close #7877
