### ISSUE TITLE
主机录入问题

### ISSUE THREAD

**Issue by shsjshentao** [TencentBlueKing/bk-cmdb#8093]
1. 开源版本的主机录入只能支持表格导入么，没有界面化表单操作么？
2. 开源版本能否安装cmdb-agent（bk-nodeman）产品？

**Comment by new9xgh** [comment]
@bd-xiaowang 我的场景是私有部署（开源版），
目前只部署了bk-cmdb,，采集若需要使用bk-nodeman，那么是否只需要部署bk-nodeman即可？
我看部署文档上是，还需要pass？
