### ISSUE TITLE
cmdb中的容器纳管功能如何使用？

### ISSUE THREAD

**Issue by a1226207408** [TencentBlueKing/bk-cmdb#8158]
问题描述
===========
看到3.12.1版本发布了容器纳管功能，但是没有看到功能使用的说明？有没有一个文档或示例能让用户了解这个功能如何使用？

**Comment by bd-xiaowang** [comment]
@a1226207408 容器数据纳管功能主要依赖外部系统将k8s中的容器数据录入cmdb进行管理，cmdb根据录入的数据在业务拓扑中展示；
而容器数据可由以下方式同步到CMDB中：
1、通过蓝鲸容器管理平台（BCS）同步；
2、调用CMDB提供的容器相关操作的接口进行同步；
