### ISSUE TITLE
web_server 模块 的 cookies 中 HTTP_BLUEKING_SUPPLIER_ID 是干啥用的，有对应的设计文档吗

### ISSUE THREAD

**Issue by twgcode** [TencentBlueKing/bk-cmdb#8170]
**功能需求背景，例如你遇到了什么问题**

为什么会有这个点子？或者遇到了什么问题驱使你需要这个功能？

**描述你觉得更好的解决方案**

可以举例子来描述你觉得怎样做会更好

**额外信息**

任何你觉得有助于理解的信息

**Comment by bd-xiaowang** [comment]
@twgcode HTTP_BLUEKING_SUPPLIER_ID 主要用于多租户场景下区分不同的租户
