### ISSUE TITLE
CMDB怎么接入公司的登录系统，进行验证

### ISSUE THREAD

**Issue by xuexuexuexiaoxiao** [TencentBlueKing/bk-cmdb#8171]
**功能需求背景，例如你遇到了什么问题**

为什么会有这个点子？或者遇到了什么问题驱使你需要这个功能？

**描述你觉得更好的解决方案**

可以举例子来描述你觉得怎样做会更好

**额外信息**

任何你觉得有助于理解的信息

**Comment by sangta0** [comment]
看了一遍没有直接对接的，像bk-user,bk-iam引进来又特别重，部署一套下来人都要麻了，所以只能自己以系统里提供的登录插件的方式实现自己的登录逻辑
1. 在 src/web_server/middleware/user/plugins/methods 里实现你自己的登录和校验逻辑，你可以参考里面已经实现的几种登录认证
2. 在 src/common/definitions.go 里定义你自己的LoginPluginVersion，
3. 在配置文件common.yml中修改webServer.login.version换成你自己在第二步注册的登录方式
可能还涉及到修改/src/web_server/middleware/login.go里校验登录逻辑
